Repository hiero-ledger/hiero-json-rpc-relay, pull requests merged in 2022-09, with the labels that each got.

#489 Rolling restarts done via cronjob
  helm-chart/environments/minikube.yaml
  helm-chart/templates/cronjob.yaml
  helm-chart/templates/role.yaml
  helm-chart/templates/rolebinding.yaml
  helm-chart/templates/serviceaccount.yaml
  helm-chart/values.yaml
Labels: P1, process

#496 Bump 0.7.0
  docker-compose.yml
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: enhancement, P1, process

#503 DApp Test stuck running bootstrap action step
  package-lock.json
  packages/server/package.json
  packages/server/tests/acceptance/index.spec.ts
  packages/server/tests/helpers/prerequisite.ts
Labels: bug, limechain, P1, process

#484 Bump mirror 0.64.0 and misc test setup fixes
  dapp-example/tests/support/bootstrap.js
  packages/server/tests/acceptance/htsPrecompile.spec.ts
  packages/server/tests/acceptance/index.spec.ts
  packages/server/tests/helpers/prerequisite.ts
Labels: enhancement, P2, process

#467 Add HTS Precompile Acceptance Tests for Expiry Info methods
  package.json
  packages/server/package.json
  packages/server/tests/acceptance/htsPrecompile.spec.ts
  packages/server/tests/acceptance/index.spec.ts
  packages/server/tests/contracts/BaseHTS.json
  packages/server/tests/contracts/BaseHTS.sol
  packages/server/tests/contracts/HederaTokenService.json
  packages/server/tests/contracts/HederaTokenService.sol
  packages/server/tests/contracts/IHederaTokenService.json
  packages/server/tests/contracts/IHederaTokenService.sol
  packages/server/tests/helpers/prerequisite.ts
  packages/server/tests/localAcceptance.env
Labels: enhancement, limechain, P2

#515 Split acceptance tests into separate jobs
  .github/workflows/acceptance.yml
  dapp-example/tests/e2e/index.spec.js
  dapp-example/tests/support/bootstrap.js
  package.json
  packages/server/tests/acceptance/erc20.spec.ts
  packages/server/tests/acceptance/htsPrecompile.spec.ts
  packages/server/tests/acceptance/htsPrecompile_v1.spec.ts
  packages/server/tests/acceptance/rpc.spec.ts
  packages/server/tests/helpers/prerequisite.ts
Labels: enhancement, P2, process

#468 Add HTS Precompile tests for token check methods
  packages/server/tests/acceptance/htsPrecompile.spec.ts
  packages/server/tests/contracts/BaseHTS.json
  packages/server/tests/contracts/BaseHTS.sol
  packages/server/tests/contracts/FeeHelper.json
  packages/server/tests/contracts/HederaTokenService.sol
  packages/server/tests/contracts/IHederaTokenService.json
  packages/server/tests/contracts/IHederaTokenService.sol
  packages/server/tests/contracts/KeyHelper.json
Labels: enhancement, limechain, P2

#523 Add IERC transferFrom to HTS Precompile Acceptance Tests
  dapp-example/tests/support/bootstrap.js
  packages/server/tests/acceptance/htsPrecompile.spec.ts
  packages/server/tests/contracts/BaseHTS.json
  packages/server/tests/contracts/BaseHTS.sol
  packages/server/tests/contracts/ERC721Mock.json
Labels: enhancement, limechain, P1, process

#525 Add example subgraph
  tools/hardhat-example/contracts/Greeter.sol
  tools/subgraph-example/.gitignore
  tools/subgraph-example/README.md
  tools/subgraph-example/abis/Greeter.json
  tools/subgraph-example/docker-compose.yml
  tools/subgraph-example/networks.json
  tools/subgraph-example/package.json
  tools/subgraph-example/schema.graphql
  tools/subgraph-example/src/greeter.ts
  tools/subgraph-example/subgraph.yaml
  tools/subgraph-example/tests/greeter-utils.ts
  tools/subgraph-example/tests/greeter.test.ts
  tools/subgraph-example/tsconfig.json
  tools/subgraph-example/yarn.lock
  tools/truffle-example/contracts/Greeter.sol
  tools/web3js-example/contract/Greeter.json
  tools/web3js-example/contract/Greeter.sol
Labels: enhancement, P2, dev tools

#527 initial pass for tests
  packages/server/tests/acceptance/htsPrecompile.spec.ts
  packages/server/tests/contracts/BaseHTS.json
  packages/server/tests/contracts/BaseHTS.sol
  packages/server/tests/contracts/HederaTokenService.json
  packages/server/tests/contracts/HederaTokenService.sol
  packages/server/tests/contracts/IHederaTokenService.json
  packages/server/tests/contracts/IHederaTokenService.sol
Labels: enhancement, P2, process

#481 Add Rate Limit Support
  .env.example
  README.md
  docs/rate-limiting.md
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/server/src/koaJsonRpc/index.ts
  packages/server/src/koaJsonRpc/lib/RpcError.ts
  packages/server/src/koaJsonRpc/lib/RpcInvalidError.ts
  packages/server/src/koaJsonRpc/lib/RpcResponse.ts
  packages/server/src/koaJsonRpc/lib/isJson.ts
  packages/server/src/koaJsonRpc/lib/methodConfiguration.ts
  packages/server/src/ratelimit/index.ts
  packages/server/src/server.ts
  packages/server/tests/acceptance/index.spec.ts
  packages/server/tests/acceptance/rpc.spec.ts
  packages/server/tests/localAcceptance.env
Labels: enhancement, limechain, P2

#532 Support block tags in getLogs()
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: bug, limechain, P1

#529 Update eth_getBalance to use mirror node
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/server/tests/acceptance/rpc.spec.ts
  tools/hardhat-example/test/rpc.js
Labels: enhancement, P1

#541 Log fileId and file size for callData
  packages/relay/src/lib/clients/sdkClient.ts
Labels: enhancement, P1

#538 Bump 0-9-0 snapshot
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: P1, process

#546 540 capture calldata cp
  packages/relay/src/lib/clients/sdkClient.ts
Labels: enhancement, P1

#539 Bump version to 0.8.0-rc1
  README.md
  docker-compose.yml
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: P1, process

#548 Rate limit test workaround
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/server/tests/acceptance/rpc.spec.ts
Labels: enhancement, P2, process

#544 Bump services 0.30 and mirror 0.65.0-beta1
  packages/server/tests/acceptance/index.spec.ts
  packages/server/tests/helpers/prerequisite.ts
Labels: P2, process

#557 Update eth_transactioncount to use mirror (0.8)
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/precheck.spec.ts
Labels: enhancement, P1

#558 update nonce precheck logic (0.8)
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/precheck.ts
  packages/relay/tests/lib/precheck.spec.ts
Labels: enhancement, P1

#563 Bump 0.8.0-rc2
  docker-compose.yml
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: enhancement, P1

#570 Bump 0.8.0
  docker-compose.yml
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: enhancement, P1

#568 Nonce to 0 for Hedera native transactions
  dapp-example/package-lock.json
  dapp-example/package.json
  dapp-example/synpress.json
  packages/relay/src/lib/eth.ts
  packages/server/tests/acceptance/index.spec.ts
  packages/server/tests/acceptance/rpc.spec.ts
  packages/server/tests/helpers/prerequisite.ts
Labels: bug, limechain
