Repository hiero-ledger/hiero-json-rpc-relay, pull requests merged in 2022-05, with the labels that each got.

#71 metamask properly estimating gas
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/mirrorNode.ts
  packages/relay/src/lib/model.ts
Labels: enhancement, P1

#73 Add MirrorNode Client to make calls to real Mirror Node
  package-lock.json
  package.json
  packages/relay/src/lib/clients/consensusNodeClient.ts
  packages/relay/src/lib/clients/index.ts
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/mirrorNode.ts
  packages/relay/src/lib/relay.ts
  packages/relay/tests/lib/mirrorNode.spec.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
  packages/relay/tests/test.env
Labels: enhancement, P1

#79 Clarify development purpose of docker compose
  README.md
Labels: documentation, enhancement, P2, process

#84 Add support for eth_getTransactionByHash with mocked data
  packages/relay/src/index.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/model.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/server/src/server.ts
  packages/server/tests/server.spec.ts
Labels: enhancement, P2

#74 Implement eth_blockNumber
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
  packages/relay/tests/test.env
  packages/server/tests/server.spec.ts
Labels: enhancement, P1

#82 Chain ID and FeeHistory Tweaks
  packages/relay/src/index.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/mirrorNode.ts
  packages/relay/src/lib/net.ts
  packages/relay/src/lib/relay.ts
  packages/server/src/server.ts
Labels: P1

#80 Add support for getBlockBy, getBlockTransactionCountBy and getTransactionByBlock endpoints
  packages/relay/src/index.ts
  packages/relay/src/lib/clients/consensusNodeClient.ts
  packages/relay/src/lib/clients/index.ts
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/model.ts
  packages/relay/src/lib/relay.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
  packages/server/src/server.ts
Labels: enhancement, P1

#83 eth_getTransactionReceiptByHash
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/model.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: enhancement, P2

#91 Support block tags in 5 APIs
  .prettierrc
  packages/relay/src/index.ts
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/server/src/server.ts
Labels: enhancement, P1

#95 Fix regression on hex block numbers
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: bug, P1

#98 Fix blocks transactions and r and s signatures assignments
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/mirrorNode.ts
  packages/relay/src/lib/model.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: bug, P1

#100 Bring getBlockBy... into execution-api schema compliance
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/model.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: enhancement, P2

#108 Add cost call to avoid insufficient fee issue
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/eth.ts
Labels: bug, P1
