Repository hiero-ledger/hiero-json-rpc-relay, pull requests merged in 2022-08, with the labels that each got.

#397 Bump 0.6.0-snapshot
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: enhancement, P1

#396 Bump 0.5.0-rc1
  docker-compose.yml
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: enhancement, P1

#415 Updating README with example scrape config and note about getting the…
  README.md
Labels: enhancement, process

#419 return 0x instead of 0x0 for non existing contract addresses given to…
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/server/tests/acceptance/erc20.spec.ts
  packages/server/tests/acceptance/rpc.spec.ts
Labels: bug, P1

#420 Bump v0.5.0
  docker-compose.yml
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: enhancement, P1

#422 Enhance README and newman coverage
  README.md
  docs/rpc-api.md
  packages/server/tests/postman.json
Labels: documentation, enhancement, P3, process

#418 Query mirror node for deployed_bytecode in eth_getCode
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/server/tests/acceptance/index.spec.ts
Labels: enhancement, limechain, P1

#429 Add truffle readme.md
  tools/truffle-example/README.md
Labels: documentation, enhancement, limechain, P2

#428 Add web3js readme.md
  tools/web3js-example/README.md
Labels: documentation, enhancement, limechain, P2

#423 Add trace id to logs
  packages/relay/src/formatters.ts
  packages/relay/src/index.ts
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/precheck.ts
  packages/server/src/server.ts
Labels: enhancement, P3

#430 test: Acceptance tests seems inconsistent
  packages/server/tests/acceptance/rpc.spec.ts
Labels: enhancement, limechain, P2

#427 Add comparison analysis table for supported tool
  tools/README.md
Labels: documentation, enhancement, limechain, P2

#432 Resolve issues with some fields in eth_getBlock
  packages/relay/src/lib/eth.ts
  packages/relay/tests/helpers.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/server/tests/helpers/assertions.ts
Labels: enhancement, limechain, P1, dev tools

#424 Add acceptance test support for hts precompile
  packages/server/tests/acceptance/htsPrecompile.spec.ts
  packages/server/tests/contracts/BaseHTS.json
  packages/server/tests/contracts/BaseHTS.sol
  packages/server/tests/contracts/FeeHelper.json
  packages/server/tests/contracts/FeeHelper.sol
  packages/server/tests/contracts/HederaResponseCodes.json
  packages/server/tests/contracts/HederaResponseCodes.sol
  packages/server/tests/contracts/HederaTokenService.json
  packages/server/tests/contracts/HederaTokenService.sol
  packages/server/tests/contracts/IHederaTokenService.json
  packages/server/tests/contracts/IHederaTokenService.sol
  packages/server/tests/contracts/KeyHelper.json
  packages/server/tests/contracts/KeyHelper.sol
Labels: enhancement, limechain, P1

#436 Add support for k6 perf tests
  k6/ENV.csh
  k6/README.md
  k6/run.sh
  k6/src/lib/common.js
  k6/src/lib/constants.js
  k6/src/lib/parameters.js
  k6/src/scenarios/apis.js
  k6/src/scenarios/test/bootstrapEnvParameters.js
  k6/src/scenarios/test/common.js
  k6/src/scenarios/test/eth_accounts.js
  k6/src/scenarios/test/eth_blockNumber.js
  k6/src/scenarios/test/eth_call.js
  k6/src/scenarios/test/eth_chainId.js
  k6/src/scenarios/test/eth_coinbase.js
  k6/src/scenarios/test/eth_estimateGas.js
  k6/src/scenarios/test/eth_feeHistory.js
  k6/src/scenarios/test/eth_gasPrice.js
  k6/src/scenarios/test/eth_getBalance.js
  k6/src/scenarios/test/eth_getBlockByHash.js
  k6/src/scenarios/test/eth_getBlockByNumber.js
  k6/src/scenarios/test/eth_getBlockTransactionCountByHash.js
  k6/src/scenarios/test/eth_getBlockTransactionCountByNumber.js
  k6/src/scenarios/test/eth_getCode.js
  k6/src/scenarios/test/eth_getLogs.js
  k6/src/scenarios/test/eth_getStorageAt.js
  k6/src/scenarios/test/eth_getTransactionByBlockHashAndIndex.js
  k6/src/scenarios/test/eth_getTransactionByBlockNumberAndIndex.js
  k6/src/scenarios/test/eth_getTransactionByHash.js
  k6/src/scenarios/test/eth_getTransactionCount.js
  k6/src/scenarios/test/eth_getTransactionReceipt.js
  k6/src/scenarios/test/eth_getUncleByBlockHashAndIndex.js
  k6/src/scenarios/test/eth_getUncleByBlockNumberAndIndex.js
  k6/src/scenarios/test/eth_getUncleCountByBlockHash.js
  k6/src/scenarios/test/eth_getUncleCountByBlockNumber.js
  k6/src/scenarios/test/eth_getWork.js
  k6/src/scenarios/test/eth_hashrate.js
  k6/src/scenarios/test/eth_mining.js
  k6/src/scenarios/test/eth_protocolVersion.js
  k6/src/scenarios/test/eth_sendRawTransaction.js
  k6/src/scenarios/test/eth_sendTransaction.js
  k6/src/scenarios/test/eth_sign.js
  k6/src/scenarios/test/eth_signTransaction.js
  k6/src/scenarios/test/eth_submitHashrate.js
  k6/src/scenarios/test/eth_submitWork.js
  k6/src/scenarios/test/eth_syncing.js
  k6/src/scenarios/test/index.js
  k6/src/scenarios/test/net_listening.js
  k6/src/scenarios/test/net_version.js
  k6/src/scenarios/test/web3_clientVersion.js
  k6/src/scenarios/test/web3_client_version.js
Labels: enhancement, P2, process

#445 Bump 0.7.0-snapshot
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: enhancement, P1, process

#443 Add hts precompile approval/allowance tests
  packages/server/tests/acceptance/htsPrecompile.spec.ts
  packages/server/tests/contracts/BaseHTS.json
  packages/server/tests/contracts/BaseHTS.sol
Labels: enhancement, limechain, P1, process

#447 Add check for valid account in balance precheck
  packages/relay/src/lib/precheck.ts
  packages/relay/tests/lib/precheck.spec.ts
  packages/server/tests/acceptance/erc20.spec.ts
  packages/server/tests/acceptance/htsPrecompile.spec.ts
  packages/server/tests/acceptance/rpc.spec.ts
  packages/server/tests/clients/servicesClient.ts
Labels: enhancement, P1, process

#444 Bump 0.6.0-rc1
  docker-compose.yml
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
  packages/server/tests/acceptance/erc20.spec.ts
  packages/server/tests/acceptance/htsPrecompile.spec.ts
  packages/server/tests/acceptance/rpc.spec.ts
Labels: enhancement, P1, process

#450 Add htsPreCompile get tokenInfo acceptance tests
  packages/server/tests/acceptance/htsPrecompile.spec.ts
  packages/server/tests/contracts/BaseHTS.json
  packages/server/tests/contracts/BaseHTS.sol
Labels: enhancement, limechain, P1

#453 402 htsprecompile acceptance tests for pause unpause
  packages/server/tests/acceptance/htsPrecompile.spec.ts
  packages/server/tests/contracts/BaseHTS.json
  packages/server/tests/contracts/BaseHTS.sol
Labels: enhancement, limechain, P1, process

#455 add htsprecompile acceptance tests for freeze/unfreeze
  packages/server/tests/acceptance/htsPrecompile.spec.ts
  packages/server/tests/contracts/BaseHTS.json
  packages/server/tests/contracts/BaseHTS.sol
Labels: enhancement, P2, process

#460 Bump 0.6.0
  README.md
  docker-compose.yml
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  package.json
  packages/relay/package.json
  packages/server/package.json
  packages/server/tests/postman.json
Labels: enhancement, P1

#457 HTS precompile tests for wipe token methods
  packages/server/tests/acceptance/erc20.spec.ts
  packages/server/tests/acceptance/htsPrecompile.spec.ts
  packages/server/tests/contracts/BaseHTS.json
  packages/server/tests/contracts/BaseHTS.sol
  packages/server/tests/helpers/assertions.ts
Labels: enhancement, limechain, P1

#452 Add HtsPrecompile test support for getTokenCustomFees
  packages/server/tests/acceptance/htsPrecompile.spec.ts
  packages/server/tests/contracts/BaseHTS.json
  packages/server/tests/contracts/BaseHTS.sol
Labels: enhancement, limechain, P1, process

#459 HTS precompile tests for token default status
  packages/server/tests/acceptance/htsPrecompile.spec.ts
  packages/server/tests/contracts/BaseHTS.json
  packages/server/tests/contracts/BaseHTS.sol
Labels: enhancement, limechain, P2

#458 Describe the invalid precomputed address issue in the tools readme
  tools/README.md
Labels: documentation, enhancement, limechain, P1, dev tools

#461 Add HtsPrecompile test for token delete
  packages/server/tests/acceptance/htsPrecompile.spec.ts
  packages/server/tests/contracts/BaseHTS.json
  packages/server/tests/contracts/BaseHTS.sol
  packages/server/tests/contracts/HederaTokenService.sol
  packages/server/tests/contracts/IHederaTokenService.json
  packages/server/tests/contracts/IHederaTokenService.sol
Labels: enhancement, limechain, P2

#463 Add HTS Precompile Acceptance Tests for KYC methods
  packages/server/tests/acceptance/htsPrecompile.spec.ts
  packages/server/tests/contracts/BaseHTS.json
  packages/server/tests/contracts/BaseHTS.sol
  packages/server/tests/contracts/HederaTokenService.json
  packages/server/tests/contracts/HederaTokenService.sol
  packages/server/tests/contracts/IHederaTokenService.json
  packages/server/tests/contracts/IHederaTokenService.sol
Labels: enhancement, limechain, P2

#466 Fix postman eth_getBalance test & misc edits
  k6/README.md
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/eth.ts
  packages/server/tests/postman.json
Labels: bug, P3, process

#474 Bump sdk to v2.18.0
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: enhancement, P1, dependencies

#473 add trace id to error response messages
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/server/src/server.ts
  packages/server/tests/helpers/assertions.ts
  packages/server/tests/integration/server.spec.ts
  packages/server/tests/postman.json
Labels: enhancement, P3

#480 Bump 0.8.0-snapshot
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: enhancement, P1, process

#479 Bump 0.7.0-rc1
  docker-compose.yml
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: enhancement, P1, process
