Repository hiero-ledger/hiero-json-rpc-relay, pull requests merged in 2022-06, with the labels that each got.

#103 eth_getLogs
  packages/relay/src/index.ts
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/model.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
  packages/server/src/server.ts
  packages/server/tests/server.spec.ts
Labels: enhancement, P2

#132 Improve server logging and metrics
  packages/relay/src/index.ts
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/mirrorNode.ts
  packages/relay/src/lib/relay.ts
  packages/server/src/server.ts
  packages/server/tests/acceptance.spec.ts
Labels: enhancement, P3

#144 Bump version to 0.1.0-rc1
  .github/workflows/release-production.yml
  docker-compose.yml
  helm-chart/Chart.yaml
  helm-chart/values.yaml
  packages/relay/package.json
  packages/server/package.json
Labels: P1, process

#147 Bump version to 0.2.0-SNAPSHOT
  .github/workflows/release-production.yml
  helm-chart/Chart.yaml
  helm-chart/values.yaml
  packages/relay/package.json
  packages/server/package.json
Labels: enhancement, P1, process

#143 add postman tests
  README.md
  packages/server/tests/postman.json
Labels: enhancement, P1, process

#151 Add artifact build and upload logic to release logic
  .github/workflows/release-production.yml
Labels: P2, process

#152 chore: remove duplicate restart policy from docker-compose
  docker-compose.yml
Labels: bug, P2, process

#156 Update block hex to be 8 bytes in length
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: bug, P1

#157 Update block hex to be 8 bytes in length (release 0.1)
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: bug, P1

#158 Remove org path from artifact build command
  .github/workflows/release-production.yml
Labels: P1, process

#136 Update gas calculation in eth method
  package-lock.json
  packages/relay/package.json
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/server/tests/acceptance.spec.ts
Labels: enhancement, limechain, P1

#163 Fix fallback gas fee calculation logic
  package-lock.json
  package.json
  packages/relay/package.json
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/eth.ts
  packages/server/package.json
  packages/server/tests/acceptance.spec.ts
Labels: bug, P1

#133 Improve duplicate transaction management
  package-lock.json
  packages/relay/package.json
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/errors.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/precheck.ts
Labels: enhancement, limechain, P1

#168 049 hbar transfer demo docs
  docs/examples/.env.sample
  docs/examples/account-alias-ecdsa.js
  docs/examples/package.json
  docs/hbar-transfer.md
  docs/images/importAccountButton.png
  docs/images/importAccountPanel.png
  docs/images/importedAccount.png
  docs/images/networkPanel.png
  docs/images/sendAddress.png
  docs/images/sendConfirm.png
  docs/images/sendPending.png
  docs/images/sendPopulate.png
  docs/images/sendReceived.png
  docs/images/sendSettled.png
Labels: documentation, enhancement, P2

#170 Expand acceptance test to query external nodes
  package-lock.json
  packages/server/package.json
  packages/server/tests/acceptance.spec.ts
Labels: enhancement, P2, process

#172 Signed transaction generator
  packages/server/tests/acceptance.spec.ts
  packages/server/tests/utils.ts
Labels: enhancement, P1, process

#177 Fix latency metric capture logic
  packages/server/src/server.ts
Labels: bug, P2, process

#182 Add gas cache logic to release 0.1
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/eth.ts
Labels: enhancement, P1

#139 Acceptance tests - eth_getBalance, eth_getTransactionCount
  package-lock.json
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/helpers.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
  packages/server/package.json
  packages/server/tests/acceptance.spec.ts
  packages/server/tests/utils.ts
Labels: enhancement, P2, process

#187 Improve startup logs
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/relay.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/server/tests/server.spec.ts
Labels: enhancement, P1, process

#199 Fix acceptance test timeout issue
  packages/server/tests/acceptance.spec.ts
Labels: bug, P1, process

#198 Workaround for varying eth_getBalance acceptance test result on primary account
  packages/server/tests/acceptance.spec.ts
Labels: bug, P2, process

#202 Bump release to 0.1.0
  .github/workflows/release-production.yml
  docker-compose.yml
  helm-chart/Chart.yaml
  helm-chart/values.yaml
  package.json
  packages/relay/package.json
  packages/server/package.json
  packages/server/tests/acceptance.spec.ts
Labels: enhancement, P1, process

#185 Fix transactionsRoot return value in case of empty transactions array
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: bug, P1, dev tools

#205 Improve release git action flow
  .github/workflows/release-production.yml
Labels: enhancement, P2, process

#192 Acceptance tests for eth_getTransactionReceipt
  packages/server/tests/acceptance.spec.ts
  packages/server/tests/utils.ts
Labels: enhancement, P2, process

#173 154 document token transfer
  docs/examples/account-alias-ecdsa.js
  docs/examples/token-transfer-setup.js
  docs/hbar-transfer.md
  docs/images/ImportTokens.png
  docs/images/assetsMenu.png
  docs/images/importTokenAddress.png
  docs/images/importTokenDetails.png
  docs/images/selectAsset.png
  docs/images/sendAssetConfirm.png
  docs/images/sendAssetDecrease.png
  docs/images/sendAssetPending.png
  docs/images/sendAssetPopulate.png
  docs/images/sendAssetReceived.png
  docs/images/sendAssetSettled.png
  docs/images/sendButton.png
  docs/transfer-guide.md
Labels: documentation, enhancement, P2

#208 Improve transfer-only gas estimate
  packages/relay/src/index.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/server/src/server.ts
Labels: enhancement, P2

#180 Add reusable DApp example
  dapp-example/.gitignore
  dapp-example/README.md
  dapp-example/package-lock.json
  dapp-example/package.json
  dapp-example/public/favicon.ico
  dapp-example/public/index.html
  dapp-example/public/logo192.png
  dapp-example/public/logo512.png
  dapp-example/public/manifest.json
  dapp-example/public/robots.txt
  dapp-example/screenshot1.png
  dapp-example/src/App.js
  dapp-example/src/components/AccountActivationForm.js
  dapp-example/src/components/ContractInteractions.js
  dapp-example/src/components/TransferHTSTokensForm.js
  dapp-example/src/contracts/ERC20ABI.json
  dapp-example/src/contracts/Greeter.json
  dapp-example/src/hooks/useHederaSdk.js
  dapp-example/src/index.js
Labels: documentation, enhancement, P2

#214 Improve client logs and capture client metrics
  packages/relay/src/index.ts
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/relay.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
  packages/relay/tests/lib/net.spec.ts
  packages/relay/tests/lib/web3.spec.ts
  packages/server/src/server.ts
  packages/server/tests/acceptance.spec.ts
Labels: enhancement, P2

#190 Ignore vscode and devcontainer tracking
  .gitignore
Labels: enhancement, P2, dev tools

#229 Add logic to clear metric from registry before create
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/server/src/server.ts
Labels: bug, P1, process

#235 Add transactionhash to receipt logs
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: enhancement, P2, dev tools

#240 Handle Mirror Node network fee errors
  package-lock.json
  packages/relay/package.json
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: enhancement, P1

#233 Acceptance test plan
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/server/tests/acceptance/rpc.spec.ts
  packages/server/tests/helpers/assertions.ts
  packages/server/tests/helpers/utils.ts
Labels: Epic, P2, process

#244 Improve acceptance tests run against remote instances
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/relay.ts
  packages/server/tests/acceptance/rpc.spec.ts
  packages/server/tests/clients/mirrorClient.ts
  packages/server/tests/clients/servicesClient.ts
Labels: enhancement, P1, process

#248 Bump v0.3.0-SNAPSHOT
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: enhancement, P1, process

#246 Bump v0.2.0-rc1
  docker-compose.yml
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: enhancement, P1, process

#249 Deployment selector env and secrets
  helm-chart/templates/deployment.yaml
  helm-chart/templates/secret.yaml
  helm-chart/values.yaml
Labels: enhancement, P1, process

#263 Fix block root properties default hash formats
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/server/tests/helpers/assertions.ts
Labels: bug, enhancement, dev tools

#264 Bring over chart deployment advancement from 0.3.0-SNAPSHOT to 0.2
  helm-chart/templates/deployment.yaml
  helm-chart/templates/secret.yaml
  helm-chart/values.yaml
Labels: enhancement, P2, process

#260 Fix nonce zerohexbytes regression
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/server/tests/helpers/assertions.ts
Labels: bug, P1

#262 Improve MirrorNodeClient 500 handling
  packages/relay/src/lib/clients/mirrorNodeClient.ts
Labels: bug, P2

#266 Bump v0.2.0-rc2
  docker-compose.yml
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: enhancement, P1, process

#270 268 fix get logs
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/server/tests/acceptance/rpc.spec.ts
Labels: bug, P1

#276 Bump v0.2.0rc3
  docker-compose.yml
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: enhancement, P1

#275 Expand DApp SDK client to support non local envs
  dapp-example/tests/support/bootstrap.js
Labels: enhancement, P2

#241 Add erc20.spec.test
  package-lock.json
  package.json
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/server/package.json
  packages/server/tests/acceptance/erc20.spec.ts
  packages/server/tests/acceptance/index.spec.ts
  packages/server/tests/acceptance/rpc.spec.ts
  packages/server/tests/clients/mirrorClient.ts
  packages/server/tests/clients/servicesClient.ts
  packages/server/tests/contracts/ERC20DecimalsMock.json
  packages/server/tests/contracts/ERC20Mock.json
  packages/server/tests/helpers/utils.ts
Labels: enhancement

#282 Bump v0.2.0
  docker-compose.yml
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: enhancement, P1, process

#286 DApp tests not working on public networks
  dapp-example/src/App.js
  dapp-example/tests/e2e/index.spec.js
  dapp-example/tests/support/bootstrap.js
  package-lock.json
  packages/relay/src/lib/clients/mirrorNodeClient.ts
Labels: enhancement
