Repository hiero-ledger/hiero-json-rpc-relay, pull requests merged in 2022-12, with the labels that each got.

#718 Bump Test Images version
  packages/server/src/server.ts
  packages/server/tests/acceptance/htsPrecompile/tokenCreate.spec.ts
  packages/server/tests/acceptance/htsPrecompile/tokenManagement.spec.ts
  packages/server/tests/acceptance/index.spec.ts
  packages/server/tests/helpers/prerequisite.ts
Labels: enhancement, P2, process

#729 Bump test sdk version
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
  packages/server/src/server.ts
  packages/server/tests/acceptance/htsPrecompile/tokenCreate.spec.ts
  packages/server/tests/acceptance/htsPrecompile/tokenManagement.spec.ts
  packages/server/tests/acceptance/index.spec.ts
  packages/server/tests/helpers/prerequisite.ts
Labels: enhancement, P1, process, dependencies

#731 Bump 0.13.0-rc2
  docker-compose.yml
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: enhancement, P1, process

#733 Handle empty state_changes array in contract details
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: bug, P1

#734 Handle empty state_changes array in contract details (#733)
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: enhancement, P1, process

#717 eth_getBalance workaround
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/helpers.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
  packages/server/tests/acceptance/rpc.spec.ts
Labels: enhancement, limechain, P1

#736 Bump 0.13.0-rc3
  docker-compose.yml
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: enhancement, P1, process

#738 Return 32 byte 0 on empty state_changes array
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: bug, P1

#739 Cherry pick #738 into 0.13.0
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: enhancement, P1, process

#740 Bump to v0.13.0-rc4
  docker-compose.yml
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: enhancement, P1, process

#746 Bump 0.13.0
  docker-compose.yml
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: enhancement, P1, process

#745 Add a test values yaml for chart
  helm-chart/value-test.yaml
Labels: enhancement, P2, process

#744 Check `to` parameter in `eth_call` method
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: bug

#753 Cherry pick commits for v0.13.1
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/helpers.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
  packages/server/tests/acceptance/rpc.spec.ts
Labels: enhancement, P1, process

#754 Bump v0.13.1
  docker-compose.yml
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: enhancement, P1, process

#741 Add config support for SDK transport security
  .env.example
  helm-chart/templates/deployment.yaml
  helm-chart/values.yaml
  packages/relay/src/lib/relay.ts
Labels: enhancement, P2, process

#719 eth_getLogs - add support for multiple addresses
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/helpers.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/server/tests/acceptance/index.spec.ts
  packages/server/tests/acceptance/rpc.spec.ts
Labels: bug, enhancement, limechain, P2

#750 Events not returned on getPastEvents call
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: bug, limechain, P2

#737 Update the subgraph example
  tools/subgraph-example/.env.example
  tools/subgraph-example/.eslintignore
  tools/subgraph-example/.eslintrc.js
  tools/subgraph-example/.gitignore
  tools/subgraph-example/.npmignore
  tools/subgraph-example/.prettierignore
  tools/subgraph-example/.prettierrc
  tools/subgraph-example/.solhint.json
  tools/subgraph-example/.solhintignore
  tools/subgraph-example/README.md
  tools/subgraph-example/abis/Greeter.json
  tools/subgraph-example/configs/latest.json
  tools/subgraph-example/contracts/ExampleERC20.sol
  tools/subgraph-example/contracts/ExampleERC721.sol
  tools/subgraph-example/contracts/GravatarRegistry.sol
  tools/subgraph-example/docker-compose.yml
  tools/subgraph-example/hardhat.config.ts
  tools/subgraph-example/matchstick.yaml
  tools/subgraph-example/networks.json
  tools/subgraph-example/package-lock.json
  tools/subgraph-example/package.json
  tools/subgraph-example/schema.graphql
  tools/subgraph-example/scripts/create-gravatar.ts
  tools/subgraph-example/scripts/erc20-transfer.ts
  tools/subgraph-example/scripts/erc721-mint.ts
  tools/subgraph-example/scripts/index.ts
  tools/subgraph-example/scripts/update-gravatar.ts
  tools/subgraph-example/src/greeter.ts
  tools/subgraph-example/subgraph.yaml
  tools/subgraph-example/subgraph/abis/ExampleERC20.json
  tools/subgraph-example/subgraph/abis/ExampleERC721.json
  tools/subgraph-example/subgraph/abis/GravatarRegistry.json
  tools/subgraph-example/subgraph/networks.json
  tools/subgraph-example/subgraph/package.json
  tools/subgraph-example/subgraph/schema.graphql
  tools/subgraph-example/subgraph/src/example-erc-20.ts
  tools/subgraph-example/subgraph/src/example-erc-721.ts
  tools/subgraph-example/subgraph/src/gravatar-registry.ts
  tools/subgraph-example/subgraph/subgraph.yaml
  tools/subgraph-example/subgraph/tests/example-erc-20-utils.ts
  tools/subgraph-example/subgraph/tests/example-erc-20.test.ts
  tools/subgraph-example/subgraph/tests/gravatar-registry-utils.ts
  tools/subgraph-example/subgraph/tests/gravatar-registry.test.ts
  tools/subgraph-example/subgraph/tsconfig.json
  tools/subgraph-example/tests/greeter-utils.ts
  tools/subgraph-example/tests/greeter.test.ts
  tools/subgraph-example/tsconfig.json
  tools/subgraph-example/yarn.lock
Labels: enhancement, limechain, P1, dev tools

#764 Add Subgraph Example Tests
  tools/subgraph-example/README.md
  tools/subgraph-example/configs/local-test.json
  tools/subgraph-example/hardhat.config.ts
  tools/subgraph-example/package-lock.json
  tools/subgraph-example/scripts/create-gravatar.ts
  tools/subgraph-example/scripts/erc20-transfer.ts
  tools/subgraph-example/scripts/erc721-mint.ts
  tools/subgraph-example/scripts/index.ts
  tools/subgraph-example/scripts/manage-gravatar.ts
  tools/subgraph-example/scripts/update-gravatar.ts
  tools/subgraph-example/subgraph/networks.json
  tools/subgraph-example/subgraph/subgraph.yaml
  tools/subgraph-example/test/expected.json
  tools/subgraph-example/test/subgraph.ts
Labels: limechain

#770 Pad slot value on comparison
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/server/tests/acceptance/index.spec.ts
  packages/server/tests/acceptance/rpc.spec.ts
  packages/server/tests/helpers/prerequisite.ts
Labels: bug, limechain, P2

#780 Add subgraph GitHub workflow and update the Readme
  .github/workflows/subgraph.yml
  tools/README.md
  tools/subgraph-example/README.md
  tools/subgraph-example/configs/latest.json
  tools/subgraph-example/package-lock.json
  tools/subgraph-example/package.json
  tools/subgraph-example/test/subgraph.ts
Labels: enhancement

#767 Configmap fix env from change
  helm-chart/templates/configmap.yaml
  helm-chart/templates/deployment.yaml
  helm-chart/templates/secret.yaml
  helm-chart/templates/service.yaml
  helm-chart/value-test.yaml
  helm-chart/values.yaml
Labels: enhancement, P1, process

#785 Bump 0.15.0-snapshot
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: enhancement, P1, process

#786 Bump 0.14.0-rc1
  README.md
  docker-compose.yml
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: enhancement, P1, process

#789 Bump 0.14.0
  docker-compose.yml
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: enhancement, P1, process

#787 Add custom error message for better traceability for multiple asserts
  packages/server/tests/helpers/assertions.ts
  packages/server/tests/helpers/nodeCheck.ts
  packages/server/tests/integration/server.spec.ts
  tools/subgraph-example/README.md
Labels: enhancement
