Repository hiero-ledger/hiero-json-rpc-relay, pull requests merged in 2022-07, with the labels that each got.

#290 eth_call acceptance tests
  packages/server/tests/acceptance/rpc.spec.ts
Labels: enhancement, limechain, P2, process

#288 ChainId precheck
  README.md
  packages/relay/src/lib/errors.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/precheck.ts
  packages/relay/tests/lib/precheck.spec.ts
  packages/server/tests/acceptance/rpc.spec.ts
  packages/server/tests/clients/mirrorClient.ts
  packages/server/tests/clients/relayClient.ts
  packages/server/tests/helpers/assertions.ts
Labels: enhancement, limechain, P1

#278 Update feeHistory exchangeRate logic to use MirrorNode
  .env.example
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/errors.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/server/tests/acceptance/index.spec.ts
  packages/server/tests/acceptance/rpc.spec.ts
  packages/server/tests/clients/servicesClient.ts
  packages/server/tests/helpers/assertions.ts
  packages/server/tests/localAcceptance.env
Labels: enhancement, P1

#291 Add gas precheck to eth_sendRawTransaction
  packages/relay/src/lib/errors.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/precheck.ts
  packages/relay/tests/lib/precheck.spec.ts
  packages/server/tests/acceptance/rpc.spec.ts
Labels: enhancement, limechain, P2

#293 Add balance precheck to eth_sendRawtransaction
  packages/relay/src/lib/errors.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/precheck.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/precheck.spec.ts
  packages/server/tests/acceptance/rpc.spec.ts
  packages/server/tests/clients/relayClient.ts
  packages/server/tests/clients/servicesClient.ts
  packages/server/tests/helpers/assertions.ts
Labels: enhancement, limechain, P2

#297 Improve logging, metrics and error handling
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/precheck.ts
  packages/relay/src/lib/relay.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/server/tests/clients/relayClient.ts
Labels: enhancement, P3

#281 Implement eth_sendRawTransaction for large Ethereum TXs
  package-lock.json
  packages/relay/package.json
  packages/relay/src/lib/clients/sdkClient.ts
  packages/server/package.json
  packages/server/tests/acceptance/rpc.spec.ts
Labels: enhancement, limechain, P1

#299 Helm chart chain id fix
  helm-chart/templates/deployment.yaml
  helm-chart/templates/secret.yaml
  helm-chart/values.yaml
Labels: P1, process

#292 Add acceptance test support for eth_getLogs
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/server/src/server.ts
  packages/server/tests/acceptance/rpc.spec.ts
  packages/server/tests/contracts/Logs.json
  packages/server/tests/contracts/Logs.sol
Labels: enhancement, limechain, P2, process

#307 Bump 0.3.0-rc1
  .github/workflows/release-production.yml
  docker-compose.yml
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: P1, process

#304 Implement gasLimit Precheck
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/errors.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/precheck.ts
  packages/relay/tests/helpers.ts
  packages/relay/tests/lib/precheck.spec.ts
  packages/server/tests/acceptance/erc20.spec.ts
  packages/server/tests/acceptance/rpc.spec.ts
Labels: enhancement, limechain, P2

#318 Add lerna to dependency to support complete docker build and release
  package.json
Labels: bug, P2, process

#315 Fix schema mismatch for nums in eth_getTransactionReceipt response
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/model.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/server/tests/helpers/assertions.ts
  packages/server/tests/helpers/utils.ts
Labels: bug, P2

#314 Update eth_getLogs to utilize index across block transactions
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/server/tests/acceptance/rpc.spec.ts
Labels: bug, P1

#323 Add lerna to dependency to support complete docker build and release (0.3)
  package.json
Labels: bug, P2, process

#326 Bump 0.3.0-rc2
  docker-compose.yml
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: P1, process

#310 Add cache logic to capture static INVALID entity transaction failures
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: enhancement, limechain, P1

#320 Add backup logic to generate keys as part of the flow
  dapp-example/tests/support/bootstrap.js
Labels: enhancement, P3, dev tools

#330 Bump 0.3.0-rc3
  docker-compose.yml
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: enhancement, P1

#332 Align receipt with execution apis
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/model.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/server/tests/helpers/assertions.ts
Labels: bug, P2

#298 HTS acceptance tests
  packages/server/tests/acceptance/erc20.spec.ts
  packages/server/tests/clients/servicesClient.ts
Labels: enhancement, limechain

#317 Add support for optional data field on eth_call flow
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/eth.ts
  packages/server/tests/acceptance/rpc.spec.ts
  packages/server/tests/clients/servicesClient.ts
  packages/server/tests/contracts/Basic.json
  packages/server/tests/contracts/Basic.sol
Labels: enhancement, P1

#352 Bump 0.4.0-rc1
  docker-compose.yml
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: enhancement, P1

#341 Align transaction with ethereum execution apis
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/server/tests/helpers/assertions.ts
Labels: bug, limechain, P1

#343 Align log with execution apis
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/server/tests/acceptance/rpc.spec.ts
Labels: bug, limechain, P1

#351 Ensure acceptance tests run on previewnet/testnet
  README.md
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
  packages/server/tests/acceptance/erc20.spec.ts
  packages/server/tests/acceptance/rpc.spec.ts
  packages/server/tests/clients/relayClient.ts
  packages/server/tests/clients/servicesClient.ts
  packages/server/tests/helpers/assertions.ts
Labels: enhancement, P1, process

#350 Optimize parse transaction on prechecks
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/precheck.ts
  packages/relay/tests/lib/precheck.spec.ts
Labels: enhancement, limechain, P2

#357 Metamask window does not popup on DApp tests
  dapp-example/tests/e2e/index.spec.js
Labels: bug, limechain, P1, process, dev tools

#354 Add RPC API endpoint table
  README.md
  docs/rpc-api.md
Labels: documentation, enhancement, P3

#360 Add an OpenRPC Document
  README.md
  docs/openrpc.json
  package-lock.json
  package.json
  packages/server/package.json
  packages/server/src/server.ts
  packages/server/tests/integration/openrpc.spec.ts
Labels: documentation, enhancement, limechain, P2

#359 Automate hardhat-relay test
  .github/workflows/hardhat.yml
  package-lock.json
  packages/server/package.json
  packages/server/tests/acceptance/index.spec.ts
  packages/server/tests/helpers/prerequisite.ts
  packages/server/tests/localAcceptance.env
  tools/hardhat-example/.env.example
Labels: enhancement, limechain, P1, dev tools

#365 Add release acceptance tests tag support
  package.json
  packages/server/tests/acceptance/erc20.spec.ts
  packages/server/tests/acceptance/index.spec.ts
  packages/server/tests/acceptance/rpc.spec.ts
  packages/server/tests/clients/servicesClient.ts
Labels: enhancement, P2, process

#363 Align transaction with ethereum execution apis (0.4)
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/server/tests/helpers/assertions.ts
Labels: bug, P1

#364 Align log with execution apis (0.4)
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/server/tests/acceptance/rpc.spec.ts
Labels: bug, P1

#368 Bump 0.4.0 version
  docker-compose.yml
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: enhancement, P1, process

#370 Web3js <> relay compatibility
  .github/workflows/hardhat-compatibility.yml
  .github/workflows/web3js-compatibility.yml
  tools/web3js-example/.env.example
  tools/web3js-example/.gitignore
  tools/web3js-example/contract/Greeter.json
  tools/web3js-example/contract/Greeter.sol
  tools/web3js-example/package-lock.json
  tools/web3js-example/package.json
  tools/web3js-example/scripts/contractCall.js
  tools/web3js-example/scripts/contractViewCall.js
  tools/web3js-example/scripts/deployContract.js
  tools/web3js-example/scripts/showBalance.js
  tools/web3js-example/scripts/transferHbars.js
  tools/web3js-example/test/rpc.js
Labels: enhancement, limechain, P2, dev tools

#374 remove mirrorNode.ts and dependencies
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/mirrorNode.ts
  packages/relay/src/lib/model.ts
  packages/relay/src/lib/relay.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: enhancement, P3

#375 Support 'from' in 'eth_call'
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/server/tests/acceptance/erc20.spec.ts
Labels: bug, P1

#383 Support 'from' in 'eth_call' (0.4)
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/server/tests/acceptance/erc20.spec.ts
Labels: bug, P1

#384 Bump 0.4.1
  docker-compose.yml
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: enhancement, P1

#372 Ensure Schema compliance with execution-apis schema
  docs/openrpc.json
  package.json
  packages/relay/src/index.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/helpers.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/openrpc.spec.ts
  packages/server/package.json
  packages/server/tests/acceptance/rpc.spec.ts
  packages/server/tests/integration/openrpc.spec.ts
Labels: enhancement, limechain, P1

#378 Document the blockHash filter for eth_getLogs
  docs/openrpc.json
Labels: documentation, enhancement, P2

#379 Truffle <> relay compatibility
  .github/workflows/truffle-compatibility.yml
  tools/truffle-example/.env.example
  tools/truffle-example/.gitignore
  tools/truffle-example/contracts/Greeter.sol
  tools/truffle-example/migrations/1_deploy_greeter.js
  tools/truffle-example/package-lock.json
  tools/truffle-example/package.json
  tools/truffle-example/test/rpc.js
  tools/truffle-example/truffle-config.js
Labels: enhancement, limechain, P2, dev tools

#388 Improve error handling for eth_getLogs
  packages/relay/src/index.ts
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/relay/src/lib/errors/MirrorNodeClientError.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/server/src/server.ts
  packages/server/tests/acceptance/rpc.spec.ts
Labels: bug, P1

#393 Increase newman postman tests coverage
  .github/workflows/postman.yml
  packages/server/tests/postman.json
Labels: enhancement, P2, process

#390 Calls with bad data should return an error response
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: bug, limechain, P1
