Repository hiero-ledger/hiero-json-rpc-relay, pull requests merged in 2022-10, with the labels that each got.

#575 Add HBAR Rate Limit support
  .env.example
  .github/workflows/acceptance.yml
  README.md
  docs/hbar-limiting.md
  package.json
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/hbarlimiter/index.ts
  packages/server/src/koaJsonRpc/index.ts
  packages/server/src/koaJsonRpc/lib/RpcError.ts
  packages/server/tests/acceptance/hbarLimiter.spec.ts
  packages/server/tests/acceptance/rpc.spec.ts
  packages/server/tests/localAcceptance.env
Labels: enhancement, limechain, P1

#580 Improve Koa and KoaJsonRpc classes
  packages/server/src/koaJsonRpc/index.ts
  packages/server/src/server.ts
Labels: enhancement, limechain

#578 Add chart rate limit configuration support
  helm-chart/templates/configmap.yaml
  helm-chart/templates/deployment.yaml
  helm-chart/values.yaml
Labels: enhancement, P2

#584 Unit tests for HBAR Rate limit
  .github/workflows/acceptance.yml
  package.json
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/hbarlimiter/index.ts
  packages/relay/tests/lib/hbarLimiter.spec.ts
  packages/server/tests/acceptance/rateLimiter.spec.ts
  packages/server/tests/acceptance/rpc.spec.ts
Labels: enhancement, limechain, P2

#549 eth_getBalance search by blockNumberOrTag
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/server/tests/acceptance/rpc.spec.ts
Labels: enhancement, limechain, P2

#581 Fix constants. Set effectiveGasPrice to 0 if null
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: enhancement, limechain, P2

#587 Bump 0.10.0-snapshot
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: enhancement, P1

#588 Bump 0.9.0-rc1
  docker-compose.yml
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: enhancement, P1

#593 Add TransactionRecordQuery calls to capture failed transaction costs
  package-lock.json
  packages/relay/package.json
  packages/relay/src/lib/clients/sdkClient.ts
  packages/server/package.json
Labels: enhancement, P1

#596 Add TransactionRecordQuery calls to capture failed transaction costs (0.9)
  package-lock.json
  packages/relay/package.json
  packages/relay/src/lib/clients/sdkClient.ts
  packages/server/package.json
Labels: enhancement, P1

#597 Bump 0.9.0-rc2
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: enhancement, P1, process

#589 Remove Acceptance Tests and Dapp Test workaround
  .github/workflows/dapp.yml
  dapp-example/tests/support/bootstrap.js
  package-lock.json
  package.json
  packages/server/tests/acceptance/index.spec.ts
  packages/server/tests/helpers/prerequisite.ts
  packages/server/tests/helpers/prerequisiteDappTests.ts
  packages/server/tests/localAcceptance.env
  tools/hardhat-example/scripts/transferHbars.js
  tools/truffle-example/package-lock.json
Labels: enhancement, limechain

#603 Bump 0.9.0
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: enhancement, P1, process

#600 Handle empty hex bloom in eth_getTransactionReceipt
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: bug, limechain

#595 Add support for eth_maxPriorityFeePerGas
  docs/openrpc.json
  docs/rpc-api.md
  packages/relay/src/index.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/openrpc.spec.ts
  packages/server/src/koaJsonRpc/lib/methodConfiguration.ts
  packages/server/src/server.ts
  packages/server/tests/acceptance/rpc.spec.ts
  packages/server/tests/integration/server.spec.ts
Labels: enhancement, limechain, P2

#598 `eth_getCode` to return the redirect bytecode for HTS tokens
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/helpers.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
  packages/server/tests/acceptance/rpc.spec.ts
Labels: bug, limechain, P2

#607 Update subgraph example docs
  tools/subgraph-example/README.md
  tools/subgraph-example/docker-compose.yml
Labels: enhancement, limechain

#611 Add graph integration status
  tools/README.md
Labels: enhancement, limechain

#610 Handle null `gas_used` from contract results
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: bug, limechain

#604 Revert reason in eth_call
  packages/relay/src/formatters.ts
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/helpers.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/formatters.spec.ts
  packages/server/src/server.ts
  packages/server/tests/acceptance/rpc.spec.ts
  packages/server/tests/contracts/Reverter.json
  packages/server/tests/contracts/Reverter.sol
Labels: bug, limechain

#613 Improve Rate Limiter Tiers for Development Tools
  docs/rate-limiting.md
  packages/server/tests/localAcceptance.env
  tools/README.md
Labels: enhancement, limechain, P2

#616 Optimize `eth_getLogs()`
  packages/relay/src/lib/eth.ts
  packages/relay/tests/helpers.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: enhancement, limechain, P2

#442 Bump lerna and eth waffle packages
  package-lock.json
  package.json
Labels: P3, process

#617 Bump local node acceptance test images for 0.31.A
  packages/server/tests/acceptance/index.spec.ts
  packages/server/tests/helpers/prerequisite.ts
Labels: enhancement, P2

#622 Add logging and metrics to rate limit logic
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/hbarlimiter/index.ts
  packages/relay/tests/lib/hbarLimiter.spec.ts
  packages/server/src/koaJsonRpc/index.ts
  packages/server/src/koaJsonRpc/lib/RpcError.ts
  packages/server/src/ratelimit/index.ts
  packages/server/src/server.ts
Labels: enhancement, P2

#629 Update eth_getCode to handle call to iHTS address
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: enhancement, P1, dev tools

#637 Fix rate limit not reseting
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/server/src/koaJsonRpc/index.ts
  packages/server/tests/acceptance/rateLimiter.spec.ts
Labels: bug, limechain, P1

#636 Bump 0.11.0-snapshot
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: enhancement, P1, process

#635 Bump 0.10.0-rc1
  docker-compose.yml
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/server/package.json
  packages/server/src/koaJsonRpc/index.ts
  packages/server/tests/acceptance/rateLimiter.spec.ts
Labels: enhancement, P1, process

#640 Add missing python to node alpine base image
  Dockerfile
Labels: bug, P1, process

#643 Add missing python to node alpine base image (0.10)
  Dockerfile
Labels: enhancement, P1, process

#646 Bump 0.10.0-rc2
  docker-compose.yml
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: enhancement, P1, process

#648 Fix transaction index param
  packages/relay/src/index.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/openrpc.spec.ts
Labels: bug, limechain

#652 Bump 0.10.0
  docker-compose.yml
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: enhancement, P1, process

#649 Dev tools and Dapp example tests Fix
  .github/workflows/dapp.yml
  .github/workflows/dev-tool-workflow.yml
  dapp-example/package-lock.json
  dapp-example/package.json
  dapp-example/tests/support/bootstrap.js
  package-lock.json
  package.json
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/server/package.json
  packages/server/tests/acceptance/index.spec.ts
  packages/server/tests/acceptance/rpc.spec.ts
  packages/server/tests/helpers/nodeCheck.ts
  packages/server/tests/helpers/prerequisite.ts
  tools/hardhat-example/package-lock.json
  tools/hardhat-example/package.json
  tools/truffle-example/package-lock.json
  tools/truffle-example/package.json
Labels: bug, limechain, P1

#650 Pull evm_address for contract logs
  packages/relay/src/lib/eth.ts
  packages/relay/tests/helpers.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/openrpc.spec.ts
Labels: enhancement, P1

#655 Add env variable to control rate limiting
  .env.example
  README.md
  docs/rate-limiting.md
  helm-chart/templates/configmap.yaml
  helm-chart/templates/deployment.yaml
  helm-chart/values.yaml
  packages/server/src/ratelimit/index.ts
  packages/server/tests/localAcceptance.env
Labels: enhancement, P2, process
