Repository hiero-ledger/hiero-json-rpc-relay, pull requests merged in 2023-11, with the labels that each got.

#1867 Fix Poller in docker build
  packages/relay/src/lib/poller.ts
Labels: limechain

#1873 upgrading chart-testing-action to 2.6.1
  .github/workflows/charts.yml
Labels: bug, dependencies

#1864 [Snyk] Upgrade pnpm from 8.7.6 to 8.8.0
  package-lock.json
  packages/ws-server/package.json
Labels: dependencies

#1872 Adding support for Batch Requests.
  docs/configuration.md
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/server/src/koaJsonRpc/index.ts
  packages/server/src/koaJsonRpc/lib/RpcError.ts
  packages/server/src/koaJsonRpc/lib/RpcInvalidError.ts
  packages/server/src/koaJsonRpc/lib/isJson.ts
  packages/server/src/server.ts
  packages/server/tests/integration/server.spec.ts
  packages/server/tests/postman.json
Labels: enhancement, P2

#1886 Chart Install GHA WF Fix
  charts/hedera-json-rpc-relay/postman.json
Labels: bug, P1

#1888 Update Packages
  package-lock.json
  package.json
  packages/relay/package.json
  packages/server/package.json
  packages/server/tests/acceptance/index.spec.ts
  packages/server/tests/helpers/prerequisite.ts
  packages/ws-server/package.json
Labels: limechain

#1918 Acceptance Tests TokenCreate Fix and Reliability Improvements
  packages/server/tests/acceptance/htsPrecompile/tokenCreate.spec.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
  packages/server/tests/acceptance/ws/subscribe.spec.ts
Labels: bug

#1920 Bump Hedera-Local version
  package-lock.json
  package.json
  packages/server/tests/acceptance/index.spec.ts
  packages/server/tests/helpers/prerequisite.ts
  tools/hardhat-example/package-lock.json
  tools/hardhat-example/package.json
  tools/subgraph-example/package-lock.json
  tools/subgraph-example/package.json
Labels: dependencies

#1900 Upgrade @hashgraph/sdk from 2.32.0 to 2.37.0
  package-lock.json
  packages/relay/package.json
Labels: bug

#1911 Productization of Environment optimization for retries against mirror node calls.
  docs/configuration.md
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/constants.ts
  packages/server/tests/acceptance/htsPrecompile/tokenCreate.spec.ts
Labels: enhancement

#1927 [Snyk] Upgrade @mui/material from 5.14.14 to 5.14.17
  dapp-example/package-lock.json
  dapp-example/package.json
Labels: dependencies

#1936 HotFix to allow Metamask to unblock Send Token Flow
  packages/server/src/server.ts
  packages/server/tests/acceptance/htsPrecompile/tokenCreate.spec.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
  packages/server/tests/acceptance/ws/subscribe.spec.ts
Labels: bug

#1933 [Snyk] Upgrade lerna from 7.3.0 to 7.4.2
  package-lock.json
  package.json
Labels: dependencies

#1938 [Snyk] Upgrade pnpm from 8.9.2 to 8.10.2
  package-lock.json
  packages/ws-server/package.json
Labels: dependencies

#1944 [Snyk] Upgrade web3 from 4.2.0 to 4.2.2
  tools/web3js-example/package-lock.json
  tools/web3js-example/package.json
Labels: dependencies
