Repository hiero-ledger/hiero-json-rpc-relay, pull requests merged in 2023-01, with the labels that each got.

#663 651 add eth methods validations
  .gitignore
  package-lock.json
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/openrpc.spec.ts
  packages/server/package.json
  packages/server/src/koaJsonRpc/index.ts
  packages/server/src/rateLimit/index.ts
  packages/server/src/server.ts
  packages/server/src/validator/constants.ts
  packages/server/src/validator/index.ts
  packages/server/src/validator/methods.ts
  packages/server/src/validator/objectTypes.ts
  packages/server/src/validator/types.ts
  packages/server/src/validator/utils.ts
  packages/server/tests/acceptance/erc20.spec.ts
  packages/server/tests/acceptance/index.spec.ts
  packages/server/tests/acceptance/rateLimiter.spec.ts
  packages/server/tests/acceptance/rpc.spec.ts
  packages/server/tests/clients/relayClient.ts
  packages/server/tests/integration/server.spec.ts
  packages/server/tests/integration/test.env
  packages/server/tests/integration/validator.spec.ts
  packages/server/tests/postman.json
Labels: enhancement

#797 Bump 0.16.0 snapshot
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: enhancement, P1, process

#798 Bump 0.15.0-rc1
  .gitignore
  README.md
  docker-compose.yml
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/openrpc.spec.ts
  packages/server/package.json
  packages/server/src/koaJsonRpc/index.ts
  packages/server/src/rateLimit/index.ts
  packages/server/src/server.ts
  packages/server/src/validator/constants.ts
  packages/server/src/validator/index.ts
  packages/server/src/validator/methods.ts
  packages/server/src/validator/objectTypes.ts
  packages/server/src/validator/types.ts
  packages/server/src/validator/utils.ts
  packages/server/tests/acceptance/erc20.spec.ts
  packages/server/tests/acceptance/index.spec.ts
  packages/server/tests/acceptance/rateLimiter.spec.ts
  packages/server/tests/acceptance/rpc.spec.ts
  packages/server/tests/clients/relayClient.ts
  packages/server/tests/integration/server.spec.ts
  packages/server/tests/integration/test.env
  packages/server/tests/integration/validator.spec.ts
  packages/server/tests/postman.json
Labels: enhancement, P1, process

#807 Bump 0.15.0
  docker-compose.yml
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: enhancement, P1, process

#812 ContractCallQuery retry logic
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/errors/SDKClientError.ts
  packages/relay/tests/lib/sdkClient.spec.ts
  packages/relay/tests/test.env
Labels: bug

#819 Bump 0.16.0-rc1
  README.md
  docker-compose.yml
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: enhancement, P1, process

#818 Bump 0.17.0-snapshot
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: enhancement, P1, process

#820 Fix cache on getBalance
  packages/relay/src/lib/eth.ts
Labels: bug, limechain, P1

#817 Expand `eth_call` validation to support blockParam object
  package-lock.json
  package.json
  packages/relay/src/lib/eth.ts
  packages/server/package.json
  packages/server/src/validator/constants.ts
  packages/server/src/validator/methods.ts
  packages/server/src/validator/objectTypes.ts
  packages/server/src/validator/types.ts
  packages/server/tests/acceptance/erc20.spec.ts
  packages/server/tests/acceptance/index.spec.ts
  packages/server/tests/acceptance/rpc.spec.ts
  packages/server/tests/helpers/prerequisite.ts
  packages/server/tests/integration/server.spec.ts
Labels: bug, limechain, P1

#792 Configurable function input size
  .env.example
  README.md
  helm-chart/templates/configmap.yaml
  helm-chart/value-test.yaml
  helm-chart/values.yaml
  packages/server/src/server.ts
  packages/server/tests/localAcceptance.env
Labels: enhancement

#823 Expand `eth_call` validation to support blockParam object (#817)
  package-lock.json
  package.json
  packages/relay/src/lib/eth.ts
  packages/server/package.json
  packages/server/src/validator/constants.ts
  packages/server/src/validator/methods.ts
  packages/server/src/validator/objectTypes.ts
  packages/server/src/validator/types.ts
  packages/server/tests/acceptance/erc20.spec.ts
  packages/server/tests/acceptance/index.spec.ts
  packages/server/tests/acceptance/rpc.spec.ts
  packages/server/tests/helpers/prerequisite.ts
  packages/server/tests/integration/server.spec.ts
Labels: bug, limechain, P1

#824 Bump acceptance test node images
  packages/server/tests/acceptance/index.spec.ts
  packages/server/tests/helpers/prerequisite.ts
Labels: enhancement

#825 Bump 0.16.0-rc2
  docker-compose.yml
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: enhancement, P1, process

#842 Remove unnecessary call when details not requested
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: bug

#832 eth_feeHistory wrongly returns error
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: bug

#846 Fix validations for estimateGas
  packages/server/src/validator/objectTypes.ts
  packages/server/tests/acceptance/rpc.spec.ts
Labels: enhancement, P1, dev tools

#848 Bump 0-16-0-rc3
  docker-compose.yml
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: enhancement, P1, process

#849 Add nullable check to estimateGas validation
  packages/relay/src/lib/eth.ts
  packages/server/src/validator/objectTypes.ts
  packages/server/src/validator/utils.ts
  packages/server/tests/acceptance/rpc.spec.ts
  packages/server/tests/integration/server.spec.ts
  packages/server/tests/integration/validator.spec.ts
Labels: bug, P1, dev tools

#851 Bump 0.16.0-rc4
  docker-compose.yml
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: enhancement, P1, process

#804 Optimize acceptance test CI
  .github/workflows/acceptance.yml
  package.json
  packages/server/tests/acceptance/rpc.spec.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
  packages/server/tests/acceptance/rpc_batch3.spec.ts
  packages/server/tests/clients/servicesClient.ts
Labels: enhancement, limechain, P3, process

#854 Return array of numbers in `eth_feeHistory` response
  docs/openrpc.json
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/server/tests/helpers/assertions.ts
Labels: bug

#857 Bump 0.18.0 snapshot
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: enhancement, P1, process

#856 ga release for 0.16.0
  docker-compose.yml
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: enhancement, P1, process

#844 Fix eth_estimateGas for hollow account creation
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/openrpc.spec.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
Labels: enhancement, limechain, P1

#860 Fix eth_estimateGas for hollow account creation (#844)
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/openrpc.spec.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
Labels: enhancement, limechain, P1

#858 Bump version 0.17.0-rc1
  README.md
  docker-compose.yml
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: enhancement, P1, process

#763 Refactor eth_call to use mirror node
  .env.example
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/relay/src/lib/errors/MirrorNodeClientError.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/relay.ts
  packages/relay/tests/helpers.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
  packages/relay/tests/lib/openrpc.spec.ts
  packages/relay/tests/test.env
  packages/server/src/validator/constants.ts
  packages/server/tests/acceptance/erc20.spec.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
  packages/server/tests/acceptance/rpc_batch3.spec.ts
  packages/server/tests/contracts/Caller.json
  packages/server/tests/contracts/Caller.sol
  packages/server/tests/helpers/utils.ts
  packages/server/tests/localAcceptance.env
Labels: enhancement, limechain

#863 Refactor eth_call to use mirror node (#763)
  .env.example
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/relay/src/lib/errors/MirrorNodeClientError.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/relay.ts
  packages/relay/tests/helpers.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
  packages/relay/tests/lib/openrpc.spec.ts
  packages/relay/tests/test.env
  packages/server/src/validator/constants.ts
  packages/server/tests/acceptance/erc20.spec.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
  packages/server/tests/acceptance/rpc_batch3.spec.ts
  packages/server/tests/contracts/Caller.json
  packages/server/tests/contracts/Caller.sol
  packages/server/tests/helpers/utils.ts
  packages/server/tests/localAcceptance.env
Labels: P1, process

#864 Bump 0.17.0-rc2
  docker-compose.yml
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: enhancement, P1, process
