Repository hiero-ledger/hiero-json-rpc-relay, pull requests merged in 2023-03, with the labels that each got.

#964 993-Request-ID-is-missing-from-some-mirror-node-relay-logs. This was…
  packages/relay/src/lib/eth.ts
Labels: enhancement

#899 Improvements to K6 Load and Performance Tests
  k6/.envexample
  k6/ENV.csh
  k6/README.md
  k6/package.json
  k6/src/lib/common.js
  k6/src/prepare/contracts/Greeter.json
  k6/src/prepare/prep.js
  k6/src/scenarios/apis.js
  k6/src/scenarios/test/bootstrapEnvParameters.js
  k6/src/scenarios/test/common.js
  k6/src/scenarios/test/eth_call.js
  k6/src/scenarios/test/eth_coinbase.js
  k6/src/scenarios/test/eth_feeHistory.js
  k6/src/scenarios/test/eth_getBlockByHash.js
  k6/src/scenarios/test/eth_getBlockTransactionCountByHash.js
  k6/src/scenarios/test/eth_getBlockTransactionCountByNumber.js
  k6/src/scenarios/test/eth_getCode.js
  k6/src/scenarios/test/eth_getStorageAt.js
  k6/src/scenarios/test/eth_getTransactionByBlockNumberAndIndex.js
  k6/src/scenarios/test/eth_getTransactionCount.js
  k6/src/scenarios/test/eth_getWork.js
  k6/src/scenarios/test/eth_protocolVersion.js
  k6/src/scenarios/test/eth_sendRawTransaction.js
  k6/src/scenarios/test/eth_sendTransaction.js
  k6/src/scenarios/test/eth_sign.js
  k6/src/scenarios/test/eth_signTransaction.js
  k6/src/scenarios/test/eth_submitHashrate.js
Labels: enhancement, P2, process

#939 Add a gas/s metric for gas consuming endpoints
  packages/relay/src/lib/clients/sdkClient.ts
Labels: enhancement, P2

#961 Add subscription handling class
  .env.example
  helm-chart/templates/configmap.yaml
  helm-chart/value-test.yaml
  helm-chart/values.yaml
  packages/relay/src/index.ts
  packages/relay/src/lib/relay.ts
  packages/relay/src/lib/subscriptionController.ts
  packages/server/tests/localAcceptance.env
Labels: enhancement, eth_subscribe

#962 Add Mirror node poller
  .env.example
  packages/relay/src/lib/poller.ts
  packages/relay/src/lib/relay.ts
  packages/relay/src/lib/subscriptionController.ts
  packages/ws-server/src/webSocketServer.ts
Labels: enhancement, eth_subscribe

#896 Design Document for `eth_subscribe` and `eth_unsubscribe`
  docs/design/eth-subscribe.md
Labels: enhancement, limechain, P1

#959 Update rate limiting and API docs
  docs/rate-limiting.md
  docs/rpc-api.md
Labels: documentation, enhancement, P3

#958 Add cache to Mirror Node Client getContractResult method.
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/constants.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
  packages/server/tests/integration/server.spec.ts
Labels: enhancement, P2

#953 Improve cache log and server error log
  packages/relay/src/lib/eth.ts
  packages/server/src/server.ts
Labels: enhancement, P3

#956 Add Configurations documents
  README.md
  docs/configuration.md
Labels: documentation, P2

#978 927 - Added socket connection limits.
  .env.example
  docs/configuration.md
  packages/server/tests/acceptance/index.spec.ts
  packages/server/tests/acceptance/ws/subscribe.spec.ts
  packages/server/tests/localAcceptance.env
  packages/ws-server/src/webSocketServer.ts
Labels: enhancement, eth_subscribe

#994 Check for Valid To and From Addresses on eth_call
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/openrpc.spec.ts
  packages/server/tests/acceptance/rpc_batch3.spec.ts
Labels: enhancement, P2

#1000 bump 0.21.0-SNAPSHOT
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: P1, process

#1002 Bump 0.20.0-rc1
  README.md
  docker-compose.yml
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: enhancement, P1, process

#998 941 add unit tests for the poller class
  packages/relay/src/lib/poller.ts
  packages/relay/tests/lib/poller.spec.ts
Labels: enhancement, P2, eth_subscribe

#1007 Invalid Json Crashes WS-Server Fix
  packages/server/tests/acceptance/ws/subscribe.spec.ts
  packages/ws-server/src/webSocketServer.ts
Labels: eth_subscribe

#1013 GA release 0.20.0
  docker-compose.yml
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: P1, process

#989 Acceptance Tests for eth_subscribe, connect, disconnect, subscribe, unsubscribe and multiple subscriptions at once
  packages/server/tests/acceptance/ws/subscribe.spec.ts
Labels: eth_subscribe

#997 Fix `eth_getBalance` returning wrong balance
  package-lock.json
  package.json
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/server/tests/acceptance/index.spec.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
  packages/server/tests/helpers/prerequisite.ts
Labels: bug, P1

#1016 Enable `eth_getStorageAt` to return older state
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
  packages/server/tests/acceptance/index.spec.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
  packages/server/tests/helpers/prerequisite.ts
Labels: enhancement, limechain, P1

#1005 Switch eth_call to Mirror Node
  .env.example
  docs/configuration.md
  helm-chart/templates/configmap.yaml
  helm-chart/value-test.yaml
  helm-chart/values.yaml
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/errors/MirrorNodeClientError.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/openrpc.spec.ts
  packages/server/tests/acceptance/erc20.spec.ts
  packages/server/tests/acceptance/index.spec.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
  packages/server/tests/acceptance/rpc_batch3.spec.ts
  packages/server/tests/contracts/HederaTokenServiceImpl.json
  packages/server/tests/contracts/HederaTokenServiceImpl.sol
  packages/server/tests/helpers/prerequisite.ts
  packages/server/tests/integration/server.spec.ts
  packages/server/tests/localAcceptance.env
  tools/hardhat-example/test/rpc.js
  tools/truffle-example/test/rpc.js
  tools/web3js-example/test/rpc.js
Labels: enhancement

#1019 Cherry Pick Switch eth_call to Mirror-node
  .env.example
  docs/configuration.md
  helm-chart/templates/configmap.yaml
  helm-chart/value-test.yaml
  helm-chart/values.yaml
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/errors/MirrorNodeClientError.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/openrpc.spec.ts
  packages/server/tests/acceptance/erc20.spec.ts
  packages/server/tests/acceptance/index.spec.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
  packages/server/tests/acceptance/rpc_batch3.spec.ts
  packages/server/tests/contracts/HederaTokenServiceImpl.json
  packages/server/tests/contracts/HederaTokenServiceImpl.sol
  packages/server/tests/helpers/prerequisite.ts
  packages/server/tests/integration/server.spec.ts
  packages/server/tests/localAcceptance.env
  tools/hardhat-example/test/rpc.js
  tools/truffle-example/test/rpc.js
  tools/web3js-example/test/rpc.js
Labels: enhancement, P1
