Repository hiero-ledger/hiero-json-rpc-relay, pull requests merged in 2023-09, with the labels that each got.

#1696 Fix `eth_getТransactionByHash` does not return accesslist and yparity for 1559 and 2930 transactions
  docs/openrpc.json
  packages/relay/src/formatters.ts
  packages/relay/src/lib/model.ts
  packages/relay/tests/assertions.ts
  packages/relay/tests/helpers.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/formatters.spec.ts
Labels: enhancement, P2

#1695 Automatically formatting and cleaning code on commit
  .eslintrc.js
  .husky/pre-commit
  package-lock.json
  package.json
Labels: enhancement, P3

#1699 Enable shared cache in Filter API
  docs/configuration.md
  package-lock.json
  package.json
  packages/relay/src/formatters.ts
  packages/relay/src/lib/model.ts
  packages/relay/src/lib/services/ethService/ethFilterService/index.ts
  packages/relay/tests/assertions.ts
  packages/relay/tests/helpers.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/formatters.spec.ts
  packages/relay/tests/lib/services/eth/filter.spec.ts
  packages/server/tests/localAcceptance.env
Labels: enhancement, limechain, P1

#1713 Add metrics to CacheService
  packages/relay/src/lib/clients/cache/localLRUCache.ts
  packages/relay/src/lib/services/cacheService/cacheService.ts
Labels: enhancement, P2

#1718 [Snyk] Upgrade @mui/material from 5.14.4 to 5.14.5
  dapp-example/package-lock.json
  dapp-example/package.json
Labels: P2, dependencies

#1720 Applied test fixes.
  packages/server/tests/acceptance/erc20.spec.ts
  packages/server/tests/acceptance/index.spec.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
Labels: bug, P3

#1703 Acceptance tests for CacheService
  .github/workflows/acceptance.yml
  package-lock.json
  package.json
  packages/relay/src/lib/clients/cache/redisCache.ts
  packages/server/tests/acceptance/cacheService.spec.ts
  packages/server/tests/acceptance/index.spec.ts
Labels: enhancement, limechain, P2

#1727 Environment variable fixes.
  packages/server/tests/acceptance/cacheService.spec.ts
  packages/server/tests/acceptance/index.spec.ts
Labels: bug

#1728 Environment variable fixes.
  packages/server/tests/acceptance/cacheService.spec.ts
  packages/server/tests/acceptance/index.spec.ts
Labels: bug

#1731 [Snyk] Upgrade web3 from 4.1.0 to 4.1.1
  tools/web3js-example/package-lock.json
  tools/web3js-example/package.json
Labels: P2, dependencies

#1621 Script executing execution api tests
  .github/workflows/acceptance-public.yml
  .github/workflows/acceptance.yml
  package-lock.json
  package.json
  packages/server/package.json
  packages/server/tests/acceptance/conformityTests.spec.ts
Labels: enhancement, P2

#1726 Return evm_address in eth_getTransactionByHash and eth_getTransactionReceipt
  package-lock.json
  packages/relay/src/lib/clients/cache/redisCache.ts
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/eth.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
  packages/server/tests/clients/servicesClient.ts
  packages/server/tests/helpers/assertions.ts
  packages/server/types.d.ts
Labels: bug, limechain, P1

#1709 Add Documentation for Debug endpoint
  docs/design/debug-api.md
Labels: documentation, P1

#1740 Fix: eth_estimateGas Errors when providing `gas` field
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: bug, P1

#1735 Fixed Null exception for transaction receipts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: bug, P2

#1729 Usage of Shared Cache for Synthetic transaction receipts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/services/cacheService/cacheService.ts
  packages/relay/tests/lib/ethGetBlockBy.spec.ts
  packages/relay/tests/lib/services/cacheService/cacheService.spec.ts
Labels: enhancement, P2

#1721 Set the mirror-image-tag to 0.88.0 from main
  packages/server/tests/acceptance/index.spec.ts
Labels: P1, process

#1746 Reduce Accepted Error codes from `MirrorNodeClient.ts`
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
Labels: enhancement, P2

#1744 TheGraph environment variables recommended values for HashIO Relay
  tools/subgraph-example/README.md
  tools/subgraph-example/docker-compose.yml
Labels: enhancement, P2

#1742 [Snyk] Upgrade redis from 4.6.7 to 4.6.8
  package-lock.json
  package.json
Labels: dependencies

#1756 Fix Flaky Subgraph Acceptance Test - Adding a sleep to wait for the subgraph to index before running tests
  .github/workflows/subgraph.yml
Labels: bug, P1

#1637 Fix Wrong Intrinsic gas cost in `eth_sendRawTransaction` precheck calculation
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/precheck.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/precheck.spec.ts
  packages/server/tests/helpers/prerequisite.ts
  tools/subgraph-example/hardhat.config.ts
  tools/subgraph-example/package-lock.json
  tools/subgraph-example/package.json
  tools/subgraph-example/scripts/erc20-transfer.ts
  tools/subgraph-example/scripts/erc721-mint.ts
  tools/subgraph-example/scripts/manage-gravatar.ts
  tools/subgraph-example/test/expected.json
Labels: bug

#1743 Add actual Gas Price to synthetic transaction receipts
  package-lock.json
  package.json
  packages/relay/src/formatters.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/assertions.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/openrpc.spec.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
  packages/server/tests/helpers/assertions.ts
  packages/server/tests/localAcceptance.env
Labels: enhancement, limechain, P1
