Repository hiero-ledger/hiero-json-rpc-relay, pull requests merged in 2023-10, with the labels that each got.

#1758 Add basic positive tests for contract creation with transactions of t…
  packages/server/tests/acceptance/rpc_batch1.spec.ts
Labels: bug, limechain, P3

#1761 Stop treating CONTRACT_REVERT as ERROR
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/eth.ts
  packages/server/src/koaJsonRpc/index.ts
  packages/server/src/server.ts
  packages/server/tests/acceptance/rpc_batch3.spec.ts
  packages/server/tests/clients/relayClient.ts
Labels: enhancement, P1

#1767 Adding Example project with solidity-coverage lib
  tools/solidity-coverage-example/.gitignore
  tools/solidity-coverage-example/.solcover.js
  tools/solidity-coverage-example/README.md
  tools/solidity-coverage-example/assets/console.png
  tools/solidity-coverage-example/assets/contracts.png
  tools/solidity-coverage-example/assets/lock.png
  tools/solidity-coverage-example/contracts/HederaResponseCodes.sol
  tools/solidity-coverage-example/contracts/HederaTokenService.sol
  tools/solidity-coverage-example/contracts/IHederaTokenService.sol
  tools/solidity-coverage-example/contracts/IPrngSystemContract.sol
  tools/solidity-coverage-example/contracts/Lock.sol
  tools/solidity-coverage-example/contracts/PrngSystemContract.sol
  tools/solidity-coverage-example/contracts/TokenSend.sol
  tools/solidity-coverage-example/hardhat.config.ts
  tools/solidity-coverage-example/package-lock.json
  tools/solidity-coverage-example/package.json
  tools/solidity-coverage-example/scripts/deploy.ts
  tools/solidity-coverage-example/test/Lock.ts
  tools/solidity-coverage-example/test/PrngSystemContract.ts
  tools/solidity-coverage-example/test/TokenSend.ts
  tools/solidity-coverage-example/tsconfig.json
Labels: enhancement, limechain, dev tools

#1781 Bump mirror and node container images.
  packages/server/tests/acceptance/index.spec.ts
Labels: enhancement

#1776 1445 duplicate request id in log
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/services/ethService/ethCommonService/index.ts
  packages/server/src/rateLimit/index.ts
  tools/solidity-coverage-example/.solcover.js
Labels: bug, limechain

#1788 Productize ETH_POPULATE_SYNTHETIC_CONTRACT_RESULTS = true
  docs/configuration.md
  packages/relay/src/lib/eth.ts
Labels: enhancement, P2

#1797 Fix `withdrawalsRoot`
  docs/openrpc.json
  packages/relay/src/lib/model.ts
Labels: bug, P2

#1796 Broke out the WS_RELAY_URL to support other environments than dev.
  packages/server/tests/acceptance/rpc_batch3.spec.ts
  packages/server/tests/acceptance/ws/subscribe.spec.ts
  packages/server/tests/localAcceptance.env
Labels: enhancement

#1774 Add more tests and refine Intrinsic gas cost calculation
  packages/relay/src/lib/precheck.ts
  packages/relay/tests/lib/precheck.spec.ts
Labels: limechain

#1745 Add `debug_traceTransaction` endpoint
  charts/hedera-json-rpc-relay/templates/configmap.yaml
  charts/hedera-json-rpc-relay/value-test.yaml
  charts/hedera-json-rpc-relay/values.yaml
  docs/configuration.md
  packages/relay/src/index.ts
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/services/debugService/IDebugService.ts
  packages/relay/src/lib/services/debugService/index.ts
  packages/relay/src/lib/services/ethService/ethCommonService/ICommonService.ts
  packages/relay/src/lib/services/ethService/ethCommonService/index.ts
  packages/relay/src/lib/services/ethService/ethFilterService/index.ts
  packages/relay/tests/lib/services/debugService/debug.spec.ts
  packages/relay/tests/test.env
  packages/server/src/koaJsonRpc/lib/methodConfiguration.ts
  packages/server/src/server.ts
  packages/server/src/validator/constants.ts
  packages/server/src/validator/methods.ts
  packages/server/src/validator/types.ts
  packages/server/tests/helpers/constants.ts
  packages/server/tests/localAcceptance.env
Labels: enhancement, limechain

#1812 [Snyk] Upgrade web3 from 4.1.1 to 4.1.2
  tools/web3js-example/package-lock.json
  tools/web3js-example/package.json
Labels: dependencies

#1805 returning synthetic transaction when fetching it using eth_getTransac…
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: enhancement, P2

#1816 Cancel in progress action runs
  .github/workflows/acceptance.yml
  .github/workflows/charts.yml
  .github/workflows/dapp.yml
  .github/workflows/dev-tool-test.yml
  .github/workflows/postman.yml
  .github/workflows/subgraph.yml
  .github/workflows/test.yml
Labels: enhancement, P2, process

#1813 Update relay transaction size limit response to look more like the geth response
  docs/configuration.md
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/precheck.ts
  packages/relay/tests/lib/precheck.spec.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
  packages/server/tests/localAcceptance.env
Labels: enhancement, P2

#1814 Add acceptance tests for debug_traceTransaction endpoint
  docs/design/debug-api.md
  package-lock.json
  package.json
  packages/server/tests/acceptance/rpc_batch3.spec.ts
  packages/server/tests/helpers/assertions.ts
Labels: enhancement, P2, process

#1836 Fix timestamp from hex to decimal when querying the mirror node
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: bug, P1

#1834 Foundry Forge Create Contract Fix
  docs/openrpc.json
  packages/relay/src/lib/model.ts
  packages/relay/tests/assertions.ts
  packages/relay/tests/lib/formatters.spec.ts
Labels: bug, P1

#1840 Upgrading @hashgraph/sdk to 2.36.0 across all packages.
  dapp-example/package-lock.json
  dapp-example/package.json
  docs/examples/package.json
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: P1, dependencies

#1841 Acceptance Tests: Upgrading Network node to version '0.42.6' and mirror-node to '0.90.0'
  packages/server/tests/acceptance/index.spec.ts
Labels: dependencies

#1851 Fix tests
  dapp-example/package-lock.json
  dapp-example/package.json
  docs/examples/package.json
  package-lock.json
  packages/relay/package.json
  packages/relay/src/lib/services/debugService/index.ts
  packages/server/package.json
  packages/ws-server/package.json
Labels: bug

#1852 Cherry pick #1845
  dapp-example/package-lock.json
  dapp-example/package.json
  docs/examples/package.json
  package-lock.json
  packages/relay/package.json
  packages/relay/src/lib/services/debugService/index.ts
  packages/server/package.json
  packages/server/tests/acceptance/rpc_batch1.spec.ts
  packages/ws-server/package.json
Labels: P1, process

#1847 Prevent tests with `.only` in CI
  .mocharc.js
Labels: enhancement, process

#1844 [Snyk] Security upgrade node from 18.17-bullseye-slim to 18.18.2-bullseye-slim
  Dockerfile
Labels: P1, process
