Repository hiero-ledger/hiero-json-rpc-relay, pull requests merged in 2023-12, with the labels that each got.

#1946 eth_estimateGas Fixed for MetaMask issue #1935
  packages/server/src/server.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
Labels: bug, P1

#1941 Improve logs message when falling back to consensus node due to unsupported calls
  packages/relay/src/lib/eth.ts
Labels: enhancement

#1947 [Snyk] Upgrade @graphprotocol/graph-cli from 0.60.0 to 0.61.0
  tools/subgraph-example/subgraph/package.json
Labels: dependencies

#1952 [Snyk] Upgrade pnpm from 8.10.3 to 8.10.4
  package-lock.json
  packages/ws-server/package.json
Labels: P2, dependencies

#1924 Removing cache for getBalance in dev mode and 'blockNumberOrTagOrHash' is explicit
  packages/relay/package.json
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/services/ethService/ethCommonService/index.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: bug

#1925 Refactor ETH test spec
  packages/relay/package.json
  packages/relay/tests/assertions.ts
  packages/relay/tests/helpers.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/eth/eth-config.ts
  packages/relay/tests/lib/eth/eth-helpers.ts
  packages/relay/tests/lib/eth/eth_call.spec.ts
  packages/relay/tests/lib/eth/eth_common.spec.ts
  packages/relay/tests/lib/eth/eth_estimateGas.spec.ts
  packages/relay/tests/lib/eth/eth_feeHistory.spec.ts
  packages/relay/tests/lib/eth/eth_gasPrice.spec.ts
  packages/relay/tests/lib/eth/eth_getBalance.spec.ts
  packages/relay/tests/lib/eth/eth_getBlockByHash.spec.ts
  packages/relay/tests/lib/eth/eth_getBlockByNumber.spec.ts
  packages/relay/tests/lib/eth/eth_getBlockTransactionCountByHash.spec.ts
  packages/relay/tests/lib/eth/eth_getBlockTransactionCountByNumber.spec.ts
  packages/relay/tests/lib/eth/eth_getCode.spec.ts
  packages/relay/tests/lib/eth/eth_getLogs.spec.ts
  packages/relay/tests/lib/eth/eth_getStorageAt.spec.ts
  packages/relay/tests/lib/eth/eth_getTransactionByBlockHashAndIndex.spec.ts
  packages/relay/tests/lib/eth/eth_getTransactionByBlockNumberAndIndex.spec.ts
  packages/relay/tests/lib/eth/eth_getTransactionByHash.spec.ts
  packages/relay/tests/lib/eth/eth_getTransactionCount.spec.ts
  packages/relay/tests/lib/eth/eth_getTransactionReceipt.spec.ts
  packages/relay/tests/lib/eth/eth_sendRawTransaction.spec.ts
Labels: enhancement

#1958 [Snyk] Upgrade pnpm from 8.10.4 to 8.10.5
  package-lock.json
  packages/ws-server/package.json
Labels: dependencies

#1974 [Snyk] Upgrade redis from 4.6.10 to 4.6.11
  package-lock.json
  package.json
Labels: dependencies

#1976 Improving Caching for eth_getGasPrice
  docs/configuration.md
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/eth.ts
Labels: enhancement, P1

#1978 feat: Add option to configure file chunk size.
  docs/configuration.md
  packages/relay/src/lib/clients/sdkClient.ts
  packages/server/tests/acceptance/rpc_batch3.spec.ts
Labels: enhancement

#1975 [Snyk] Upgrade @hashgraph/sdk from 2.34.1 to 2.38.0
  dapp-example/package-lock.json
  dapp-example/package.json
Labels: dependencies

#1979 fix: Removed the contract revert reason from the eth_getTransactionByHash.
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth/eth_getTransactionByHash.spec.ts
  packages/server/tests/acceptance/rpc_batch3.spec.ts
Labels: bug

#1882 Add Rate Limits to batch request itself
  packages/server/src/koaJsonRpc/index.ts
  packages/server/src/koaJsonRpc/lib/methodConfiguration.ts
Labels: enhancement

#1982 feat: Upgraded CI runner.
  .github/workflows/acceptance-workflow.yml
Labels: enhancement

#1980 K6 Perf Test - Fix eth_estimateGas
  k6/src/scenarios/test/eth_estimateGas.js
Labels: enhancement

#1971 Acceptance Tests Improvement
  packages/server/tests/acceptance/rpc_batch3.spec.ts
Labels: bug, P2

#1887 Created a separate new metric for tracking the method results, simila…
  packages/server/src/koaJsonRpc/index.ts
  packages/server/src/koaJsonRpc/lib/HttpStatusCodeAndMessage.ts
Labels: enhancement, P2

#1877 Design Documentation for Batch Requests
  docs/design/batch-request.md
Labels: enhancement, P2

#1983 [Snyk] Security upgrade lerna from 7.4.2 to 8.0.1
  package-lock.json
  package.json
Labels: dependencies

#1990 fix: Handle INVALID_TRANSACTION together with FAIL_INVALID when Contract does not exists
  packages/relay/src/lib/errors/MirrorNodeClientError.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/helpers.ts
  packages/relay/tests/lib/eth/eth-config.ts
  packages/relay/tests/lib/eth/eth_call.spec.ts
  packages/server/tests/acceptance/htsPrecompile/precompileCalls.spec.ts
  packages/server/tests/acceptance/rpc_batch3.spec.ts
Labels: bug, P1

#1993 chore: Reapplying snyk upgrade, pnpm from 8.10.5 to 8.11.0
  package-lock.json
  packages/ws-server/package.json
Labels: dependencies

#1995 [Snyk] Upgrade keyv-file from 0.2.0 to 0.3.0
  package-lock.json
  packages/relay/package.json
Labels: dependencies

#1994 [Snyk] Upgrade @mui/material from 5.14.18 to 5.14.19
  dapp-example/package-lock.json
  dapp-example/package.json
Labels: dependencies

#1997 chore: [Snyk] Upgrade keyv-file from 0.2.0 to 0.3.0
  package-lock.json
  package.json
Labels: dependencies

#1998 chore: [Snyk] Upgrade @hashgraph/sdk from 2.38.0 to 2.39.0
  package-lock.json
  packages/relay/package.json
Labels: dependencies

#1999 chore: [Snyk] Upgrade ts-node from 10.9.1 to 10.9.2
  package-lock.json
  package.json
Labels: dependencies
