Repository hiero-ledger/hiero-json-rpc-relay, pull requests merged in 2023-02, with the labels that each got.

#862 Cache results from resolveEntityType
  package-lock.json
  package.json
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/tests/helpers.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
  packages/server/package.json
  packages/server/tests/acceptance/rpc_batch1.spec.ts
Labels: enhancement, P2

#872 GA release 0.17.0
  docker-compose.yml
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: enhancement, P1, process

#875 Replace hethers.js with ethers.js in hardhat-example
  packages/server/tests/acceptance/index.spec.ts
  packages/server/tests/helpers/prerequisite.ts
  tools/hardhat-example/README.md
  tools/hardhat-example/hardhat.config.js
  tools/hardhat-example/package-lock.json
  tools/hardhat-example/package.json
  tools/hardhat-example/scripts/contractCall.js
  tools/hardhat-example/scripts/contractViewCall.js
  tools/hardhat-example/scripts/deployContract.js
  tools/hardhat-example/scripts/showBalance.js
  tools/hardhat-example/scripts/transferHbars.js
  tools/hardhat-example/test/rpc.js
Labels: limechain, P2, dev tools

#855 HIP-583: Add test case for creating hollow account in the dapp example
  dapp-example/.gitignore
  dapp-example/src/App.js
  dapp-example/src/components/ActivateHollowAccountForm.js
  dapp-example/src/components/AssociateHTSTokensForm.js
  dapp-example/src/contracts/ContractTransferTx.json
  dapp-example/tests/e2e/bootstrap.js
  dapp-example/tests/e2e/specs/index.spec.js
  package-lock.json
Labels: enhancement, limechain, P2, process

#880 Add simple cache on `eth_call`
  .env.example
  README.md
  helm-chart/templates/configmap.yaml
  helm-chart/value-test.yaml
  helm-chart/values.yaml
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: enhancement, limechain, P1

#885 cherry pick #880 - simple cache for eth_call
  .env.example
  README.md
  helm-chart/templates/configmap.yaml
  helm-chart/value-test.yaml
  helm-chart/values.yaml
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: enhancement, P1, process

#886 Bump to version 0.17.1
  docker-compose.yml
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: enhancement, P1, process

#883 Handle GRPC timeout error
  .env.example
  README.md
  helm-chart/templates/configmap.yaml
  helm-chart/value-test.yaml
  helm-chart/values.yaml
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/relay/src/lib/errors/SDKClientError.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
  packages/server/tests/localAcceptance.env
Labels: enhancement, limechain, P1, dev tools

#898 865-update-logs-and-metrics. Added the requestId to the server context.
  package-lock.json
  packages/server/package.json
  packages/server/src/formatters.ts
  packages/server/src/koaJsonRpc/index.ts
  packages/server/src/rateLimit/index.ts
  packages/server/src/server.ts
Labels: enhancement, P1, process

#901 Cherry pick 0.18 commits since 0.18.0-alpha1
  .env.example
  README.md
  helm-chart/templates/configmap.yaml
  helm-chart/value-test.yaml
  helm-chart/values.yaml
  package-lock.json
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/relay/src/lib/errors/SDKClientError.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/hbarlimiter/index.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/hbarLimiter.spec.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
  packages/server/package.json
  packages/server/src/formatters.ts
  packages/server/src/koaJsonRpc/index.ts
  packages/server/src/rateLimit/index.ts
  packages/server/src/server.ts
  packages/server/tests/localAcceptance.env
Labels: enhancement, P1, process

#904 Bump 0.18.0-rc1
  README.md
  docker-compose.yml
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: enhancement, P1, process

#902 Bump 0.19.0-SNAPSHOT
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: enhancement, P1, process

#910 Add InteractingEntity label to ConsensusNode Metrics
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/precheck.ts
Labels: enhancement, P1

#935 GA 0.18.0 release
  docker-compose.yml
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: enhancement, P1, process

#934 Add exponential backoff to axios retry
  README.md
  helm-chart/value-test.yaml
  helm-chart/values.yaml
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/server/tests/localAcceptance.env
Labels: enhancement, limechain, P2

#937 Bump Image Versions and Update Packages
  package-lock.json
  package.json
  packages/server/tests/acceptance/index.spec.ts
  packages/server/tests/helpers/prerequisite.ts
Labels: enhancement, P1

#931 Cache the account mirror node query on `estimateGas` and `getTransactionByHash`
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: enhancement, P2

#930 Add cache to eth_getBlockByNumber
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: enhancement, P2

#917 Change `v` field in `eth_getTransactionByHash` and `eth_getBlockByHash` to be zeroHex instead of `null`
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: bug, P2

#951 Bump 0.19.0-rc1
  README.md
  docker-compose.yml
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
Labels: enhancement, P1, process

#919 893 Added support to configure SDK requestTimeOut.
  .env.example
  README.md
  helm-chart/value-test.yaml
  helm-chart/values.yaml
  packages/relay/src/lib/relay.ts
  packages/server/tests/localAcceptance.env
Labels: enhancement, P2
