Repository hiero-ledger/hiero-json-rpc-relay, pull requests merged in 2023-07, with the labels that each got.

#1417 fix: parsing of numeric env vars
  packages/relay/src/formatters.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/formatters.spec.ts
Labels: enhancement, P3

#1434 Fixes try catch tests and remove unecessary asseritons
  dapp-example/tests/e2e/specs/index.spec.js
  package-lock.json
  package.json
  packages/server/tests/acceptance/index.spec.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
  packages/server/tests/acceptance/rpc_batch3.spec.ts
Labels: enhancement, good first issue, P2

#1433 Update server to support cors preflight check
  packages/server/src/server.ts
  packages/server/tests/integration/server.spec.ts
Labels: enhancement, P1

#1432 Fix clientCache metric collection
  packages/relay/src/lib/clients/clientCache.ts
  packages/server/tests/integration/server.spec.ts
Labels: bug, P1

#1451 Bump version 0 26 3
  charts/hedera-json-rpc-relay-websocket/Chart.yaml
  charts/hedera-json-rpc-relay/Chart.yaml
  docker-compose.yml
  docs/openrpc.json
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: enhancement, P1, process

#1430 Improve handling of Mirror Node API failures response objects
  packages/relay/src/formatters.ts
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/relay/src/lib/errors/MirrorNodeClientError.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/helpers.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
Labels: enhancement, P2

#1446 Improve `eth_sendRawTransaction` latency by simplifying precheck
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/precheck.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/openrpc.spec.ts
  packages/relay/tests/lib/precheck.spec.ts
Labels: enhancement, P2, perf

#1464 Bump version 0.28.0-SNAPSHOT
  charts/hedera-json-rpc-relay-websocket/Chart.yaml
  charts/hedera-json-rpc-relay/Chart.yaml
  docs/openrpc.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: enhancement, P1, process

#1465 Fix README and pnpm inconsistencies
  Dockerfile
  README.md
  package-lock.json
  packages/relay/package.json
Labels: enhancement, P3, process

#1469 Improve handling of boolean cache retrieval and metric labels
  packages/relay/src/lib/clients/clientCache.ts
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/clients/clientCache.spec.ts
Labels: bug, P1, perf

#1499 Bump PR 0.27.0-rc2
  charts/hedera-json-rpc-relay-websocket/Chart.yaml
  charts/hedera-json-rpc-relay/Chart.yaml
  docker-compose.yml
  docs/openrpc.json
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: enhancement, P1, process

#1244 Improve logging across classes
  package-lock.json
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/relay.ts
  packages/relay/tests/helpers.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
  packages/relay/tests/lib/openrpc.spec.ts
  packages/server/src/server.ts
  packages/server/tests/acceptance/index.spec.ts
  packages/server/tests/acceptance/ws/subscribe.spec.ts
  packages/ws-server/src/webSocketServer.ts
Labels: enhancement, P2

#1509 Add Remix IDE in tools Readme.md
  tools/README.md
Labels: documentation

#1497 Changes way of sending raw transaction instead of relay.call with rel…
  packages/server/tests/acceptance/rpc_batch1.spec.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
  packages/server/tests/acceptance/rpc_batch3.spec.ts
  packages/server/tests/helpers/assertions.ts
Labels: enhancement, limechain, P2

#1510 Handles CONTRACT_REVERT properly be returning the message.
  package-lock.json
  packages/relay/src/lib/errors/MirrorNodeClientError.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/server/tests/acceptance/erc20.spec.ts
  packages/server/tests/acceptance/index.spec.ts
Labels: enhancement, P1

#1517 Bump PR 0.27.1
  charts/hedera-json-rpc-relay-websocket/Chart.yaml
  charts/hedera-json-rpc-relay/Chart.yaml
  docker-compose.yml
  docs/openrpc.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: enhancement, P1, process

#1496 Optimize eth_getTransactionCount
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/openrpc.spec.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
Labels: enhancement

#1519 Using better-lookup to improve dns resolution performance for each outgoing requests
  docs/configuration.md
  package-lock.json
  packages/relay/package.json
  packages/relay/src/lib/clients/mirrorNodeClient.ts
Labels: enhancement

#1526 Bumping up hashgraph sdk version
  package-lock.json
  packages/relay/package.json
  packages/ws-server/package.json
Labels: enhancement, P1, dependencies

#1529 Bumping up hedera-local version to latest v2.11.0
  package-lock.json
  package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: enhancement, P1, dependencies

#1538 Bump versions for v0.29.0-SNAPSHOT
  charts/hedera-json-rpc-relay-websocket/Chart.yaml
  charts/hedera-json-rpc-relay/Chart.yaml
  docs/openrpc.json
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: P1, process

#1534 Returned bytecode is incorrect after selfdestruct and recreation via create2
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: bug, limechain, P2

#1536 subscriptions_enabled=true is necessary to enable the websockets func…
  charts/hedera-json-rpc-relay-websocket/templates/configmap.yaml
Labels: enhancement, P1, process

#1545 Cherry-Pick: 1534 - Returned bytecode is incorrect after selfdestruct and recreation via …
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: bug, limechain, P2

#1518 Construct Synthetic Contract Result
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/modelConverter.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/ethGetBlockBy.spec.ts
Labels: enhancement, P1, dev tools

#1537 refactor getContractByteCode to set cost based on the sdk assessment
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/eth.ts
Labels: enhancement, P1

#1547 Cherry pick 1518: construct synthetic contract result for HTS
  docs/configuration.md
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/modelConverter.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/ethGetBlockBy.spec.ts
Labels: enhancement, P1, process

#1556 Increase default number of sockets for mirror node client to 300
  packages/relay/src/lib/clients/mirrorNodeClient.ts
Labels: enhancement, P2, perf

#1554 Gating Populate Synthetic Transaction Feature for ability to control via property configuration
  docs/configuration.md
  packages/relay/src/lib/eth.ts
Labels: enhancement, P1

#1564 Changed nulls for synthetic values when returning a synthetic transaction log
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: bug, enhancement, P1

#1566 Productize mirror node configuration to keep alive by default
  packages/relay/src/lib/clients/mirrorNodeClient.ts
Labels: P2, perf

#1571 Configurable Page Max for Contract Results Logs
  docs/configuration.md
  packages/relay/src/lib/clients/mirrorNodeClient.ts
Labels: bug, enhancement, P1

#1573 Cherry-Pick #1571 - Configurable Page Max for Contract Results Logs
  docs/configuration.md
  packages/relay/src/lib/clients/mirrorNodeClient.ts
Labels: enhancement, P1, process

#1576 Add couple of diagrams
  docs/diagrams/hapi-service-diagram.md
  docs/diagrams/hbar-limiter-diagram.md
  docs/diagrams/operation.md
  docs/diagrams/project-overview-diagram.md
Labels: documentation, P3

#1578 [Snyk] Upgrade truffle from 5.10.1 to 5.10.2
  tools/truffle-example/package-lock.json
  tools/truffle-example/package.json
Labels: P3, dependencies

#1561 This is the exported JSON from the grafana dashboard
  README.md
  charts/hedera-json-rpc/dashboards/hedera-json-rpc-relay-http-server.json
Labels: enhancement, P3, process

#1572 Improves few tests and an assert method
  packages/server/tests/acceptance/rateLimiter.spec.ts
  packages/server/tests/acceptance/ws/subscribe.spec.ts
  packages/server/tests/helpers/assertions.ts
Labels: enhancement, P2

#1549 Bump image versions in acceptance tests
  package-lock.json
  package.json
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/errors/MirrorNodeClientError.ts
  packages/relay/src/lib/eth.ts
  packages/server/package.json
  packages/server/tests/acceptance/erc20.spec.ts
  packages/server/tests/acceptance/htsPrecompile/precompileCalls.spec.ts
  packages/server/tests/acceptance/htsPrecompile/tokenCreate.spec.ts
  packages/server/tests/acceptance/index.spec.ts
  packages/server/tests/helpers/prerequisite.ts
  packages/ws-server/package.json
Labels: enhancement, P1

#1586 1581 set typeof in undefined condition
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: bug, P2

#1535 Update eth_getTransactionCount to return contract nonce
  packages/relay/src/lib/eth.ts
  packages/relay/tests/helpers.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/server/tests/acceptance/erc20.spec.ts
  packages/server/tests/acceptance/htsPrecompile/tokenCreate.spec.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
  packages/server/tests/acceptance/rpc_batch3.spec.ts
  packages/server/tests/clients/servicesClient.ts
  packages/server/tests/contracts/Deployer.json
  packages/server/tests/contracts/Deployer.sol
  packages/server/tests/contracts/MockContract.json
  packages/server/tests/helpers/assertions.ts
Labels: enhancement, P1

#1589 Bump PR. 30-SNAPSHOT
  charts/hedera-json-rpc-relay-websocket/Chart.yaml
  charts/hedera-json-rpc-relay/Chart.yaml
  docs/openrpc.json
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: enhancement, P1, process
