Repository hiero-ledger/hiero-json-rpc-relay, pull requests merged in 2023-05, with the labels that each got.

#1142 Load Test
  k6/README.md
  k6/src/lib/common.js
  k6/src/prepare/prep.js
  k6/src/scenarios/test/eth_call.js
Labels: enhancement, P1

#1157 Update eth_estimateGas to handle invalid to and value
  packages/relay/src/index.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
  packages/server/tests/integration/server.spec.ts
  packages/server/tests/postman.json
Labels: bug, P1

#1163 Axios Retries against mirror node refactored
  packages/relay/src/lib/clients/mirrorNodeClient.ts
Labels: enhancement, P1, perf

#1175 Updated eth_estimateGas bad input tests
  packages/relay/tests/lib/eth.spec.ts
Labels: bug, P1

#1158 Add resolve type consideration for tokens
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
  packages/ws-server/src/webSocketServer.ts
Labels: enhancement, P1

#1178 feat: add server section to openrpc spec
  docs/openrpc.json
Labels: documentation, enhancement, P2

#1184 Add resolve type consideration for tokens (#1158)
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
  packages/ws-server/src/webSocketServer.ts
Labels: enhancement, P1

#1177 Add caching logic to getTinyBarGasFee()
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/constants.ts
  packages/relay/tests/lib/sdkClient.spec.ts
Labels: enhancement, P1, perf

#1206 change so we only retry on 404s if a retry is desired (#1194)
  docs/configuration.md
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/errors/MirrorNodeClientError.ts
Labels: bug, P2

#1170 Edit eth_getCode cache
  package-lock.json
  packages/relay/package.json
  packages/relay/src/lib/errors/SDKClientError.ts
  packages/relay/src/lib/eth.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
  packages/server/tests/contracts/Basic.json
  packages/server/tests/contracts/Basic.sol
Labels: bug, P1

#1216 resolveEntityType error handling improvement inside promises
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: bug, P1

#1135 Add metrics to the Websocket server
  .env.example
  docs/configuration.md
  packages/relay/src/index.ts
  packages/relay/src/lib/poller.ts
  packages/relay/src/lib/relay.ts
  packages/relay/src/lib/subscriptionController.ts
  packages/relay/tests/lib/poller.spec.ts
  packages/relay/tests/lib/subscriptionController.spec.ts
  packages/server/tests/acceptance/index.spec.ts
  packages/ws-server/src/ConnectionLimiter.ts
  packages/ws-server/src/index.ts
  packages/ws-server/src/webSocketServer.ts
Labels: enhancement, P2, eth_subscribe

#1193 Update websocket documentation
  README.md
  docs/design/eth-subscribe.md
  docs/live-events-api.md
  docs/rpc-api.md
Labels: documentation, enhancement, eth_subscribe

#1217 Cherry-Pick: resolveEntityType error handling improvement inside promises (#1216)
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: bug, P1

#1230 Add cache on MirrorNodeClient.getBlock() (#1192)
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/constants.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
Labels: enhancement, P1

#1234 Return meaningful JSON RPC errors (#1213)
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
  packages/server/tests/clients/relayClient.ts
Labels: enhancement, P2

#1235 HotFix to re-create the sdk client every X amount of request on runt…
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/relay.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/openrpc.spec.ts
Labels: enhancement, P1, perf

#1196 Update dockerfile build based on debian
  Dockerfile
Labels: enhancement, P1, process, perf

#1237 Bump 0.23.1
  docker-compose.yml
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: enhancement, P1

#1212 Add cache support for eth_getTransactionReceipt
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: enhancement

#1149 Add Helm chart scaling and test improvements
  .github/ct.yaml
  .github/workflows/charts.yml
  helm-chart/Chart.yaml
  helm-chart/ci/default-values.yaml
  helm-chart/postman.json
  helm-chart/templates/_helpers.tpl
  helm-chart/templates/configmap.yaml
  helm-chart/templates/cronjob.yaml
  helm-chart/templates/deployment.yaml
  helm-chart/templates/hpa.yaml
  helm-chart/templates/ingress.yaml
  helm-chart/templates/role.yaml
  helm-chart/templates/rolebinding.yaml
  helm-chart/templates/secret.yaml
  helm-chart/templates/service.yaml
  helm-chart/templates/serviceaccount.yaml
  helm-chart/templates/tests/configmap.yaml
  helm-chart/templates/tests/pod.yaml
  helm-chart/values.yaml
Labels: enhancement, P1, process

#1219 Configurable default gas for eth_call
  docs/configuration.md
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
Labels: enhancement, P2

#1210 Add cache support for eth_getBlockByHash
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: enhancement, P2, perf

#1251 bump version 0.23.2
  docker-compose.yml
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: enhancement, P1

#1168 Support websocket server in docker
  .env.example
  Dockerfile
  docker-compose.yml
  docs/configuration.md
  packages/ws-server/src/index.ts
  packages/ws-server/src/webSocketServer.ts
Labels: enhancement, P1

#1221 Add cache support for eth_getBlockTransactionCountByNumber and eth_getBlockTransactionCountByHash
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: enhancement, P2, perf

#1252 Fix SDK reinitialization
  .env.example
  helm-chart/templates/configmap.yaml
  helm-chart/value-test.yaml
  helm-chart/values.yaml
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/errors/SDKClientError.ts
  packages/relay/src/lib/eth.ts
Labels: bug, P1

#1254 Bump Relay Version to 0.23.3
  docker-compose.yml
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: enhancement, P1, process

#1167 eth_estimateGas w/o precompiles tests
  packages/relay/src/lib/eth.ts
  packages/server/tests/acceptance/estimateGasContract.spec.ts
  packages/server/tests/contracts/EstimateGasContract.json
  packages/server/tests/contracts/EstimateGasContract.sol
  packages/server/tests/helpers/utils.ts
Labels: enhancement, P2

#1264 configurable eth_call accepted errors
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
  packages/server/tests/acceptance/htsPrecompile/precompileCalls.spec.ts
  packages/server/tests/acceptance/rpc_batch3.spec.ts
Labels: enhancement, P1

#1266 bump version 0.23.4
  docker-compose.yml
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: enhancement, P1, process

#1241 Add SDK Client Service
  .env.example
  dapp-example/package-lock.json
  dapp-example/package.json
  docs/configuration.md
  docs/examples/package.json
  helm-chart/templates/configmap.yaml
  helm-chart/value-test.yaml
  helm-chart/values.yaml
  package-lock.json
  packages/relay/package.json
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/precheck.ts
  packages/relay/src/lib/relay.ts
  packages/relay/src/lib/services/hapiService/hapiService.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/hapiService.spec.ts
  packages/relay/tests/lib/openrpc.spec.ts
  packages/relay/tests/lib/precheck.spec.ts
  packages/relay/tests/lib/sdkClient.spec.ts
  packages/relay/tests/test.env
  packages/server/package.json
  packages/server/tests/localAcceptance.env
Labels: enhancement, limechain, P1, perf

#1273 bump versions 0.23.5
  docker-compose.yml
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: enhancement, P1

#1267 Expand eth_estimateGas w/o precompiles test cases
  packages/server/tests/acceptance/estimateGasContract.spec.ts
  packages/server/tests/contracts/EstimateGasContract.json
  packages/server/tests/contracts/EstimateGasContract.sol
Labels: enhancement, P2

#1275 Cherry-Pick: Return correct error for rate limit (#1269)
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/errors/MirrorNodeClientError.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/helpers.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
  packages/server/tests/acceptance/htsPrecompile/precompileCalls.spec.ts
  packages/server/tests/acceptance/rpc_batch3.spec.ts
Labels: bug, P2

#1271 Paginate eth_getBlockByHash
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/helpers.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
Labels: bug, P1

#1279 936 block number range test
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: enhancement, P1

#1280 Refactor `eth_estimateGas`
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: enhancement, P2

#1281 bump version 0.24.0-rc1
  README.md
  docker-compose.yml
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: enhancement, P1, process

#1282 bump version 0.25.0-SNAPSHOT
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: enhancement, P1, process

#1137 tests: refactor constants and fix failing tests #1129
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/eth.ts
  packages/server/tests/acceptance/erc20.spec.ts
  packages/server/tests/acceptance/htsPrecompile/precompileCalls.spec.ts
  packages/server/tests/acceptance/htsPrecompile/tokenCreate.spec.ts
  packages/server/tests/acceptance/htsPrecompile/tokenManagement.spec.ts
  packages/server/tests/acceptance/htsPrecompile_v1.spec.ts
  packages/server/tests/acceptance/index.spec.ts
  packages/server/tests/acceptance/rateLimiter.spec.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
  packages/server/tests/acceptance/rpc_batch3.spec.ts
  packages/server/tests/helpers/constants.ts
  packages/server/tests/integration/server.spec.ts
  tsconfig.json
Labels: enhancement, limechain, P3

#1243 feat(chart): Support an existing secret and configmap
  helm-chart/templates/deployment.yaml
  helm-chart/templates/secret.yaml
  helm-chart/values.yaml
Labels: enhancement, P2, process

#1285 Stabilize Dapp Tests
  dapp-example/package-lock.json
  dapp-example/package.json
  dapp-example/src/components/ActivateHollowAccountForm.js
  dapp-example/src/contracts/IHRC.json
  dapp-example/tests/e2e/specs/index.spec.js
  packages/relay/src/lib/eth.ts
Labels: enhancement, P2, process

#1286 Handle null transaction on contract revert.
  .DS_Store
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
Labels: bug, P1

#1290 Bump 0.24.0
  docker-compose.yml
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: enhancement, P1, process

#1253 feat(ci): Release the helm chart to gh pages
  .github/ct.yaml
  .github/workflows/charts.yml
  .github/workflows/release-production.yml
  charts/hedera-json-rpc-relay/Chart.yaml
  charts/hedera-json-rpc-relay/ci/default-values.yaml
  charts/hedera-json-rpc-relay/environments/minikube.yaml
  charts/hedera-json-rpc-relay/postman.json
  charts/hedera-json-rpc-relay/templates/_helpers.tpl
  charts/hedera-json-rpc-relay/templates/configmap.yaml
  charts/hedera-json-rpc-relay/templates/cronjob.yaml
  charts/hedera-json-rpc-relay/templates/deployment.yaml
  charts/hedera-json-rpc-relay/templates/hpa.yaml
  charts/hedera-json-rpc-relay/templates/ingress.yaml
  charts/hedera-json-rpc-relay/templates/role.yaml
  charts/hedera-json-rpc-relay/templates/rolebinding.yaml
  charts/hedera-json-rpc-relay/templates/secret.yaml
  charts/hedera-json-rpc-relay/templates/service.yaml
  charts/hedera-json-rpc-relay/templates/serviceaccount.yaml
  charts/hedera-json-rpc-relay/templates/tests/configmap.yaml
  charts/hedera-json-rpc-relay/templates/tests/pod.yaml
  charts/hedera-json-rpc-relay/value-test.yaml
  charts/hedera-json-rpc-relay/values.yaml
Labels: enhancement, P2, process

#1294 Handle invalid call response from consensus node
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: bug, P1

#1308 Fix relay operator balance gauge
  packages/relay/src/lib/relay.ts
Labels: bug, P1

#1300 Added configurable maxChunks parameter to the FileAppendTransaction
  .env.example
  docs/configuration.md
  packages/relay/src/lib/clients/sdkClient.ts
Labels: enhancement, P2

#1302 Add processs unhandledRejection and uncaughtException server logs
  packages/server/src/server.ts
  packages/ws-server/src/webSocketServer.ts
Labels: enhancement, P1

#1310 Updated to reflect new directory structure.
  scripts/.bump-version.js
Labels: enhancement, P2, process

#1312 Bump 0.25.0 rc1
  README.md
  charts/hedera-json-rpc-relay/Chart.yaml
  docker-compose.yml
  docs/openrpc.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
  scripts/.bump-version.js
Labels: enhancement, P1, process
