Repository hiero-ledger/hiero-json-rpc-relay, pull requests merged in 2023-08, with the labels that each got.

#1588 Bump PR. 0.29.0-rc1
  README.md
  charts/hedera-json-rpc-relay-websocket/Chart.yaml
  charts/hedera-json-rpc-relay/Chart.yaml
  docker-compose.yml
  docs/openrpc.json
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: enhancement

#1563 Call mirror node accounts api without requesting transactions list
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
  packages/relay/tests/lib/openrpc.spec.ts
Labels: enhancement, P1, perf

#1594 Refactor `EthImpl.formatContractResult()`
  packages/relay/src/formatters.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/precheck.ts
  packages/relay/src/lib/relay.ts
  packages/relay/tests/assertions.ts
  packages/relay/tests/helpers.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/ethGetBlockBy.spec.ts
  packages/relay/tests/lib/formatters.spec.ts
  packages/relay/tests/lib/openrpc.spec.ts
  packages/server/tests/acceptance/htsPrecompile/precompileCalls.spec.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
  packages/server/tests/acceptance/rpc_batch3.spec.ts
Labels: enhancement, limechain, P3

#1598 Call mirror node accounts api without requesting transactions list (#…
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
  packages/relay/tests/lib/openrpc.spec.ts
Labels: enhancement, P1, perf

#1606 Refactor and cleanup Dockerfile
  Dockerfile
Labels: bug

#1590 Implement `eth_uninstallFilter`
  docs/rpc-api.md
  packages/relay/package.json
  packages/relay/src/index.ts
  packages/relay/src/lib/clients/clientCache.ts
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/services/ethService/ethFilterService/IFilterService.ts
  packages/relay/src/lib/services/ethService/ethFilterService/index.ts
  packages/relay/src/lib/services/ethService/index.ts
  packages/relay/tests/lib/clients/clientCache.spec.ts
  packages/relay/tests/lib/services/eth/filter.spec.ts
  packages/server/src/koaJsonRpc/lib/methodConfiguration.ts
  packages/server/src/server.ts
  packages/server/src/validator/methods.ts
  packages/server/tests/acceptance/rpc_batch3.spec.ts
  packages/server/tests/helpers/constants.ts
Labels: enhancement, P1

#1619 Add unsupported eth_newPendingTransactionFilter
  docs/openrpc.json
  docs/rate-limiting.md
  docs/rpc-api.md
  packages/relay/src/lib/services/ethService/ethFilterService/IFilterService.ts
  packages/relay/src/lib/services/ethService/ethFilterService/index.ts
  packages/server/src/koaJsonRpc/lib/methodConfiguration.ts
  packages/server/src/server.ts
  packages/server/tests/acceptance/rpc_batch3.spec.ts
  packages/server/tests/helpers/constants.ts
Labels: enhancement, P1

#1615 Fix `eth_estimateGas` transaction values formatting
  packages/relay/src/formatters.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/formatters.spec.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
Labels: bug

#1314 Migrate from ethers v5 to v6
  package-lock.json
  package.json
  packages/relay/package.json
  packages/relay/src/lib/precheck.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/formatters.spec.ts
  packages/relay/tests/lib/openrpc.spec.ts
  packages/server/package.json
  packages/server/tests/acceptance/erc20.spec.ts
  packages/server/tests/acceptance/estimateGasContract.spec.ts
  packages/server/tests/acceptance/htsPrecompile/precompileCalls.spec.ts
  packages/server/tests/acceptance/htsPrecompile/tokenCreate.spec.ts
  packages/server/tests/acceptance/htsPrecompile/tokenManagement.spec.ts
  packages/server/tests/acceptance/htsPrecompile_v1.spec.ts
  packages/server/tests/acceptance/index.spec.ts
  packages/server/tests/acceptance/rateLimiter.spec.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
  packages/server/tests/acceptance/rpc_batch3.spec.ts
  packages/server/tests/acceptance/ws/subscribe.spec.ts
  packages/server/tests/clients/relayClient.ts
  packages/server/tests/clients/servicesClient.ts
  packages/server/tests/helpers/assertions.ts
  packages/server/tests/helpers/prerequisite.ts
  packages/server/tests/helpers/utils.ts
  packages/ws-server/package.json
  tools/hardhat-example/package-lock.json
  tools/hardhat-example/package.json
  tools/subgraph-example/package-lock.json
  tools/subgraph-example/package.json
Labels: enhancement, limechain, P1, dev tools

#1618 Add eth_newBlockFilter
  docs/openrpc.json
  docs/rate-limiting.md
  docs/rpc-api.md
  packages/relay/src/lib/services/ethService/ethFilterService/IFilterService.ts
  packages/relay/src/lib/services/ethService/ethFilterService/index.ts
  packages/relay/tests/lib/services/eth/filter.spec.ts
  packages/server/src/koaJsonRpc/lib/methodConfiguration.ts
  packages/server/src/server.ts
  packages/server/tests/acceptance/rpc_batch3.spec.ts
  packages/server/tests/helpers/constants.ts
Labels: enhancement, P1

#1624 Implement eth_getFilterLogs
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/services/ethService/ethCommonService/ICommonService.ts
  packages/relay/src/lib/services/ethService/ethCommonService/index.ts
  packages/relay/src/lib/services/ethService/ethFilterService/IFilterService.ts
  packages/relay/src/lib/services/ethService/ethFilterService/index.ts
  packages/relay/tests/lib/services/eth/filter.spec.ts
  packages/server/src/koaJsonRpc/lib/methodConfiguration.ts
  packages/server/src/server.ts
  packages/server/src/validator/methods.ts
Labels: enhancement, limechain, P1

#1610 [Snyk] Security upgrade mocha from 9.2.2 to 10.1.0
  package-lock.json
  packages/ws-server/package.json
Labels: dependencies

#1639 Add docs for `eth_getFilterLogs`
  docs/openrpc.json
  docs/rate-limiting.md
  docs/rpc-api.md
Labels: documentation, enhancement, limechain, P3

#1643 [Snyk] Upgrade @mui/material from 5.14.1 to 5.14.2
  dapp-example/package-lock.json
  dapp-example/package.json
Labels: dependencies

#1626 Add eth_getFilterChanges
  docs/openrpc.json
  docs/rate-limiting.md
  docs/rpc-api.md
  package-lock.json
  packages/relay/src/lib/services/ethService/ethFilterService/IFilterService.ts
  packages/relay/src/lib/services/ethService/ethFilterService/index.ts
  packages/relay/tests/lib/services/eth/filter.spec.ts
  packages/server/src/koaJsonRpc/lib/methodConfiguration.ts
  packages/server/src/server.ts
  packages/server/tests/acceptance/rpc_batch3.spec.ts
  packages/server/tests/helpers/constants.ts
Labels: enhancement

#1646 Reapplied web3js changes.
  package-lock.json
  packages/relay/src/formatters.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/formatters.spec.ts
  tools/web3js-example/package-lock.json
  tools/web3js-example/package.json
  tools/web3js-example/scripts/contractCall.js
  tools/web3js-example/scripts/contractViewCall.js
  tools/web3js-example/scripts/deployContract.js
  tools/web3js-example/scripts/showBalance.js
  tools/web3js-example/scripts/transferHbars.js
  tools/web3js-example/test/rpc.js
Labels: enhancement, P1, dev tools

#1640 Fix eth_getBalance to accept hash
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/server/src/validator/methods.ts
  packages/server/src/validator/utils.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
  packages/server/tests/integration/server.spec.ts
Labels: enhancement, P2

#1653 [Snyk] Upgrade @hashgraph/sdk from 2.29.0 to 2.31.0
  dapp-example/package-lock.json
  dapp-example/package.json
Labels: P2, dependencies

#1645 Adds withdrawals and withdrawalsRoot properties with default values
  docs/openrpc.json
  packages/relay/src/lib/model.ts
Labels: enhancement, P2

#1651 Removed 400 AcceptedErrorCodes from MirrorNodeClient for GET_ACCOUNTS_BY_ID_ENDPOINT path
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
Labels: enhancement, P2

#1652 added null check for non found account for given block in the past
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: bug, P2

#1667 Cherry-Pick: Add ping messages to websocket server (#1658)
  charts/hedera-json-rpc-relay-websocket/templates/configmap.yaml
  charts/hedera-json-rpc-relay-websocket/values.yaml
  docs/configuration.md
  package-lock.json
  packages/server/tests/acceptance/ws/subscribe.spec.ts
  packages/ws-server/src/webSocketServer.ts
Labels: P2, process

#1662 Implement accurate assertions with new ethers v6 errors/reverts mechanism
  packages/server/tests/acceptance/rpc_batch1.spec.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
  packages/server/tests/acceptance/rpc_batch3.spec.ts
  packages/server/tests/clients/relayClient.ts
  packages/server/tests/helpers/assertions.ts
Labels: enhancement, limechain

#1676 [Snyk] Upgrade @mui/material from 5.14.2 to 5.14.3
  dapp-example/package-lock.json
  dapp-example/package.json
Labels: P2, dependencies

#1663 Adds type property to getTransactionReceipt response
  packages/relay/src/lib/eth.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
  packages/server/tests/helpers/assertions.ts
Labels: enhancement, limechain, P2

#1675 Support synthetic logs in eth_subscribe
  packages/relay/src/lib/constants.ts
  packages/server/tests/acceptance/ws/subscribe.spec.ts
  packages/ws-server/src/webSocketServer.ts
Labels: enhancement, limechain, eth_subscribe

#1683 Add request-id as part of all response headers
  packages/server/src/koaJsonRpc/index.ts
  packages/server/tests/integration/server.spec.ts
Labels: enhancement, P2

#1678 Refactor connection TTL logic in WS server
  charts/hedera-json-rpc-relay-websocket/templates/configmap.yaml
  charts/hedera-json-rpc-relay-websocket/values.yaml
  docs/configuration.md
  packages/relay/src/lib/subscriptionController.ts
  packages/relay/tests/lib/subscriptionController.spec.ts
  packages/server/tests/acceptance/ws/subscribe.spec.ts
  packages/ws-server/src/ConnectionLimiter.ts
  packages/ws-server/src/webSocketServer.ts
Labels: enhancement, limechain, eth_subscribe

#1679 Adds new types of transactions
  packages/relay/src/formatters.ts
  packages/relay/src/lib/model.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/formatters.spec.ts
Labels: enhancement, P2
