Repository hiero-ledger/hiero-json-rpc-relay, pull requests merged in 2023-06, with the labels that each got.

#1255 Fix flaky acceptance tests
  dapp-example/src/components/AssociateHTSTokensForm.js
  dapp-example/tests/e2e/bootstrap.js
  package-lock.json
  package.json
  packages/relay/src/lib/eth.ts
  packages/server/package.json
  packages/server/tests/acceptance/erc20.spec.ts
  packages/server/tests/acceptance/htsPrecompile/precompileCalls.spec.ts
  packages/server/tests/acceptance/htsPrecompile/tokenCreate.spec.ts
  packages/server/tests/acceptance/htsPrecompile/tokenManagement.spec.ts
  packages/server/tests/acceptance/htsPrecompile_v1.spec.ts
  packages/server/tests/acceptance/index.spec.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
  packages/server/tests/acceptance/rpc_batch3.spec.ts
  packages/server/tests/acceptance/ws/subscribe.spec.ts
  packages/server/tests/clients/servicesClient.ts
  packages/server/tests/helpers/prerequisite.ts
  packages/server/tests/helpers/utils.ts
  packages/server/tests/localAcceptance.env
Labels: enhancement, limechain, process

#1325 Set initialErrorCodes to [50] by default if missing
  packages/relay/src/lib/services/hapiService/hapiService.ts
Labels: enhancement, P1

#1320 Set ETH_CALL_DEFAULT_TO_CONSENSUS_NODE to false
  charts/hedera-json-rpc-relay/values.yaml
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/openrpc.spec.ts
Labels: enhancement, P1

#1318 Fix helm chart ingress template
  charts/hedera-json-rpc-relay/templates/ingress.yaml
Labels: enhancement, P2

#1303 Add structure for clientCache class
  docs/configuration.md
  packages/relay/src/lib/clients/clientCache.ts
  packages/relay/src/lib/clients/index.ts
Labels: enhancement, P2

#1316 Header: x-api-key
  docs/configuration.md
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
Labels: enhancement, P2

#1334 Fixed test to use correct contract to estimate gas. Gas is estimated for running the ping method which belongs to the basic contract, not the mirror contract.
  packages/server/tests/acceptance/rpc_batch2.spec.ts
Labels: bug, P2

#1335 Bump Synpress Version
  dapp-example/package-lock.json
  dapp-example/package.json
  dapp-example/tests/e2e/specs/index.spec.js
Labels: enhancement, limechain, P2, process

#1340 Optimize mirror node get accounts call with limit
  package-lock.json
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
  packages/relay/tests/lib/net.spec.ts
  packages/relay/tests/lib/openrpc.spec.ts
  packages/relay/tests/lib/precheck.spec.ts
  packages/relay/tests/lib/web3.spec.ts
Labels: enhancement, P1

#1342 Catch JsonRpcError on balance check
  packages/relay/src/lib/precheck.ts
Labels: enhancement, P2

#1344 Handle max pagination
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
  packages/relay/tests/lib/precheck.spec.ts
Labels: enhancement, P2

#1353 Add configurability of mirrorNodeContractResultsPageMax
  docs/configuration.md
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
Labels: enhancement, P1

#1306 Add manual CI for acceptance tests
  .github/workflows/acceptance-public.yml
  .github/workflows/acceptance-workflow.yml
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/precheck.ts
  packages/relay/src/lib/relay.ts
  packages/relay/src/lib/services/hapiService/hapiService.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/openrpc.spec.ts
  packages/relay/tests/lib/precheck.spec.ts
  packages/relay/tests/lib/sdkClient.spec.ts
  packages/server/src/koaJsonRpc/index.ts
  packages/server/src/koaJsonRpc/lib/methodConfiguration.ts
  packages/server/tests/acceptance/htsPrecompile/tokenCreate.spec.ts
  packages/server/tests/acceptance/htsPrecompile/tokenManagement.spec.ts
  packages/server/tests/acceptance/index.spec.ts
  packages/server/tests/acceptance/rateLimiter.spec.ts
  packages/server/tests/acceptance/rpc_batch3.spec.ts
  packages/server/tests/acceptance/ws/subscribe.spec.ts
  packages/server/tests/localAcceptance.env
  packages/server/tests/previewnetAcceptance.env
  packages/server/tests/testnetAcceptance.env
  packages/ws-server/src/index.ts
Labels: enhancement, P3, process

#1332 Improvements on load testing to avoid only hitting cache and have mor…
  k6/README.md
  k6/src/lib/common.js
  k6/src/prepare/prep.js
  k6/src/scenarios/apis.js
  k6/src/scenarios/test/eth_call.js
  k6/src/scenarios/test/eth_getBalance.js
  k6/src/scenarios/test/eth_getBlockByNumber.js
  k6/src/scenarios/test/eth_getCode.js
  k6/src/scenarios/test/eth_getLogs.js
  k6/src/scenarios/test/eth_getTransactionCount.js
  k6/src/scenarios/test/eth_sendRawTransaction.js
Labels: enhancement, P3

#1354 1150 add metrics to capture function called
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/relay.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/openrpc.spec.ts
Labels: enhancement, P2

#1351 Reorganize latency calculation logic
  packages/server/src/koaJsonRpc/index.ts
  packages/server/src/server.ts
Labels: enhancement, P2

#1350 Add terminationGracePeriodSeconds to chart deployment resource
  charts/hedera-json-rpc-relay-websocket/templates/deployment.yaml
  charts/hedera-json-rpc-relay/templates/deployment.yaml
Labels: enhancement, P2

#1369 Simplify DApp tests layout
  .github/workflows/acceptance.yml
  .github/workflows/dapp.yml
  dapp-example/src/components/ActivateHollowAccountForm.js
  dapp-example/src/components/AssociateHTSTokensForm.js
  dapp-example/src/components/TransferHTSTokensForm.js
  dapp-example/tests/e2e/specs/index.spec.js
  package.json
Labels: enhancement, P1, process

#1370 Fix performCallBlockParamChecks latest block check
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: enhancement, P2, process

#1103 Improve eth_transactionCount perf
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/helpers.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
  packages/server/tests/acceptance/htsPrecompile/tokenCreate.spec.ts
  packages/server/tests/acceptance/htsPrecompile/tokenManagement.spec.ts
  packages/server/tests/acceptance/rateLimiter.spec.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
  packages/server/tests/acceptance/ws/subscribe.spec.ts
Labels: enhancement, P1

#1372 1357 - Added max transaction count that can be returned on an eth_get…
  docs/configuration.md
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: bug, P2, perf

#1382 1354 fix cannot read null bug
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: bug, P1

#1384 Batch parallel contract result requests for detailed block info
  docs/configuration.md
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/ethGetBlockBy.spec.ts
Labels: enhancement, P1, perf

#1367 Removed a call to the mirror node.
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/openrpc.spec.ts
Labels: enhancement, P1

#1381 Simplify this down to one container and the built-in wget
  charts/hedera-json-rpc-relay/templates/cronjob.yaml
Labels: enhancement, P3, process

#1256 Bump Acceptance Tests Node Images
  packages/server/tests/acceptance/index.spec.ts
  packages/server/tests/helpers/prerequisite.ts
Labels: enhancement, P2, process

#1347 Remove `from` check from `eth_call` prechecks
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/server/tests/acceptance/htsPrecompile/precompileCalls.spec.ts
  packages/server/tests/acceptance/rpc_batch3.spec.ts
Labels: enhancement, P1

#1389 bump version 0.26.0-rc1
  README.md
  charts/hedera-json-rpc-relay-websocket/Chart.yaml
  charts/hedera-json-rpc-relay/Chart.yaml
  docker-compose.yml
  docs/openrpc.json
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: P1, process

#1388 bump version 0.27.0-SNAPSHOT
  charts/hedera-json-rpc-relay-websocket/Chart.yaml
  charts/hedera-json-rpc-relay/Chart.yaml
  docs/openrpc.json
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: P1, process

#1345 Refactor eth_sendRawTransaction to use mirror node for tx hash
  docs/configuration.md
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/helpers.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
  packages/server/tests/acceptance/rateLimiter.spec.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
Labels: enhancement, P1

#1390 Cherry-Pick for 0.26: Refactor eth_sendRawTransaction to use mirror node for tx hash (#1345)
  docs/configuration.md
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/helpers.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
  packages/server/tests/acceptance/rateLimiter.spec.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
Labels: P1, process

#1386 Add optional flag for request id
  docs/configuration.md
  packages/server/src/koaJsonRpc/index.ts
  packages/server/tests/integration/server.spec.ts
Labels: enhancement, P3, wallets

#1397 Fix Snyk vulnerabilities
  .github/workflows/acceptance-workflow.yml
  .github/workflows/dapp.yml
  .github/workflows/dev-tool-workflow.yml
  .github/workflows/postman.yml
  .github/workflows/test.yml
  Dockerfile
  README.md
  dapp-example/package-lock.json
  dapp-example/package.json
  lerna.json
  package-lock.json
  package.json
  tools/truffle-example/package-lock.json
  tools/truffle-example/package.json
Labels: enhancement, process

#1404 Cherry-Pick: 1401 into 0.26
  packages/relay/src/lib/clients/mirrorNodeClient.ts
Labels: bug, P2

#1245 Add clientCache to centralize cache
  packages/relay/src/lib/clients/clientCache.ts
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/relay.ts
  packages/relay/src/lib/services/hapiService/hapiService.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/ethGetBlockBy.spec.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
  packages/relay/tests/lib/openrpc.spec.ts
  packages/relay/tests/lib/precheck.spec.ts
  packages/relay/tests/lib/sdkClient.spec.ts
Labels: enhancement, P2

#1410 Cherry pick 1245 into 0.26 release
  packages/relay/src/lib/clients/clientCache.ts
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/relay.ts
  packages/relay/src/lib/services/hapiService/hapiService.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/ethGetBlockBy.spec.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
  packages/relay/tests/lib/openrpc.spec.ts
  packages/relay/tests/lib/precheck.spec.ts
  packages/relay/tests/lib/sdkClient.spec.ts
Labels: P1, process

#1413 Update default env and some misc fixes
  .env.example
  README.md
  charts/hedera-json-rpc-relay/postman.json
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/eth.ts
  packages/server/tests/integration/server.spec.ts
  packages/server/tests/postman.json
Labels: documentation, enhancement, P3, process

#1411 Cherry Pick 1408 into release 0.26 - Enable chart deploy on github workflow (#1408)
  .github/workflows/release-production.yml
  README.md
Labels: enhancement, P1, process

#1412 upgrade axios and axios-retry dependencies to latests versions
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: P2, dependencies

#1258 903 automate branch tag
  .github/workflows/release-automation.yml
Labels: enhancement, P3, process

#1426 Cherry pick: 903 automate branch tag (#1258)
  .github/workflows/release-automation.yml
Labels: enhancement, P3, process

#1425 bump version 0.26.1
  charts/hedera-json-rpc-relay-websocket/Chart.yaml
  charts/hedera-json-rpc-relay/Chart.yaml
  docker-compose.yml
  docs/openrpc.json
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: enhancement, P1, process

#1427 cherry-pick: upgrade axios and axios-retry dependencies to latests versions (#1412)
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: P2, process
