Repository hiero-ledger/hiero-json-rpc-relay, pull requests merged in 2023-04, with the labels that each got.

#1011 TTL for WS Connections
  .env.example
  docs/configuration.md
  packages/server/tests/acceptance/ws/subscribe.spec.ts
  packages/ws-server/src/webSocketServer.ts
Labels: enhancement, P2, eth_subscribe

#1027 Add `eth_getStorageAt` in openrpc doc
  docs/openrpc.json
Labels: documentation, limechain, P2

#1035 Bump Acceptance Tests network images
  package-lock.json
  package.json
  packages/server/package.json
  packages/server/tests/acceptance/index.spec.ts
  packages/server/tests/helpers/prerequisite.ts
Labels: enhancement

#1037 Connection limits per IP for WebSocket server
  .env.example
  packages/relay/src/index.ts
  packages/relay/src/lib/errors/WebSocketError.ts
  packages/relay/src/lib/poller.ts
  packages/relay/tests/lib/poller.spec.ts
  packages/server/tests/acceptance/ws/subscribe.spec.ts
  packages/ws-server/src/ConnectionLimiter.ts
  packages/ws-server/src/webSocketServer.ts
Labels: enhancement, eth_subscribe

#1043 Extract and Log Contract Revert Reason
  packages/relay/src/formatters.ts
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/errors/SDKClientError.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/formatters.spec.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
Labels: enhancement, limechain, P1

#1029 Feature Flag for eth_subscribe multiple contracts support and acceptance tests
  .env.example
  docs/configuration.md
  packages/server/tests/acceptance/ws/subscribe.spec.ts
  packages/server/tests/helpers/utils.ts
  packages/server/tests/localAcceptance.env
  packages/ws-server/src/webSocketServer.ts
Labels: enhancement, eth_subscribe

#1047 Limit subscriptions for a single connection
  .env.example
  docs/configuration.md
  packages/relay/src/index.ts
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/relay/src/lib/subscriptionController.ts
  packages/relay/tests/lib/subscriptionController.spec.ts
  packages/server/tests/acceptance/ws/subscribe.spec.ts
  packages/ws-server/src/ConnectionLimiter.ts
  packages/ws-server/src/webSocketServer.ts
Labels: enhancement, eth_subscribe

#1064 Adding a configurable TTL cache for get_ethBalance to eth.ts
  .env.example
  docs/configuration.md
  k6/.envexample
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: enhancement, P1

#1070 Cherrypick - Extract and Log Contract Revert Reason (#1043)
  packages/relay/src/formatters.ts
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/errors/SDKClientError.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/formatters.spec.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
Labels: enhancement, P1

#1072 Cherrypick - configurable ttl Cache for current blockNumber (#1063)
  docs/configuration.md
  k6/.envexample
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: enhancement, P1

#1075 RPC API Batch 1 - Acceptance Test - Improvement (#1050)
  packages/server/tests/acceptance/rpc_batch1.spec.ts
Labels: enhancement, process

#1067 Added the abort controller to cancel requests.
  packages/relay/src/lib/clients/mirrorNodeClient.ts
Labels: bug, P1

#1076 Adding a configurable TTL cache for get_ethBalance to eth.ts (#1064)
  .env.example
  docs/configuration.md
  k6/.envexample
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: enhancement, P1

#1077 Added the abort controller to cancel requests. (#1067)
  packages/relay/src/lib/clients/mirrorNodeClient.ts
Labels: bug, P1

#1079 Bump version to 0.21.1
  docker-compose.yml
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: enhancement, P1, process

#1053 Sanity check of ethSubscribe Logs Params
  packages/server/src/validator/objectTypes.ts
  packages/server/tests/acceptance/ws/subscribe.spec.ts
  packages/server/tests/integration/validator.spec.ts
  packages/ws-server/src/webSocketServer.ts
Labels: enhancement, P2, eth_subscribe

#1091 Restrore dropped SDKClient error message
  packages/relay/src/lib/clients/sdkClient.ts
Labels: bug, P1

#1094 Restore dropped SDKClient error message (#1091)
  packages/relay/src/lib/clients/sdkClient.ts
Labels: bug, P1

#1096 Bump 0.21.3
  docker-compose.yml
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: enhancement, P1, process

#1093 Add default seconds to liveness and readiness probes
  helm-chart/templates/deployment.yaml
  helm-chart/values.yaml
Labels: enhancement, P1

#1100 bump version 0.22.0-rc1
  README.md
  docker-compose.yml
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: enhancement, P1, process

#1101 bump version 0.23.0-SNAPSHOT
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: enhancement, P1, process

#1105 Add Contract Call Query Retry Logic
  docs/configuration.md
  helm-chart/templates/configmap.yaml
  helm-chart/value-test.yaml
  helm-chart/values.yaml
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/errors/SDKClientError.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: enhancement, limechain, P1

#1012 Precompile acceptance tests for eth_call with Mirror node
  .github/workflows/acceptance.yml
  package.json
  packages/relay/src/lib/eth.ts
  packages/server/tests/acceptance/htsPrecompile/precompileCalls.spec.ts
  packages/server/tests/acceptance/htsPrecompile/tokenCreate.spec.ts
  packages/server/tests/acceptance/index.spec.ts
  packages/server/tests/clients/servicesClient.ts
  packages/server/tests/contracts/openzeppelin/IERC165.json
  packages/server/tests/contracts/openzeppelin/IERC165.sol
  packages/server/tests/contracts/openzeppelin/IERC20.json
  packages/server/tests/contracts/openzeppelin/IERC20.sol
  packages/server/tests/contracts/openzeppelin/IERC20Metadata.json
  packages/server/tests/contracts/openzeppelin/IERC20Metadata.sol
  packages/server/tests/contracts/openzeppelin/IERC721.json
  packages/server/tests/contracts/openzeppelin/IERC721.sol
  packages/server/tests/contracts/openzeppelin/IERC721Enumerable.json
  packages/server/tests/contracts/openzeppelin/IERC721Enumerable.sol
  packages/server/tests/contracts/openzeppelin/IERC721Metadata.json
  packages/server/tests/contracts/openzeppelin/IERC721Metadata.sol
Labels: enhancement

#1109 Cherry pick PR 1012 into 0.22 release
  .github/workflows/acceptance.yml
  package.json
  packages/relay/src/lib/eth.ts
  packages/server/tests/acceptance/htsPrecompile/precompileCalls.spec.ts
  packages/server/tests/acceptance/htsPrecompile/tokenCreate.spec.ts
  packages/server/tests/acceptance/index.spec.ts
  packages/server/tests/clients/servicesClient.ts
  packages/server/tests/contracts/openzeppelin/IERC165.json
  packages/server/tests/contracts/openzeppelin/IERC165.sol
  packages/server/tests/contracts/openzeppelin/IERC20.json
  packages/server/tests/contracts/openzeppelin/IERC20.sol
  packages/server/tests/contracts/openzeppelin/IERC20Metadata.json
  packages/server/tests/contracts/openzeppelin/IERC20Metadata.sol
  packages/server/tests/contracts/openzeppelin/IERC721.json
  packages/server/tests/contracts/openzeppelin/IERC721.sol
  packages/server/tests/contracts/openzeppelin/IERC721Enumerable.json
  packages/server/tests/contracts/openzeppelin/IERC721Enumerable.sol
  packages/server/tests/contracts/openzeppelin/IERC721Metadata.json
  packages/server/tests/contracts/openzeppelin/IERC721Metadata.sol
Labels: enhancement, P1

#1108 Cherrypick PR-1105 into 0.22 release
  docs/configuration.md
  helm-chart/templates/configmap.yaml
  helm-chart/value-test.yaml
  helm-chart/values.yaml
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/errors/SDKClientError.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: enhancement, P1, process

#1111 Cherrypick PR-1105 into 0.21 release
  docs/configuration.md
  helm-chart/templates/configmap.yaml
  helm-chart/value-test.yaml
  helm-chart/values.yaml
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/errors/SDKClientError.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: enhancement, P1

#1112 Bump 0.21.4
  docker-compose.yml
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: enhancement, P1

#1113 docs: changed HEDERA_NETWORK values to lowercase + sample for testnet
  docs/configuration.md
  docs/examples/.env.mainnet.sample
  docs/examples/.env.previewnet.sample
  docs/examples/.env.testnet.sample
  packages/relay/src/lib/relay.ts
Labels: bug, good first issue, P2, process

#1122 Expand eth_call mirror node consensus retry scenarios
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/server/tests/acceptance/rpc_batch3.spec.ts
Labels: enhancement, P1

#1125 Cherry-pick: Expand eth_call mirror node consensus retry scenarios (#1122)
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/server/tests/acceptance/rpc_batch3.spec.ts
Labels: enhancement, P1

#1126 GA Version 0.22.0
  docker-compose.yml
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: enhancement, P1, process

#1132 Add `eth_call` workaround for mirror-node empty response
  packages/relay/src/lib/errors/MirrorNodeClientError.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: enhancement, limechain, P1

#1133 Cherry-Pick: Add `eth_call` workaround for mirror-node empty response (#1132)
  packages/relay/src/lib/errors/MirrorNodeClientError.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: enhancement, P1

#1124 Acceptance tests for the logs event
  .env.example
  docs/configuration.md
  package-lock.json
  packages/relay/src/lib/poller.ts
  packages/relay/src/lib/subscriptionController.ts
  packages/server/src/validator/objectTypes.ts
  packages/server/tests/acceptance/ws/subscribe.spec.ts
  packages/server/tests/helpers/assertions.ts
  packages/server/tests/helpers/utils.ts
  packages/server/tests/integration/validator.spec.ts
  packages/ws-server/src/webSocketServer.ts
Labels: P2, eth_subscribe

#1115 Removed the unnecessary call to the mirrornode for the account transa…
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/relay/tests/lib/openrpc.spec.ts
Labels: enhancement, P1

#1146 Fix flaky subgraph test
  .github/workflows/subgraph.yml
Labels: bug, limechain, P2, process

#1138 Improve logging in ws-server
  .env.example
  docs/configuration.md
  packages/relay/src/lib/errors/WebSocketError.ts
  packages/relay/src/lib/poller.ts
  packages/relay/src/lib/subscriptionController.ts
  packages/relay/tests/lib/poller.spec.ts
  packages/relay/tests/lib/subscriptionController.spec.ts
  packages/relay/tests/test.env
  packages/server/tests/acceptance/ws/subscribe.spec.ts
  packages/ws-server/src/ConnectionLimiter.ts
  packages/ws-server/src/webSocketServer.ts
Labels: enhancement, eth_subscribe

#1145 refactor: use REQUEST_ID_STRING from constants instead of replicating
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/relay/tests/lib/errors/JsonRpcError.spec.ts
  packages/relay/tests/lib/formatters.spec.ts
Labels: enhancement, P3

#1152 Add logic to manage undefined transaction index
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
Labels: bug, P1

#1153 Cherry pick 1152 and bump
  docker-compose.yml
  docs/openrpc.json
  helm-chart/Chart.yaml
  package-lock.json
  packages/relay/package.json
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth.spec.ts
  packages/server/package.json
  packages/ws-server/package.json
Labels: bug, P1
