Repository hiero-ledger/hiero-json-rpc-relay, pull requests merged in 2024-06, with the labels that each got.

#2553 feat: implemented eth_newFilter to WS server
  packages/relay/src/lib/services/ethService/ethCommonService/ICommonService.ts
  packages/relay/src/lib/services/ethService/ethFilterService/index.ts
  packages/ws-server/src/controllers/index.ts
  packages/ws-server/src/utils/constants.ts
  packages/ws-server/src/utils/utils.ts
  packages/ws-server/tests/acceptance/newFilter.spec.ts
Labels: enhancement

#2562 fix: Adding the node install as now the npm binary is not found.
  .github/workflows/release-automation.yml
Labels: bug

#2564 fix: 2561 release automation cannot find npm
  .github/workflows/release-automation.yml
Labels: bug

#2565 fix: Updated release flows to setup-node and setup make before calling npm ci
  .github/workflows/release-acceptance.yml
  .github/workflows/release-automation.yml
  .github/workflows/release-production.yml
Labels: bug, github_actions

#2554 [Snyk] Upgrade @hashgraph/hedera-local from 2.23.0 to 2.24.0
  package-lock.json
  package.json
Labels: dependencies

#2555 fix: update helm chart release action
  .github/workflows/release-production.yml
  scripts/.bump-version.js
Labels: process

#2569 fix: 2560 include workflow updates in release branch
  .github/workflows/release-acceptance.yml
  .github/workflows/release-automation.yml
  .github/workflows/release-production.yml
Labels: bug

#2566 fix: fixed condition to employ HFS in submitEthereumTransaction()
  packages/relay/src/lib/clients/sdkClient.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
Labels: bug

#2573 chore: cherry pick PR#2566
  packages/relay/src/lib/clients/sdkClient.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
Labels: process

#2577 fix: filtered acceptance tests for release testing
  packages/ws-server/tests/acceptance/batchRequest.spec.ts
  packages/ws-server/tests/acceptance/blockNumber.spec.ts
  packages/ws-server/tests/acceptance/call.spec.ts
  packages/ws-server/tests/acceptance/estimateGas.spec.ts
  packages/ws-server/tests/acceptance/gasPrice.spec.ts
  packages/ws-server/tests/acceptance/getBalance.spec.ts
  packages/ws-server/tests/acceptance/getBlockByHash.spec.ts
  packages/ws-server/tests/acceptance/getBlockByNumber.spec.ts
  packages/ws-server/tests/acceptance/getCode.spec.ts
  packages/ws-server/tests/acceptance/getLogs.spec.ts
  packages/ws-server/tests/acceptance/getStorageAt.spec.ts
  packages/ws-server/tests/acceptance/getTransactionByHash.spec.ts
  packages/ws-server/tests/acceptance/getTransactionCount.spec.ts
  packages/ws-server/tests/acceptance/getTransactionReceipt.spec.ts
  packages/ws-server/tests/acceptance/newFilter.spec.ts
  packages/ws-server/tests/acceptance/rateLimiter.spec.ts
  packages/ws-server/tests/acceptance/sendRawTransaction.spec.ts
  packages/ws-server/tests/acceptance/subscribe.spec.ts
  packages/ws-server/tests/acceptance/subscribeNewHeads.spec.ts
  packages/ws-server/tests/acceptance/validations.spec.ts
  packages/ws-server/tests/acceptance/web3ClientVersion.spec.ts
  packages/ws-server/tests/helper/index.ts
Labels: enhancement

#2582 test: re-included eth_getCode and eth_sendRawTransaction in the release testing flow
  packages/ws-server/tests/acceptance/getCode.spec.ts
  packages/ws-server/tests/acceptance/sendRawTransaction.spec.ts
Labels: bug

#2258 fix: unit tests failing in CI
  packages/relay/src/lib/precheck.ts
  packages/relay/tests/lib/eth/eth-helpers.ts
  packages/relay/tests/lib/precheck.spec.ts
Labels: bug

#2592 fix: Set the correct txn v value.
  packages/relay/src/formatters.ts
Labels: bug

#2591 feat: Added support for OPERATOR_KEY_FORMAT
  docs/configuration.md
  packages/relay/src/lib/services/hapiService/hapiService.ts
  packages/relay/tests/lib/sdkClient.spec.ts
Labels: enhancement

#2590 fix: removed name field in JsonRpcError class
  charts/hedera-json-rpc-relay/postman.json
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/relay/tests/assertions.ts
  packages/relay/tests/lib/errors/JsonRpcError.spec.ts
  packages/relay/tests/lib/eth/eth_call.spec.ts
  packages/relay/tests/lib/eth/eth_common.spec.ts
  packages/relay/tests/lib/eth/eth_estimateGas.spec.ts
  packages/relay/tests/lib/eth/eth_getCode.spec.ts
  packages/relay/tests/lib/eth/eth_getLogs.spec.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
  packages/relay/tests/lib/precheck.spec.ts
  packages/server/src/server.ts
  packages/server/tests/helpers/assertions.ts
  packages/server/tests/integration/server.spec.ts
  packages/server/tests/postman.json
  packages/ws-server/tests/acceptance/sendRawTransaction.spec.ts
  packages/ws-server/tests/acceptance/subscribe.spec.ts
  packages/ws-server/tests/acceptance/subscribeNewHeads.spec.ts
Labels: bug

#2567 fix: Added panels.
  grafana/dashboards/websocketServer/webSocketServer.json
  package-lock.json
  packages/ws-server/src/metrics/wsMetricRegistry.ts
Labels: enhancement

#2598 docs: added transport labels to open-rpc spec
  docs/images/http_label.png
  docs/images/ws_label.png
  docs/openrpc.json
Labels: enhancement

#2556 feat: Hardhat Viem usage example.
  tools/hardhat-viem-example/.env.example
  tools/hardhat-viem-example/.gitignore
  tools/hardhat-viem-example/README.md
  tools/hardhat-viem-example/contracts/Greeter.sol
  tools/hardhat-viem-example/hardhat.config.js
  tools/hardhat-viem-example/package-lock.json
  tools/hardhat-viem-example/package.json
  tools/hardhat-viem-example/scripts/contractCall.js
  tools/hardhat-viem-example/scripts/contractViewCall.js
  tools/hardhat-viem-example/scripts/deployContract.js
  tools/hardhat-viem-example/scripts/showBalance.js
  tools/hardhat-viem-example/test/rpc.js
Labels: enhancement, dev tools

#2584 feat: Golang example
  tools/golang-example/.env.sample
  tools/golang-example/.gitignore
  tools/golang-example/README.md
  tools/golang-example/contracts/Greeter.go
  tools/golang-example/contracts/Greeter.sol
  tools/golang-example/go.mod
  tools/golang-example/go.sum
  tools/golang-example/main.go
  tools/golang-example/main_test.go
  tools/golang-example/utils.go
Labels: enhancement, P3

#2574 build(deps): [Snyk] Upgrade @hashgraph/sdk from 2.44.0 to 2.45.0
  dapp-example/package-lock.json
  dapp-example/package.json
Labels: dependencies

#2606 feat: add release.yml for auto-generating release notes
  .github/release.yaml
Labels: enhancement

#2608 build(deps): Bump versions for v0.51.0-SNAPSHOT
  charts/hedera-json-rpc-relay-websocket/Chart.yaml
  charts/hedera-json-rpc-relay/Chart.yaml
  charts/hedera-json-rpc/Chart.yaml
  docs/openrpc.json
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: enhancement, process

#2609 build(deps): [Snyk] Security upgrade ethers from 5.7.2 to 6.0.0
  k6/package-lock.json
  k6/package.json
Labels: dependencies

#2611 fix: reworked gas comparison logic
  packages/server/tests/acceptance/rpc_batch1.spec.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
  packages/server/tests/helpers/assertions.ts
Labels: bug

#2612 build(deps): [Snyk] Security upgrade ethers from 6.0.0 to 6.13.1
  k6/package.json
Labels: dependencies

#2616 fix: fixed unexpected returns for eth_getLog requests with zero address
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/tests/lib/eth/eth_getLogs.spec.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
Labels: bug

#2618 chore: cherry pick PR#2616
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/tests/lib/eth/eth_getLogs.spec.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
Labels: process

#2558 build(deps): [Snyk] Upgrade @hashgraph/hedera-local from 2.23.0 to 2.26.2
  package-lock.json
  package.json
  packages/server/tests/acceptance/rpc_batch2.spec.ts
Labels: dependencies

#2621 fix: Upgrade to node 20.
  .github/workflows/acceptance-workflow.yml
  .github/workflows/dapp.yml
  .github/workflows/dev-tool-workflow.yml
  .github/workflows/postman.yml
  .github/workflows/pr-label-milestone-check.yml
  .github/workflows/release-acceptance.yml
  .github/workflows/release-automation.yml
  .github/workflows/release-production.yml
  .github/workflows/subgraph.yml
  .github/workflows/test.yml
  Dockerfile
  README.md
Labels: dependencies

#2623 fix: String preceding zeros from signature key values.
  packages/relay/src/formatters.ts
  packages/relay/tests/lib/formatters.spec.ts
Labels: bug

#2622 build(deps): [Snyk] Upgrade ethers from 6.0.0 to 6.13.0
  k6/package-lock.json
  k6/package.json
Labels: dependencies

#2617 feat: Rework how tooling tests and dapp are starting local-node
  .github/workflows/dapp.yml
  .github/workflows/dev-tool-workflow.yml
  .github/workflows/postman.yml
  package.json
  packages/server/package.json
  packages/server/tests/helpers/nodeCheck.ts
  packages/server/tests/helpers/prerequisite.ts
  packages/ws-server/package.json
Labels: enhancement, limechain

#2628 fix: debug_traceTransaction not working when we don't pass tracerConfig
  packages/server/src/server.ts
Labels: bug, limechain

#2625 fix: reduced the SDK usage in batch 3 to stablize the batch
  packages/server/tests/acceptance/rpc_batch3.spec.ts
Labels: enhancement

#2586 feat: Golang JSON RPC methods usage example.
  tools/golang-json-rpc-tests/.env.sample
  tools/golang-json-rpc-tests/README.md
  tools/golang-json-rpc-tests/contracts/SampleContract.sol
  tools/golang-json-rpc-tests/contracts/input.bin
  tools/golang-json-rpc-tests/go.mod
  tools/golang-json-rpc-tests/go.sum
  tools/golang-json-rpc-tests/main.go
Labels: enhancement, P3

#2634 fix: Added HBar rate limiter to createFile
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/sdkClient.spec.ts
Labels: bug

#2636 fix: Added HBar rate limiter to createFile (#2634)
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/sdkClient.spec.ts
Labels: process

#2624 build(deps): [Snyk] Security upgrade ethers from 6.13.0 to 6.13.1
  k6/package-lock.json
  k6/package.json
Labels: dependencies
