Repository hiero-ledger/hiero-json-rpc-relay, pull requests merged in 2024-02, with the labels that each got.

#2075 [Snyk] Upgrade @hashgraph/sdk from 2.39.0 to 2.40.0
  dapp-example/package-lock.json
  dapp-example/package.json
Labels: dependencies

#2076 [Snyk] Upgrade pnpm from 8.14.0 to 8.14.1
  packages/ws-server/package.json
Labels: dependencies

#2088 fix: nonce out of sync, temporary workaround while network node 0.47.0 is released
  packages/server/tests/acceptance/rpc_batch3.spec.ts
Labels: bug

#2077 [Snyk] Upgrade @hashgraph/sdk from 2.39.0 to 2.40.0
  package-lock.json
  packages/relay/package.json
Labels: dependencies

#2085 fix: Status Code on Relay Response Logs
  packages/server/src/server.ts
Labels: bug

#2090 fix: Status Code on Relay Response Logs (#2085)
  packages/server/src/server.ts
  packages/server/tests/acceptance/rpc_batch3.spec.ts
Labels: bug

#2095 fix: Productize increase of Gas Limit to 50M and internally keep it capped to the 15M limit
  docs/configuration.md
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth/eth_call.spec.ts
Labels: bug

#2093 [Snyk] Upgrade @graphprotocol/graph-cli from 0.65.0 to 0.67.1
  tools/subgraph-example/subgraph/package.json
Labels: dependencies

#2094 [Snyk] Upgrade @mui/material from 5.15.4 to 5.15.5
  dapp-example/package-lock.json
  dapp-example/package.json
Labels: dependencies

#2098 [Snyk] Upgrade @mui/material from 5.15.5 to 5.15.6
  dapp-example/package-lock.json
  dapp-example/package.json
Labels: dependencies

#2099 [Snyk] Upgrade pnpm from 8.14.1 to 8.14.2
  package-lock.json
  packages/ws-server/package.json
Labels: dependencies

#2100 [Snyk] Upgrade dotenv from 16.3.1 to 16.3.2
  tools/truffle-example/package-lock.json
  tools/truffle-example/package.json
Labels: dependencies

#2101 [Snyk] Upgrade @graphprotocol/graph-cli from 0.67.1 to 0.67.2
  tools/subgraph-example/subgraph/package.json
Labels: dependencies

#2103 [Snyk] Upgrade dotenv from 16.3.2 to 16.4.1
  tools/truffle-example/package-lock.json
  tools/truffle-example/package.json
Labels: dependencies

#2104 [Snyk] Upgrade dotenv from 16.3.2 to 16.4.1
  tools/web3js-example/package-lock.json
  tools/web3js-example/package.json
Labels: dependencies

#2109 docs: Update Spec API Docs
  docs/openrpc.json
Labels: documentation

#2110 [Snyk] Upgrade pnpm from 8.14.2 to 8.14.3
  package-lock.json
  packages/ws-server/package.json
Labels: dependencies

#2113 fix: Productization of MIRROR_NODE_CONTRACT_RESULTS_LOGS_PG_MAX=200
  docs/configuration.md
  packages/relay/src/lib/clients/mirrorNodeClient.ts
Labels: bug

#2118 [Snyk] Security upgrade node from 18.18.2-bullseye-slim to 18.19.0-bullseye-slim
  Dockerfile
Labels: dependencies

#2120 [Snyk] Security upgrade node from 18.18.2-bullseye-slim to 18.19.1-bullseye-slim
  Dockerfile
Labels: dependencies

#2097 chore: update local node
  package-lock.json
  package.json
  packages/server/tests/helpers/prerequisite.ts
Labels: limechain

#2122 [Snyk] Upgrade pnpm from 8.14.3 to 8.15.1
  packages/ws-server/package.json
Labels: dependencies

#2125 fix: add support for `eth_call` Historical Blocks
  packages/relay/src/index.ts
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/relay/src/lib/eth.ts
  packages/server/tests/acceptance/rpc_batch3.spec.ts
Labels: bug, P1

#2129 feat: Adding manual testing workflow
  .github/workflows/acceptance-workflow.yml
  .github/workflows/manual-testing.yml
Labels: enhancement

#2137 fix: Network issue with docker/setup-buildx-action@v2 plugin on release integration GH WF
  .github/workflows/release-integration.yml
  .github/workflows/release-production.yml
Labels: P1, process

#2140 fix: reverting node:18.18.2-bullseye-slim to unblock release process
  Dockerfile
Labels: bug, process

#2141 adding logs for eth_call size and gas
  packages/relay/src/lib/eth.ts
Labels: enhancement, P1

#2143 chore: cherry-pick #2141: adding logs for eth_call size and gas (#2141)
  packages/relay/src/lib/eth.ts
Labels: enhancement

#2153 [Snyk] Upgrade @hashgraph/sdk from 2.40.0 to 2.41.0
  packages/relay/package.json
Labels: dependencies

#2154 [Snyk] Upgrade lerna from 8.0.2 to 8.1.1
  package-lock.json
  package.json
Labels: dependencies

#2157 chore: update hardhat version in subgraph example
  tools/subgraph-example/package-lock.json
  tools/subgraph-example/package.json
Labels: bug, dependencies

#2155 [Snyk] Upgrade @graphprotocol/graph-cli from 0.67.3 to 0.67.4
  tools/subgraph-example/subgraph/package.json
Labels: dependencies

#2156 [Snyk] Upgrade @hashgraph/sdk from 2.40.0 to 2.41.0
  dapp-example/package-lock.json
  dapp-example/package.json
Labels: dependencies

#2158 [Snyk] Upgrade redis from 4.6.12 to 4.6.13
  package-lock.json
  package.json
Labels: dependencies

#2165 [Snyk] Upgrade @mui/material from 5.15.7 to 5.15.9
  dapp-example/package-lock.json
  dapp-example/package.json
Labels: dependencies
