Repository hiero-ledger/hiero-json-rpc-relay, pull requests merged in 2024-07, with the labels that each got.

#2633 fix: net_version now reads chainId from config and return decimal value
  charts/hedera-json-rpc-relay/postman.json
  docs/openrpc.json
  packages/relay/src/lib/net.ts
  packages/relay/src/lib/relay.ts
  packages/relay/tests/lib/net.spec.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
  packages/server/tests/postman.json
Labels: enhancement

#2607 build(deps): [Snyk] Security upgrade ethers from 5.7.2 to 6.0.0
  dapp-example/localDappCI.env
  dapp-example/package-lock.json
  dapp-example/package.json
  dapp-example/public/index.html
  dapp-example/src/App.js
  dapp-example/src/components/ActivateHollowAccountForm.js
  dapp-example/src/components/AssociateHTSTokensForm.js
  dapp-example/src/components/ContractInteractions.js
  dapp-example/src/hooks/useHederaSdk.js
  dapp-example/synpress.js
  dapp-example/tests/e2e/bootstrap.js
  dapp-example/tests/e2e/specs/index.spec.js
Labels: dependencies

#2637 [Snyk] Upgrade web3 from 4.8.0 to 4.9.0
  tools/web3js-example/package-lock.json
  tools/web3js-example/package.json
Labels: dependencies

#2663 fix: issue when trying to perform transaction
  package-lock.json
  package.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: P1

#2668 fix: Adds usage of internal cache for getFilterChanges
  packages/relay/src/lib/services/cacheService/cacheService.ts
  packages/relay/src/lib/services/ethService/ethFilterService/index.ts
Labels: bug

#2670 fix: Adds usage of internal cache for getFilterChanges (#2668)
  packages/relay/src/lib/services/cacheService/cacheService.ts
  packages/relay/src/lib/services/ethService/ethFilterService/index.ts
Labels: bug

#2669 fix: issue when trying to perform transaction (#2663)
  package-lock.json
  package.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: bug

#2672 fix: Added metrics around the HBar rate limiter to better track the (…
  packages/relay/src/lib/hbarlimiter/index.ts
Labels: enhancement

#2650 fix: eth_getBlockTransactionCountByNumber is not supported in wss
  tools/golang-json-rpc-tests/main.go
Labels: bug

#2409 fix: estimate_gas doesn't reflect changes in mirror-node
  packages/relay/src/formatters.ts
  packages/relay/src/index.ts
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/precheck.ts
  packages/relay/tests/lib/eth/eth_call.spec.ts
  packages/relay/tests/lib/eth/eth_estimateGas.spec.ts
  packages/relay/tests/lib/eth/eth_getCode.spec.ts
  packages/relay/tests/lib/formatters.spec.ts
  packages/relay/tests/lib/precheck.spec.ts
  packages/relay/tests/lib/services/debugService/debug.spec.ts
  packages/ws-server/src/metrics/wsMetricRegistry.ts
Labels: bug, limechain

#2688 fix: gasprice of transactions denoted in tinybars
  packages/relay/src/formatters.ts
  packages/relay/tests/lib/eth/eth-config.ts
Labels: bug, limechain

#2640 test: waffle tool example
  tools/waffle-example/.env.example
  tools/waffle-example/.gitignore
  tools/waffle-example/.mocharc.json
  tools/waffle-example/README.md
  tools/waffle-example/contracts/SampleContract.sol
  tools/waffle-example/package-lock.json
  tools/waffle-example/package.json
  tools/waffle-example/test/samplecontract.test.mjs
  tools/waffle-example/waffle.json
Labels: enhancement

#2601 chore: Increase batch request limit
  package-lock.json
  package.json
  packages/server/src/koaJsonRpc/index.ts
  packages/server/src/koaJsonRpc/lib/IJsonRpcRequest.ts
  packages/server/src/koaJsonRpc/lib/methodConfiguration.ts
  packages/server/src/koaJsonRpc/lib/utils.ts
  packages/server/src/rateLimit/index.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
  packages/server/tests/acceptance/rpc_batch3.spec.ts
  packages/server/tests/clients/relayClient.ts
  packages/server/tests/clients/servicesClient.ts
  packages/server/tests/helpers/assertions.ts
  packages/server/tsconfig.json
  packages/ws-server/src/webSocketServer.ts
  packages/ws-server/tests/acceptance/rateLimiter.spec.ts
Labels: limechain

#2647 feat: allowed eth_call to accept null/empty tx.to to simulate deploying smart contracts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth/eth-config.ts
  packages/relay/tests/lib/eth/eth_call.spec.ts
  packages/relay/tests/lib/eth/eth_sendRawTransaction.spec.ts
  packages/relay/tests/lib/formatters.spec.ts
  packages/server/tests/acceptance/rpc_batch3.spec.ts
Labels: enhancement

#2660 build(deps): [Snyk] Security upgrade mocha from 9.2.2 to 10.6.0
  package-lock.json
  packages/server/package.json
  packages/server/tests/integration/validator.spec.ts
Labels: dependencies

#2661 build(deps): [Snyk] Upgrade co-body from 6.1.0 to 6.2.0
  package-lock.json
  packages/server/package.json
Labels: dependencies

#2692 feat: add a tx gasPrice Buffer to reduce INSUFFICIENT_TX_FEE cases
  charts/hedera-json-rpc-relay/value-test.yaml
  charts/hedera-json-rpc-relay/values.yaml
  docs/configuration.md
  packages/relay/src/lib/eth.ts
  packages/relay/src/utils.ts
  packages/relay/tests/lib/eth/eth_gasPrice.spec.ts
  packages/relay/tests/lib/utils.spec.ts
Labels: enhancement

#2658 feat: Checking in the updated grafana dashboard. It now includes additional HBar spend visuals.
  charts/hedera-json-rpc/dashboards/hedera-json-rpc-relay-http-server.json
  charts/hedera-json-rpc/dashboards/webSocketServer.json
Labels: enhancement

#2698 fix: Hbar usage tracking when transaction is larger than FILE_APPEND_CHUNK_SIZE
  package.json
  packages/relay/src/lib/clients/sdkClient.ts
  packages/server/tests/acceptance/index.spec.ts
  packages/server/tests/acceptance/rateLimiter.spec.ts
  packages/server/tests/clients/metricsClient.ts
  packages/server/tests/helpers/constants.ts
  packages/server/tests/localAcceptance.env
  packages/ws-server/tests/acceptance/sendRawTransaction.spec.ts
Labels: bug, enhancement

#2715 Cherry pick PR #2698
  package.json
  packages/relay/src/lib/clients/sdkClient.ts
  packages/server/tests/acceptance/index.spec.ts
  packages/server/tests/acceptance/rateLimiter.spec.ts
  packages/server/tests/clients/metricsClient.ts
  packages/server/tests/helpers/constants.ts
  packages/server/tests/localAcceptance.env
  packages/ws-server/tests/acceptance/sendRawTransaction.spec.ts
Labels: process

#2714 fix: captured transactionFee in metrics and HBAR limiter class in executeTransaction and deleteFile
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/eth.ts
  packages/server/tests/acceptance/rateLimiter.spec.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
Labels: bug

#2730 chore: cherry picked PR#2698
  package.json
  packages/relay/src/lib/clients/sdkClient.ts
  packages/server/tests/acceptance/index.spec.ts
  packages/server/tests/acceptance/rateLimiter.spec.ts
  packages/server/tests/clients/metricsClient.ts
  packages/server/tests/helpers/constants.ts
  packages/server/tests/localAcceptance.env
  packages/ws-server/tests/acceptance/sendRawTransaction.spec.ts
Labels: process

#2731 chore: cherry picked PR#2730
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/eth.ts
  packages/server/tests/acceptance/rateLimiter.spec.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
Labels: process

#2720 feat: add real `logsBloom` where available
  packages/relay/src/lib/eth.ts
  packages/relay/tests/helpers.ts
  packages/relay/tests/lib/eth/eth_getBlockByHash.spec.ts
  packages/relay/tests/lib/eth/eth_getBlockByNumber.spec.ts
  packages/server/tests/helpers/assertions.ts
Labels: enhancement, dev tools

#2733 chore: cherry picked PR#2714
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/eth.ts
  packages/server/tests/acceptance/rateLimiter.spec.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
Labels: process

#2734 fix: The relay metrics are not exposed in the websocket server
  packages/ws-server/src/webSocketServer.ts
Labels: bug, limechain, P1

#2690 fix: Updated the account from the 0.0.2 account to an account from th…
  .github/workflows/test.yml
  packages/relay/src/lib/services/hapiService/hapiService.ts
  packages/relay/src/utils.ts
  packages/relay/tests/lib/sdkClient.spec.ts
  packages/server/tests/clients/servicesClient.ts
  packages/server/tests/localAcceptance.env
  packages/ws-server/tests/acceptance/sendRawTransaction.spec.ts
Labels: bug

#2751 feat: added preemtiveCheck for HBAR ratelimit
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/relay/src/lib/hbarlimiter/index.ts
  packages/relay/tests/lib/hbarLimiter.spec.ts
Labels: enhancement

#2752 chore: cherry picked PR#2751
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/relay/src/lib/hbarlimiter/index.ts
  packages/relay/tests/lib/hbarLimiter.spec.ts
Labels: process

#2697 test: add additional hbar limiter tests
  .github/workflows/acceptance.yml
  .github/workflows/manual-testing.yml
  package.json
  packages/relay/src/lib/clients/sdkClient.ts
  packages/server/tests/acceptance/hbarLimiter.spec.ts
  packages/server/tests/acceptance/rateLimiter.spec.ts
  packages/server/tests/contracts/hbarLimiterContracts/largeSizeContract.json
  packages/server/tests/contracts/hbarLimiterContracts/largeSizeContract.sol
  packages/server/tests/contracts/hbarLimiterContracts/mediumSizeContract.json
  packages/server/tests/contracts/hbarLimiterContracts/meduimSizeContract.sol
Labels: enhancement

#2742 fix: reorganized executeTransaction and executeTransactionRecord to avoid capturing metrics twice
  packages/relay/src/lib/clients/sdkClient.ts
Labels: bug, P1

#2753 test: added E2E test for preemtive rate limit
  packages/server/tests/acceptance/hbarLimiter.spec.ts
Labels: process

#2756 test: expand integration tests for SDK client
  package-lock.json
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/tests/lib/sdkClient.spec.ts
  packages/relay/tsconfig.json
  packages/server/package.json
Labels: enhancement, P1

#2762 feat: search contract logs only by transaction hash
  package-lock.json
  package.json
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth/eth-config.ts
  packages/relay/tests/lib/eth/eth_getTransactionByHash.spec.ts
  packages/relay/tests/lib/eth/eth_getTransactionReceipt.spec.ts
  packages/server/package.json
  packages/ws-server/package.json
Labels: enhancement

#2768 feat: deprecate `ETH_POPULATE_SYNTHETIC_CONTRACT_RESULTS` env
  docs/configuration.md
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth/eth_getTransactionByHash.spec.ts
  packages/relay/tests/lib/ethGetBlockBy.spec.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
  packages/server/tests/localAcceptance.env
Labels: enhancement

#2749 feat: reused executetransaction for methods in sdkclient and improved logging
  packages/relay/src/formatters.ts
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/tests/lib/formatters.spec.ts
  packages/relay/tests/lib/sdkClient.spec.ts
Labels: enhancement

#2776 feat: reused executetransaction for methods in sdkclient and improved…
  packages/relay/src/formatters.ts
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/tests/lib/formatters.spec.ts
  packages/relay/tests/lib/sdkClient.spec.ts
Labels: bug
