Repository hiero-ledger/hiero-json-rpc-relay, pull requests merged in 2024-08, with the labels that each got.

#2771 chore: bump memory leak threshold
  packages/server/tests/helpers/utils.ts
Labels: P1, process, github_actions

#2755 fix: reduce hbar limit only by operator fees
  packages/relay/src/formatters.ts
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/tests/helpers.ts
  packages/relay/tests/lib/eth/eth-config.ts
  packages/relay/tests/lib/eth/eth_getBlockByHash.spec.ts
  packages/relay/tests/lib/sdkClient.spec.ts
  packages/server/tests/acceptance/hbarLimiter.spec.ts
  packages/server/tests/helpers/assertions.ts
Labels: enhancement

#2781 2755 operator vs txn fees
  packages/relay/src/formatters.ts
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/tests/helpers.ts
  packages/relay/tests/lib/eth/eth-config.ts
  packages/relay/tests/lib/eth/eth_getBlockByHash.spec.ts
  packages/relay/tests/lib/sdkClient.spec.ts
  packages/server/tests/acceptance/hbarLimiter.spec.ts
  packages/server/tests/helpers/assertions.ts
Labels: bug

#2784 fix: populate synthetic transactions on `getBlock...` routes
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/ethGetBlockBy.spec.ts
Labels: bug

#2786 fix: populate synthetic transactions on `getBlock...` routes (#2784)
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/ethGetBlockBy.spec.ts
Labels: bug

#2764 fix: Code coverage report is not being uploaded
  .github/scripts/codecov-upload.sh
  .github/workflows/acceptance-workflow.yml
  .github/workflows/test.yml
  codecov.yml
  package-lock.json
  package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: bug, enhancement, limechain

#2682 fix: Adds null check for param in validation
  package-lock.json
  package.json
  packages/server/src/validator/methods.ts
  packages/server/src/validator/utils.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
  packages/server/tests/integration/server.spec.ts
  packages/server/tests/integration/validator.spec.ts
Labels: bug

#2793 chore: update local-node and sdk
  dapp-example/package-lock.json
  dapp-example/package.json
  package-lock.json
  package.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: enhancement

#2789 chore: migrate gh-docker-logs to step-security maintained version
  .github/workflows/dapp.yml
Labels: github_actions

#2795 chore: Remove and Refactor redundant logic in `eth_sendRawTransaction`
  packages/relay/src/formatters.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth/eth_sendRawTransaction.spec.ts
  packages/relay/tests/lib/formatters.spec.ts
Labels: Technical Debt

#2785 feat: calculate `logsBloom` for synthetic transactions
  packages/relay/src/lib/eth.ts
  packages/relay/src/logsBloomUtils.ts
  packages/relay/tests/lib/logsBloomUtils.spec.ts
Labels: enhancement

#2782 feat: added an option for retrieving transaction records from either the Mirror Node or the Consensus Node.
  docs/configuration.md
  packages/relay/src/formatters.ts
  packages/relay/src/index.ts
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/services/transactionService/transactionService.ts
  packages/relay/src/lib/types/IMirrorNode.ts
  packages/relay/tests/lib/eth/eth_estimateGas.spec.ts
  packages/relay/tests/lib/sdkClient.spec.ts
  packages/relay/tests/lib/services/transactionService/transactionService.spec.ts
  packages/server/tests/acceptance/hbarLimiter.spec.ts
Labels: enhancement

#2767 feat: Added request panels to the websocket dashboard.
  charts/hedera-json-rpc/dashboards/webSocketServer.json
Labels: enhancement

#2679 feat: add Golang tests to workflow
  .github/workflows/dev-tool-test.yml
  .github/workflows/dev-tool-workflow.yml
  tools/golang-json-rpc-tests/.env.example
  tools/golang-json-rpc-tests/.env.sample
  tools/golang-json-rpc-tests/README.md
  tools/golang-json-rpc-tests/main.go
Labels: enhancement, ArianeLabs

#2817 fix: stabilized sdkClient test by bumping total timeout to 30000ms
  packages/relay/tests/lib/sdkClient.spec.ts
  packages/relay/tests/lib/services/transactionService/transactionService.spec.ts
Labels: enhancement

#2797 [Snyk] Upgrade @graphprotocol/graph-cli from 0.69.0 to 0.78.0
  tools/subgraph-example/subgraph/package.json
Labels: dependencies

#2796 build(deps): [Snyk] Upgrade chai-exclude from 2.1.0 to 2.1.1
  package-lock.json
  package.json
Labels: dependencies

#2787 chore: return empty trie root where applicable
  package-lock.json
  package.json
  packages/relay/src/formatters.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/assertions.ts
  packages/relay/tests/lib/eth/eth-config.ts
  packages/relay/tests/lib/eth/eth_getBlockByNumber.spec.ts
  packages/relay/tests/lib/formatters.spec.ts
  packages/server/tests/helpers/assertions.ts
Labels: enhancement, dev tools

#2818 fix: added logging to HBARLimit class
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/hbarlimiter/index.ts
Labels: enhancement

#2822 fix: captured and added FileInfo query costs to metrics and hbar ratelimit class
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/tests/lib/sdkClient.spec.ts
Labels: enhancement

#2832 feat: added a solution to verify if a caller is whitelisted against the HBAR rate limiter
  docs/configuration.md
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/hbarlimiter/index.ts
  packages/relay/tests/lib/hbarLimiter.spec.ts
  packages/relay/tests/lib/sdkClient.spec.ts
Labels: enhancement

#2833 chore: cherry pick #2832
  docs/configuration.md
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/hbarlimiter/index.ts
  packages/relay/tests/lib/hbarLimiter.spec.ts
  packages/relay/tests/lib/sdkClient.spec.ts
Labels: process

#2835 chore: remove unnecessary heapdump dependency
  package-lock.json
  packages/server/package.json
  packages/server/tests/helpers/utils.ts
Labels: dependencies

#2825 build(deps): [Snyk] Upgrade @graphprotocol/graph-cli from 0.78.0 to 0.79.0
  tools/subgraph-example/subgraph/package.json
Labels: dependencies

#2826 build(deps): [Snyk] Upgrade @graphprotocol/graph-ts from 0.34.0 to 0.35.1
  tools/subgraph-example/subgraph/package.json
Labels: dependencies

#2841 fix: error thrown when setting value in redis cache
  packages/relay/src/lib/clients/cache/redisCache.ts
  packages/relay/tests/lib/clients/redisCache.spec.ts
Labels: bug

#2845 chore: cherry picked PR#2834
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/relay/src/lib/errors/MirrorNodeClientError.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/errors/JsonRpcError.spec.ts
  packages/relay/tests/lib/eth/eth_estimateGas.spec.ts
  packages/relay/tests/lib/formatters.spec.ts
Labels: process

#2842 chore: bump sdk version to 2.50.0-beta.3
  dapp-example/package-lock.json
  dapp-example/package.json
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
  packages/server/tests/clients/servicesClient.ts
  packages/server/tests/localAcceptance.env
  packages/ws-server/package.json
Labels: dependencies

#2859 chore: cherry picked #2854
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth/eth_getBlockByHash.spec.ts
  packages/relay/tests/lib/eth/eth_getBlockByNumber.spec.ts
Labels: process

#2843 fix: Bug due to validations of `eth_call`
  packages/server/src/types/validator/objectTypes.ts
  packages/server/src/validator/objectTypes.ts
  packages/server/tests/integration/validator.spec.ts
Labels: bug

#2840 feat: remove unnecessary empty `Trie` initialization
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/assertions.ts
  packages/relay/tests/lib/eth/eth-config.ts
  packages/relay/tests/lib/eth/eth_getBlockByNumber.spec.ts
  packages/server/tests/helpers/assertions.ts
Labels: enhancement

#2856 build(deps): [Snyk] Upgrade web3 from 4.10.0 to 4.11.1
  tools/web3js-example/package-lock.json
  tools/web3js-example/package.json
Labels: dependencies

#2864 feat: Adds design doc for hbar limiter service
  docs/design/hbar-limiter.md
Labels: enhancement

#2871 [Snyk] Security upgrade @hashgraph/sdk from 2.50.0-beta.3 to 2.50.0
  dapp-example/package-lock.json
  dapp-example/package.json
Labels: dependencies

#2877 fix: Bump timeout up due to many test runs timing out in the current CI
  .github/workflows/dapp.yml
Labels: enhancement

#2861 feat: redis cache should fallback to internal in case of error
  packages/relay/src/lib/services/cacheService/cacheService.ts
  packages/relay/tests/lib/services/cacheService/cacheService.spec.ts
  packages/server/tests/acceptance/cacheService.spec.ts
Labels: enhancement

#2798 feat: calculate actual `receiptsRoot` when possible
  package-lock.json
  package.json
  packages/relay/src/lib/eth.ts
  packages/relay/src/receiptsRootUtils.ts
  packages/relay/tests/assertions.ts
  packages/relay/tests/lib/eth/eth-config.ts
  packages/relay/tests/lib/eth/eth_getBlockByHash.spec.ts
  packages/relay/tests/lib/eth/eth_getBlockByNumber.spec.ts
  packages/relay/tests/lib/receiptsRootUtils.spec.ts
  packages/server/tests/helpers/assertions.ts
Labels: enhancement

#2649 fix: Improve compatibility with standard ethereum tooling
  .github/workflows/acceptance-public.yml
  .github/workflows/acceptance.yml
  .github/workflows/conformity-workflow.yml
  .github/workflows/manual-testing.yml
  package-lock.json
  package.json
  packages/server/package.json
  packages/server/src/validator/constants.ts
  packages/server/src/validator/methods.ts
  packages/server/src/validator/types.ts
  packages/server/tests/acceptance/conformityTests.spec.ts
  packages/server/tests/integration/server.spec.ts
  packages/server/tests/integration/validator.spec.ts
  packages/ws-server/tests/acceptance/subscribe.spec.ts
Labels: enhancement

#2862 [Snyk] Upgrade @hashgraph/hedera-local from 2.25.2 to 2.28.1
  tools/hardhat-viem-example/package-lock.json
  tools/hardhat-viem-example/package.json
Labels: dependencies

#2880 build(deps): [Snyk] Upgrade @graphprotocol/graph-cli from 0.79.2 to 0.80.0
  tools/subgraph-example/subgraph/package.json
Labels: dependencies

#2878 chore: cherry picked #2842
  dapp-example/package-lock.json
  dapp-example/package.json
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
  packages/server/tests/clients/servicesClient.ts
  packages/server/tests/localAcceptance.env
  packages/ws-server/package.json
Labels: process

#2879 chore: cherry picked #2871
  dapp-example/package-lock.json
  dapp-example/package.json
  package-lock.json
Labels: process

#2887 feat: Implement `shouldLimit` method of `HbarLimitService`
  packages/relay/src/lib/services/hbarLimitService/IHbarLimitService.ts
  packages/relay/src/lib/services/hbarLimitService/index.ts
  packages/relay/tests/lib/services/hbarLimitService/hbarLimitService.spec.ts
Labels: enhancement, P1

#2886 build(deps): [Snyk] Upgrade @emotion/styled from 11.11.5 to 11.13.0
  dapp-example/package-lock.json
  dapp-example/package.json
Labels: dependencies

#2885 build(deps): [Snyk] Upgrade @mui/material from 5.15.21 to 5.16.6
  dapp-example/package-lock.json
  dapp-example/package.json
Labels: dependencies

#2884 docs: Add class diagram for the database schema of the hbar limiter redesign
  docs/design/hbar-limiter.md
Labels: documentation, design

#2893 buiild(deps): [Snyk] Upgrade @hashgraph/hedera-local from 2.28.1 to 2.29.0
  tools/hardhat-viem-example/package-lock.json
  tools/hardhat-viem-example/package.json
Labels: dependencies

#2704 fix: fixtures usage example
  tools/waffle-example/README.md
  tools/waffle-example/test/samplecontract.test.mjs
Labels: enhancement, ArianeLabs

#2615 ci: Update actions/download-artifact and actions/upload-artifact to v4
  .github/workflows/acceptance-public.yml
  .github/workflows/acceptance-workflow.yml
  .github/workflows/acceptance.yml
  .github/workflows/dapp.yml
  .github/workflows/manual-testing.yml
  .github/workflows/release-acceptance.yml
  .github/workflows/release-production.yml
Labels: enhancement, github_actions

#2889 feat: create second batch of additional conformity tests
  packages/server/tests/acceptance/conformityTests.spec.ts
Labels: enhancement

#2900 build(deps): [Snyk] Upgrade @emotion/react from 11.11.4 to 11.13.0
  dapp-example/package-lock.json
  dapp-example/package.json
Labels: dependencies

#2860 fix: The relay relies on fallback gas estimations instead of properly sending requests to mirror node
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/types/IMirrorNode.ts
  packages/relay/tests/lib/eth/eth_call.spec.ts
  packages/relay/tests/lib/eth/eth_estimateGas.spec.ts
Labels: bug
