Repository hiero-ledger/hiero-json-rpc-relay, pull requests merged in 2024-05, with the labels that each got.

#2445 chore: cherry-picked PR#2444
  packages/ws-server/src/controllers/eth_blockNumber.ts
  packages/ws-server/src/controllers/eth_call.ts
  packages/ws-server/src/controllers/eth_estimateGas.ts
  packages/ws-server/src/controllers/eth_gasPrice.ts
  packages/ws-server/src/controllers/eth_getBalance.ts
  packages/ws-server/src/controllers/eth_getBlockByHash.ts
  packages/ws-server/src/controllers/eth_getBlockByNumber.ts
  packages/ws-server/src/controllers/eth_getCode.ts
  packages/ws-server/src/controllers/eth_getLogs.ts
  packages/ws-server/src/controllers/eth_getStorageAt.ts
  packages/ws-server/src/controllers/eth_getTransactionByHash.ts
  packages/ws-server/src/controllers/eth_getTransactionCount.ts
  packages/ws-server/src/controllers/eth_getTransactionReceipt.ts
  packages/ws-server/src/controllers/eth_sendRawTransaction.ts
  packages/ws-server/src/controllers/helpers.ts
  packages/ws-server/src/utils/utils.ts
  packages/ws-server/tests/helper/index.ts
Labels: process

#2442 chore: added a debug level log to expose contract call response for eth_call requests (#2441)
  packages/relay/src/lib/eth.ts
Labels: enhancement

#2449 fix: fixed setting WS_NEW_HEADS_ENABLED true as default logic at Relay level
  packages/relay/src/lib/poller.ts
  packages/ws-server/src/controllers/eth_subscribe.ts
  packages/ws-server/tests/acceptance/subscribeNewHeads.spec.ts
Labels: bug

#2450 chore: cherry-picked #2449
  packages/relay/src/lib/poller.ts
  packages/ws-server/src/controllers/eth_subscribe.ts
  packages/ws-server/tests/acceptance/subscribeNewHeads.spec.ts
Labels: process

#2456 feat: added CI build test
  .github/workflows/image-build.yml
Labels: enhancement, P3

#2460 fix: Test fix for nonce values on networks other thant local node.
  packages/server/tests/acceptance/rpc_batch1.spec.ts
Labels: bug

#2424 chore: [Snyk] Upgrade @mui/material from 5.15.14 to 5.15.15
  dapp-example/package-lock.json
  dapp-example/package.json
Labels: dependencies

#2425 chore: [Snyk] Upgrade @emotion/styled from 11.11.0 to 11.11.5
  dapp-example/package-lock.json
  dapp-example/package.json
Labels: dependencies

#1732 refactor: Updating the configmap setup to take any ENV that is in the .Values.c…
  charts/hedera-json-rpc-relay-websocket/templates/configmap.yaml
  charts/hedera-json-rpc-relay/templates/configmap.yaml
Labels: enhancement, P2, process

#2475 feat: added support for batch request feature to WS server (#2461)
  docs/configuration.md
  docs/design/batch-request.md
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/ws-server/src/controllers/eth_subscribe.ts
  packages/ws-server/src/controllers/eth_unscribe.ts
  packages/ws-server/src/controllers/index.ts
  packages/ws-server/src/utils/constants.ts
  packages/ws-server/src/utils/utils.ts
  packages/ws-server/src/webSocketServer.ts
  packages/ws-server/tests/acceptance/batchRequest.spec.ts
  packages/ws-server/tests/helper/index.ts
Labels: enhancement, P1, dev tools

#2478 [Snyk] Upgrade pnpm from 8.15.5 to 8.15.7
  packages/ws-server/package.json
Labels: dependencies

#2479 [Snyk] Upgrade @hashgraph/sdk from 2.43.0 to 2.44.0
  dapp-example/package-lock.json
  dapp-example/package.json
Labels: P2, dependencies

#2482 chore: relocated WS_BATCH_REQUESTS_ENABLED & WS_BATCH_REQUESTS_MAX_SIZE in configuration.md
  docs/configuration.md
Labels: documentation, enhancement

#2488 chore: [Snyk] Upgrade web3 from 4.7.0 to 4.8.0
  tools/web3js-example/package-lock.json
  tools/web3js-example/package.json
Labels: P2, dependencies

#2486 fix: Added the web3_clientVersion to the websocket server.
  packages/ws-server/src/controllers/index.ts
  packages/ws-server/src/utils/constants.ts
  packages/ws-server/tests/acceptance/web3ClientVersion.spec.ts
Labels: bug

#2498 fix: fixing Field HEDERA_NETWORK on configMap helm chart template, when is not a string but a json.
  charts/hedera-json-rpc-relay/templates/configmap.yaml
Labels: bug, P1

#2487 feat: improved metrics and added rate limit for the batch request feature in ws server (#2474)
  .github/workflows/acceptance.yml
  package.json
  packages/server/tests/localAcceptance.env
  packages/ws-server/src/controllers/index.ts
  packages/ws-server/src/metrics/connectionLimiter.ts
  packages/ws-server/src/webSocketServer.ts
  packages/ws-server/tests/acceptance/batchRequest.spec.ts
  packages/ws-server/tests/acceptance/rateLimiter.spec.ts
  packages/ws-server/tests/helper/index.ts
Labels: enhancement

#2499 fix: Applied fix using trimPrecedingZeros.
  packages/relay/src/formatters.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth/eth_getTransactionByHash.spec.ts
  packages/relay/tests/lib/formatters.spec.ts
Labels: bug

#2509 chore: cherry pick 2494
  packages/ws-server/src/controllers/index.ts
  packages/ws-server/tests/acceptance/validations.spec.ts
  packages/ws-server/tests/helper/index.ts
Labels: process

#2511 chore: cherry-picked 2498
  charts/hedera-json-rpc-relay/templates/configmap.yaml
Labels: process

#2512 chore: cherry picked 2265
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/types/IFeeHistory.ts
  packages/relay/src/lib/types/ITransactionReceipt.ts
Labels: P1, process

#2513 chore: cherry picked 2492
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth/eth_getStorageAt.spec.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
Labels: P1, process

#2514 chore: cherry picked 2489
  packages/relay/src/formatters.ts
  packages/relay/tests/lib/formatters.spec.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
Labels: P1, process

#2518 chore: cherry picked 2487
  .github/workflows/acceptance.yml
  package.json
  packages/server/tests/localAcceptance.env
  packages/ws-server/src/controllers/index.ts
  packages/ws-server/src/metrics/connectionLimiter.ts
  packages/ws-server/src/webSocketServer.ts
  packages/ws-server/tests/acceptance/batchRequest.spec.ts
  packages/ws-server/tests/acceptance/rateLimiter.spec.ts
  packages/ws-server/tests/helper/index.ts
Labels: P1, process

#2502 [Snyk] Upgrade: react, react-dom
  dapp-example/package-lock.json
  dapp-example/package.json
Labels: dependencies

#2519 chore: cherry picked 2499
  packages/relay/src/formatters.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth/eth_getTransactionByHash.spec.ts
  packages/relay/tests/lib/formatters.spec.ts
Labels: P1, process

#2517 feat: make `revertReason` consistent on `eth_getTransactionReceipt`
  packages/relay/src/formatters.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/formatters.spec.ts
Labels: limechain

#2523 fix: updated CONTRACT_REVERT error code to the value `3`
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/relay/tests/lib/eth/eth_call.spec.ts
  packages/server/src/koaJsonRpc/lib/HttpStatusCodeAndMessage.ts
  packages/server/tests/acceptance/rpc_batch3.spec.ts
Labels: enhancement

#2524 chore: cherry pick 2523
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/relay/tests/lib/eth/eth_call.spec.ts
  packages/server/src/koaJsonRpc/lib/HttpStatusCodeAndMessage.ts
  packages/server/tests/acceptance/rpc_batch3.spec.ts
Labels: process

#2521 feat: added constructValidLogSubscriptionFilter() to discard any unexpected parameters for logs subcription filter object
  packages/ws-server/src/controllers/eth_subscribe.ts
  packages/ws-server/src/utils/utils.ts
  packages/ws-server/tests/acceptance/subscribe.spec.ts
  packages/ws-server/tests/unit/utils.spec.ts
Labels: enhancement, P1

#2525 chore: cherry pick 2521
  packages/ws-server/src/controllers/eth_subscribe.ts
  packages/ws-server/src/utils/utils.ts
  packages/ws-server/tests/acceptance/subscribe.spec.ts
  packages/ws-server/tests/unit/utils.spec.ts
Labels: P1, process

#2505 fix: ws errors should conform to jsonrpc spec
  packages/ws-server/src/metrics/connectionLimiter.ts
Labels: enhancement

#2536 docs: added WS release test to acceptancetest:release command
  package.json
  packages/ws-server/tests/acceptance/batchRequest.spec.ts
  packages/ws-server/tests/acceptance/validations.spec.ts
Labels: enhancement

#2526 build(deps): [Snyk] Upgrade @mui/material from 5.15.15 to 5.15.16
  dapp-example/package-lock.json
  dapp-example/package.json
Labels: dependencies

#2529 chore: cleanup acceptance tests workflow
  .github/workflows/acceptance-workflow.yml
  .github/workflows/release-acceptance.yml
  scripts/retry_script.sh
Labels: process

#2535 ci: updated ci pipelines for security and best practices
  .github/CODEOWNERS
  .github/workflows/acceptance-public.yml
  .github/workflows/acceptance-workflow.yml
  .github/workflows/acceptance.yml
  .github/workflows/charts.yml
  .github/workflows/dapp.yml
  .github/workflows/dev-tool-workflow.yml
  .github/workflows/flow-pr-title-check.yml
  .github/workflows/foundry.yml
  .github/workflows/image-build.yml
  .github/workflows/manual-testing.yml
  .github/workflows/postman.yml
  .github/workflows/release-acceptance.yml
  .github/workflows/release-automation.yml
  .github/workflows/release-integration.yml
  .github/workflows/release-production.yml
  .github/workflows/subgraph.yml
  .github/workflows/test.yml
Labels: dependencies, github_actions

#2542 build(deps): [Snyk] Upgrade: react, react-dom
  dapp-example/package-lock.json
  dapp-example/package.json
Labels: dependencies

#2540 feat: Add precheck for blob transactions
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/relay/src/lib/precheck.ts
  packages/relay/tests/helpers.ts
  packages/relay/tests/lib/eth/eth_sendRawTransaction.spec.ts
  packages/relay/tests/lib/precheck.spec.ts
  packages/server/tests/acceptance/rpc_batch3.spec.ts
Labels: limechain

#2546 fix: Resolve issue with failing acceptance batch 1 test
  package-lock.json
  packages/server/tests/acceptance/rpc_batch1.spec.ts
  packages/server/tests/helpers/utils.ts
Labels: bug, limechain

#2538 build(deps): [Snyk] Upgrade pnpm from 8.15.7 to 8.15.8
  packages/ws-server/package.json
Labels: dependencies
