Repository hiero-ledger/hiero-json-rpc-relay, pull requests merged in 2024-04, with the labels that each got.

#2269 Bump versions for v0.46.0-SNAPSHOT
  charts/hedera-json-rpc-relay-websocket/Chart.yaml
  charts/hedera-json-rpc-relay/Chart.yaml
  docs/openrpc.json
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: process, dependencies

#2286 fix: test fix. Now consider gas price deviation in estimateGas.
  packages/server/tests/acceptance/rpc_batch2.spec.ts
Labels: bug

#2257 [Snyk] Upgrade truffle from 5.10.2 to 5.11.5
  tools/truffle-example/package.json
Labels: dependencies

#2293 fix: refactor websocket folders
  packages/relay/tests/lib/subscriptionController.spec.ts
  packages/ws-server/src/controllers/eth_subscribe.ts
  packages/ws-server/src/controllers/eth_unscribe.ts
  packages/ws-server/src/controllers/index.ts
  packages/ws-server/src/utils/connectionLimiter.ts
  packages/ws-server/src/utils/constants.ts
  packages/ws-server/src/utils/counters.ts
  packages/ws-server/src/utils/formatters.ts
  packages/ws-server/src/utils/utils.ts
  packages/ws-server/src/utils/validators.ts
  packages/ws-server/src/webSocketServer.ts
  packages/ws-server/tsconfig.json
Labels: enhancement, P1

#2294 feat: integrated eth_sendRawTransaction to websocket server
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/poller.ts
  packages/relay/tests/lib/eth/eth_call.spec.ts
  packages/relay/tests/lib/formatters.spec.ts
  packages/server/tests/acceptance/ws/sendRawTransaction.spec.ts
  packages/server/tests/acceptance/ws/subscribe.spec.ts
  packages/server/tests/acceptance/ws/subscribeNewHeads.spec.ts
  packages/ws-server/src/controllers/eth_sendRawTransaction.ts
  packages/ws-server/src/controllers/eth_subscribe.ts
  packages/ws-server/src/controllers/eth_unscribe.ts
  packages/ws-server/src/controllers/index.ts
  packages/ws-server/src/utils/constants.ts
  packages/ws-server/src/utils/counters.ts
  packages/ws-server/src/utils/formatters.ts
  packages/ws-server/src/utils/utils.ts
  packages/ws-server/src/utils/validators.ts
  packages/ws-server/src/webSocketServer.ts
Labels: enhancement, P1

#2298 [Snyk] Security upgrade node from 18.18.2-bullseye-slim to 18.20.1-bullseye-slim
  Dockerfile
Labels: dependencies

#2299 [Snyk] Upgrade pnpm from 8.15.4 to 8.15.5
  packages/ws-server/package.json
Labels: dependencies

#2304 2279 feat: implement estimate gas
  packages/server/tests/acceptance/ws/estimateGas.spec.ts
  packages/server/tests/acceptance/ws/getCode.spec.ts
  packages/server/tests/acceptance/ws/subscribeNewHeads.spec.ts
  packages/ws-server/src/controllers/eth_estimateGas.ts
  packages/ws-server/src/controllers/helpers.ts
  packages/ws-server/src/controllers/index.ts
  packages/ws-server/src/utils/constants.ts
  packages/ws-server/src/webSocketServer.ts
Labels: enhancement

#2302 [Snyk] Upgrade @graphprotocol/graph-cli from 0.68.5 to 0.69.0
  tools/subgraph-example/subgraph/package.json
Labels: dependencies

#2296 feat: Implemented getCode.
  packages/ws-server/src/controllers/eth_getCode.ts
  packages/ws-server/src/controllers/helpers.ts
  packages/ws-server/src/controllers/index.ts
  packages/ws-server/src/webSocketServer.ts
Labels: enhancement

#2310 feat: added support for eth_getBlockByHash to WS server (#2272)
  dapp-example/tests/e2e/specs/index.spec.js
  packages/server/tests/acceptance/ws/getBlockByHash.spec.ts
  packages/ws-server/src/controllers/eth_getBlockByHash.ts
  packages/ws-server/src/controllers/index.ts
  packages/ws-server/src/utils/constants.ts
  packages/ws-server/src/utils/validators.ts
  packages/ws-server/src/webSocketServer.ts
Labels: enhancement, P1

#2313 feat: added support for eth_blockNumber to the WS server (#2270)
  packages/server/tests/acceptance/ws/blockNumber.spec.ts
  packages/ws-server/src/controllers/eth_blockNumber.ts
  packages/ws-server/src/controllers/index.ts
  packages/ws-server/src/utils/constants.ts
  packages/ws-server/src/webSocketServer.ts
Labels: enhancement, P1

#2321 feat: added support for eth_getBalance to the WS server (#2280)
  packages/server/tests/acceptance/ws/getBalance.spec.ts
  packages/ws-server/src/controllers/eth_getBalance.ts
  packages/ws-server/src/controllers/index.ts
  packages/ws-server/src/utils/constants.ts
  packages/ws-server/src/webSocketServer.ts
Labels: enhancement, P1

#2322 feat: added support for eth_getStorageAt to the WS server (#2277)
  packages/server/tests/acceptance/ws/getStorageAt.spec.ts
  packages/ws-server/src/controllers/eth_getStorageAt.ts
  packages/ws-server/src/controllers/index.ts
  packages/ws-server/src/utils/constants.ts
  packages/ws-server/src/webSocketServer.ts
Labels: enhancement, P1

#2323 feat: getTransactionCount.
  packages/server/tests/acceptance/ws/getTransactionCount.spec.ts
  packages/server/tests/acceptance/ws/subscribeNewHeads.spec.ts
  packages/server/tests/helpers/utils.ts
  packages/ws-server/src/controllers/eth_getTransactionCount.ts
  packages/ws-server/src/controllers/index.ts
  packages/ws-server/src/webSocketServer.ts
Labels: enhancement

#2325 feat: added support for eth_call to the WS server
  packages/server/tests/acceptance/ws/call.spec.ts
  packages/ws-server/src/controllers/eth_call.ts
  packages/ws-server/src/controllers/index.ts
  packages/ws-server/src/utils/constants.ts
  packages/ws-server/src/webSocketServer.ts
Labels: enhancement, P1

#2328 feat: added param validator to WS server (#2311)
  packages/server/tests/acceptance/ws/blockNumber.spec.ts
  packages/server/tests/acceptance/ws/call.spec.ts
  packages/server/tests/acceptance/ws/getBalance.spec.ts
  packages/server/tests/acceptance/ws/getBlockByHash.spec.ts
  packages/server/tests/acceptance/ws/getBlockByNumber.spec.ts
  packages/server/tests/acceptance/ws/getLogs.spec.ts
  packages/server/tests/acceptance/ws/getStorageAt.spec.ts
  packages/server/tests/acceptance/ws/getTransactionByHash.spec.ts
  packages/server/tests/acceptance/ws/getTransactionCount.spec.ts
  packages/server/tests/acceptance/ws/getTransactionReceipt.spec.ts
  packages/server/tests/acceptance/ws/sendRawTransaction.spec.ts
  packages/ws-server/src/controllers/eth_blockNumber.ts
  packages/ws-server/src/controllers/eth_call.ts
  packages/ws-server/src/controllers/eth_estimateGas.ts
  packages/ws-server/src/controllers/eth_gasPrice.ts
  packages/ws-server/src/controllers/eth_getBalance.ts
  packages/ws-server/src/controllers/eth_getBlockByHash.ts
  packages/ws-server/src/controllers/eth_getBlockByNumber.ts
  packages/ws-server/src/controllers/eth_getCode.ts
  packages/ws-server/src/controllers/eth_getLogs.ts
  packages/ws-server/src/controllers/eth_getStorageAt.ts
  packages/ws-server/src/controllers/eth_getTransactionByHash.ts
  packages/ws-server/src/controllers/eth_getTransactionCount.ts
  packages/ws-server/src/controllers/eth_getTransactionReceipt.ts
  packages/ws-server/src/controllers/eth_sendRawTransaction.ts
  packages/ws-server/src/controllers/eth_subscribe.ts
  packages/ws-server/src/webSocketServer.ts
Labels: enhancement, P1

#2319 fix: allows nullable value for `transaction.to` (#2314)
  packages/server/src/validator/objectTypes.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
Labels: bug

#2333 fix: Removing `name` field from RPC Error when returning Execution Revert on `eth_call`
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/relay/tests/lib/eth/eth_call.spec.ts
  packages/server/tests/acceptance/rpc_batch3.spec.ts
  packages/server/tests/clients/relayClient.ts
Labels: bug

#2335 fix: allows nullable value for `transaction.to` (#2314) (#2319)
  packages/server/src/validator/objectTypes.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
Labels: bug

#2230 fix: Fix to eth_subscribe.md
  docs/design/eth-subscribe.md
Labels: documentation

#2308 [Snyk] Upgrade @hashgraph/sdk from 2.42.0 to 2.43.0
  dapp-example/package-lock.json
  dapp-example/package.json
Labels: dependencies

#2340 feat: added acceptance test coverage for standard web socket (#2316)
  packages/ws-server/src/webSocketServer.ts
  packages/ws-server/tests/acceptance/blockNumber.spec.ts
  packages/ws-server/tests/acceptance/call.spec.ts
  packages/ws-server/tests/acceptance/estimateGas.spec.ts
  packages/ws-server/tests/acceptance/gasPrice.spec.ts
  packages/ws-server/tests/acceptance/getBalance.spec.ts
  packages/ws-server/tests/acceptance/getBlockByHash.spec.ts
  packages/ws-server/tests/acceptance/getBlockByNumber.spec.ts
  packages/ws-server/tests/acceptance/getCode.spec.ts
  packages/ws-server/tests/acceptance/getLogs.spec.ts
  packages/ws-server/tests/acceptance/getStorageAt.spec.ts
  packages/ws-server/tests/acceptance/getTransactionByHash.spec.ts
  packages/ws-server/tests/acceptance/getTransactionCount.spec.ts
  packages/ws-server/tests/acceptance/getTransactionReceipt.spec.ts
  packages/ws-server/tests/acceptance/sendRawTransaction.spec.ts
  packages/ws-server/tests/acceptance/subscribe.spec.ts
  packages/ws-server/tests/helper/index.ts
Labels: enhancement, P1

#2332 feat: Updated to deploy the contract using a websocket provider.
  packages/ws-server/tests/acceptance/estimateGas.spec.ts
Labels: bug

#2351 fix: Now sets the WS_NEW_HEADS_ENABLED to true by default.
  docs/configuration.md
  packages/relay/src/lib/poller.ts
  packages/ws-server/src/controllers/eth_subscribe.ts
Labels: enhancement

#2343 fix: rebuilt package-lock.json
  tools/truffle-example/package-lock.json
Labels: enhancement

#2361 fix: fixed setting WS_NEW_HEADS_ENABLED true as default logic (#2360)
  packages/ws-server/src/controllers/eth_subscribe.ts
  packages/ws-server/tests/acceptance/subscribeNewHeads.spec.ts
Labels: bug, P1

#2357 [Snyk] Upgrade @hashgraph/hedera-local from 2.19.1 to 2.19.2
  package-lock.json
  package.json
Labels: dependencies

#2364 feat: Adding websocket grafana dashboard to the relay repository.
  grafana/dashboards/websocketServer/webSocketServer.json
Labels: enhancement

#2363 fix: added ability to send back to clients the reason on closing at max connection limit (#2362)
  packages/ws-server/src/utils/connectionLimiter.ts
  packages/ws-server/src/webSocketServer.ts
Labels: enhancement

#2365 chore: Remove specific version of NX dependency override. is working now.
  package-lock.json
  package.json
Labels: dependencies

#2370 docs(update): updated configuration.md (#2369)
  docs/configuration.md
  docs/hbar-limiting.md
Labels: enhancement

#2378 feat: added histograms and counters to capture metrics for connection life cycle (#2352)
  packages/ws-server/src/metrics/wsMetricRegistry.ts
  packages/ws-server/src/utils/constants.ts
  packages/ws-server/src/utils/utils.ts
  packages/ws-server/src/webSocketServer.ts
Labels: enhancement

#2381 feat: Added resource metrics.
  packages/ws-server/src/metrics/wsMetricRegistry.ts
  packages/ws-server/src/utils/constants.ts
  packages/ws-server/src/webSocketServer.ts
Labels: enhancement

#2372 fix: updated MIRROR_NODE_RETRY_DELAY to 1800ms (#2371)
  packages/relay/src/lib/clients/mirrorNodeClient.ts
Labels: enhancement

#2396 feat: Websocket documentation updates.
  docs/live-events-api.md
Labels: documentation

#2398 fix: Removed debugger settings.
  packages/relay/tsconfig.json
  packages/server/tsconfig.json
Labels: bug

#2393 feat: support deterministic proxy contract deployment transaction (#2287)
  .github/workflows/acceptance.yml
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/precheck.ts
  packages/relay/tests/lib/precheck.spec.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
  packages/ws-server/tests/acceptance/sendRawTransaction.spec.ts
Labels: enhancement, P1

#2406 fix: extended ping interval to 100s in WS server
  docs/configuration.md
  packages/ws-server/src/webSocketServer.ts
  packages/ws-server/tests/acceptance/estimateGas.spec.ts
  packages/ws-server/tests/acceptance/subscribe.spec.ts
  packages/ws-server/tests/acceptance/subscribeNewHeads.spec.ts
Labels: bug

#2395 fix: Re-submitting the memory handling
  .github/workflows/test.yml
Labels: enhancement

#2415 chore: Cherry pick #2393 on `0.46` release
  .github/workflows/acceptance-public.yml
  .github/workflows/acceptance.yml
  package-lock.json
  package.json
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/precheck.ts
  packages/relay/tests/lib/precheck.spec.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
  packages/ws-server/tests/acceptance/blockNumber.spec.ts
  packages/ws-server/tests/acceptance/call.spec.ts
  packages/ws-server/tests/acceptance/estimateGas.spec.ts
  packages/ws-server/tests/acceptance/gasPrice.spec.ts
  packages/ws-server/tests/acceptance/getBalance.spec.ts
  packages/ws-server/tests/acceptance/getBlockByHash.spec.ts
  packages/ws-server/tests/acceptance/getBlockByNumber.spec.ts
  packages/ws-server/tests/acceptance/getCode.spec.ts
  packages/ws-server/tests/acceptance/getLogs.spec.ts
  packages/ws-server/tests/acceptance/getStorageAt.spec.ts
  packages/ws-server/tests/acceptance/getTransactionByHash.spec.ts
  packages/ws-server/tests/acceptance/getTransactionCount.spec.ts
  packages/ws-server/tests/acceptance/getTransactionReceipt.spec.ts
  packages/ws-server/tests/acceptance/sendRawTransaction.spec.ts
  packages/ws-server/tests/acceptance/subscribe.spec.ts
  packages/ws-server/tests/acceptance/subscribeNewHeads.spec.ts
Labels: process

#2417 chore: cherry-pick of: fix: Use Transaction1559 type to create synthetic transactions. (#2405)
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth/eth-config.ts
  packages/relay/tests/lib/eth/eth_getBlockByNumber.spec.ts
Labels: process

#2419 fix: moved deleteFile() logic to the eth_sendRawTransaction level (#2418)
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth/eth_sendRawTransaction.spec.ts
Labels: bug, P1

#2408 [Snyk] Security upgrade node from 18.18.2-bullseye-slim to 18.20.2-bullseye-slim
  Dockerfile
Labels: dependencies

#2412 chore: bumped hedera-local to 2.23.0
  package-lock.json
  package.json
Labels: dependencies

#2428 chore: Revert synk PR #2408. Docker image won't build.
  Dockerfile
Labels: dependencies

#2430 chore: Revert synk PR #2408. Docker image won't build. (#2428)
  Dockerfile
Labels: dependencies

#2427 ci: removed networkTag for API Batch 1 and Websocket Batch 2 CI tasks (#2402)
  .github/workflows/acceptance.yml
Labels: enhancement
