Repository hiero-ledger/hiero-json-rpc-relay, pull requests merged in 2024-03, with the labels that each got.

#2159 2117 poll for new heads doc updates
  docs/configuration.md
  docs/design/eth-subscribe.md
Labels: design

#2166 [Snyk] Upgrade dotenv from 16.4.1 to 16.4.2
  tools/truffle-example/package-lock.json
  tools/truffle-example/package.json
Labels: dependencies

#2135 feat: Adds missing block aliases
  docs/openrpc.json
  packages/relay/src/lib/services/ethService/ethCommonService/index.ts
  packages/relay/tests/lib/eth/eth_feeHistory.spec.ts
  packages/relay/tests/lib/eth/eth_getBalance.spec.ts
  packages/relay/tests/lib/eth/eth_getBlockByNumber.spec.ts
  packages/relay/tests/lib/eth/eth_getBlockTransactionCountByNumber.spec.ts
  packages/relay/tests/lib/eth/eth_getStorageAt.spec.ts
  packages/relay/tests/lib/eth/eth_getTransactionByBlockNumberAndIndex.spec.ts
  packages/relay/tests/lib/eth/eth_getTransactionCount.spec.ts
  packages/server/src/validator/types.ts
Labels: bug

#2170 [Snyk] Upgrade @graphprotocol/graph-cli from 0.67.4 to 0.68.0
  tools/subgraph-example/subgraph/package.json
Labels: dependencies

#2171 [Snyk] Upgrade dotenv from 16.4.2 to 16.4.3
  tools/truffle-example/package-lock.json
  tools/truffle-example/package.json
Labels: dependencies

#2172 [Snyk] Upgrade web3 from 4.4.0 to 4.5.0
  tools/web3js-example/package-lock.json
  tools/web3js-example/package.json
Labels: dependencies

#2177 [Snyk] Upgrade dotenv from 16.4.3 to 16.4.4
  tools/truffle-example/package-lock.json
  tools/truffle-example/package.json
Labels: dependencies

#2185 fix: resolved evm addresses for `from` and `to` addresses in returned transactions
  packages/relay/src/lib/eth.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
Labels: enhancement, P1

#2186 [Snyk] Upgrade dotenv from 16.4.1 to 16.4.4
  tools/web3js-example/package-lock.json
  tools/web3js-example/package.json
Labels: dependencies

#2187 [Snyk] Upgrade @graphprotocol/graph-ts from 0.32.0 to 0.33.0
  tools/subgraph-example/subgraph/package.json
Labels: dependencies

#2193 [Snyk] Upgrade @hashgraph/hedera-local from 2.18.1 to 2.19.0
  package-lock.json
  package.json
Labels: dependencies

#2197 fix: HotFix for using mSet instead of Set for redis cache when storing synthetic transactions
  packages/relay/src/lib/clients/cache/ICacheClient.ts
  packages/relay/src/lib/clients/cache/localLRUCache.ts
  packages/relay/src/lib/clients/cache/redisCache.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/services/cacheService/cacheService.ts
  packages/relay/tests/lib/services/cacheService/cacheService.spec.ts
Labels: bug

#2199 [Snyk] Upgrade keyv-file from 0.3.0 to 0.3.1
  package-lock.json
  package.json
Labels: dependencies

#2211 [Snyk] Upgrade @graphprotocol/graph-cli from 0.68.0 to 0.68.3
  tools/subgraph-example/subgraph/package.json
Labels: dependencies

#2213 fix: HotFix for using mSet instead of Set for redis cache
  packages/relay/src/lib/clients/cache/ICacheClient.ts
  packages/relay/src/lib/clients/cache/localLRUCache.ts
  packages/relay/src/lib/clients/cache/redisCache.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/services/cacheService/cacheService.ts
  packages/relay/tests/lib/services/cacheService/cacheService.spec.ts
Labels: bug

#2180 fix: trimmed preceding zeros for gas value (#2174)
  packages/relay/src/formatters.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/formatters.spec.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
Labels: enhancement, P1

#2215 feat: Added metric for newHeads.
  packages/relay/src/lib/poller.ts
Labels: enhancement

#2184 fix: convert value from weibars to tinybars in eth_call
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth/eth-config.ts
  packages/relay/tests/lib/eth/eth_call.spec.ts
  packages/relay/tests/lib/eth/eth_estimateGas.spec.ts
  packages/server/tests/acceptance/rpc_batch3.spec.ts
Labels: bug, limechain

#2232 [Snyk] Upgrade @hashgraph/sdk from 2.41.0 to 2.42.0
  package-lock.json
  packages/relay/package.json
Labels: dependencies

#2233 [Snyk] Upgrade @graphprotocol/graph-cli from 0.68.3 to 0.68.4
  tools/subgraph-example/subgraph/package.json
Labels: dependencies

#2228 fix: added support for legacy pre EIP 155 transactions with no chainID (chainId=0x0)
  packages/relay/src/lib/precheck.ts
  packages/relay/tests/lib/precheck.spec.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
Labels: enhancement, P1

#2238 [Snyk] Upgrade @hashgraph/sdk from 2.41.0 to 2.42.0
  dapp-example/package-lock.json
  dapp-example/package.json
Labels: dependencies

#2237 chore: update hashgraph/sdk to 2.43.0
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: dependencies

#2227 feat: Added support for newHeads include transactions.
  docs/design/eth-subscribe.md
  packages/relay/src/lib/poller.ts
  packages/relay/src/lib/subscriptionController.ts
  packages/server/tests/acceptance/ws/subscribe.spec.ts
  packages/server/tests/acceptance/ws/subscribeNewHeads.spec.ts
  packages/ws-server/src/webSocketServer.ts
Labels: bug, documentation, enhancement

#2240 fix: added support for legacy pre EIP 155 transactions with no chainI…
  packages/relay/src/lib/precheck.ts
  packages/relay/tests/lib/precheck.spec.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
Labels: bug

#2242 feat: Added support for newHeads include transactions. (#2227)
  docs/design/eth-subscribe.md
  packages/relay/src/lib/poller.ts
  packages/relay/src/lib/subscriptionController.ts
  packages/server/tests/acceptance/ws/subscribe.spec.ts
  packages/server/tests/acceptance/ws/subscribeNewHeads.spec.ts
  packages/ws-server/src/webSocketServer.ts
Labels: enhancement

#2239 [Snyk] Upgrade pnpm from 8.15.3 to 8.15.4
  package-lock.json
  packages/ws-server/package.json
Labels: dependencies

#2244 [Snyk] Upgrade @graphprotocol/graph-cli from 0.68.4 to 0.68.5
  tools/subgraph-example/subgraph/package.json
Labels: dependencies

#2251 docs: updated rpc-api endpoint table
  docs/rpc-api.md
Labels: enhancement

#2236 feat: remove block range limit in `eth_getLogs` when filtering with a single address
  docs/openrpc.json
  packages/relay/src/index.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/services/ethService/ethCommonService/index.ts
  packages/relay/tests/lib/eth/eth_getLogs.spec.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
Labels: enhancement, P1

#2261 chore: cherry-pick #2236 into release 0.44
  docs/openrpc.json
  packages/relay/src/index.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/services/ethService/ethCommonService/index.ts
  packages/relay/tests/lib/eth/eth_getLogs.spec.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
Labels: process

#2243 feat: added deleteFile() method to delete files from the network
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/tests/lib/sdkClient.spec.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
Labels: enhancement

#2259 feat: added parameter check on block param for getcode()
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth/eth_getCode.spec.ts
  packages/relay/tests/lib/eth/eth_getTransactionCount.spec.ts
Labels: enhancement
