Repository hiero-ledger/hiero-json-rpc-relay, pull requests merged in 2024-09, with the labels that each got.

#2902 feat: Implement `HbarLimitService#addExpense`
  .eslintrc.js
  .eslintrc.yml
  packages/relay/src/lib/services/hbarLimitService/IHbarLimitService.ts
  packages/relay/src/lib/services/hbarLimitService/index.ts
  packages/relay/tests/lib/services/hbarLimitService/hbarLimitService.spec.ts
Labels: enhancement, P1

#2915 fix: `debug_traceTransaction` throws 500 for non-existing transaction hashes
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/services/debugService/index.ts
  packages/relay/tests/lib/services/debugService/debug.spec.ts
  packages/server/tests/acceptance/rpc_batch3.spec.ts
Labels: bug

#2929 fix: let the provider decide when to reuse an existing subscription ID
  docs/configuration.md
  packages/relay/src/lib/subscriptionController.ts
  packages/relay/tests/lib/subscriptionController.spec.ts
Labels: enhancement

#2928 ci: update workflows to use latitude.sh based runners
  .github/workflows/acceptance-public.yml
  .github/workflows/acceptance-workflow.yml
  .github/workflows/acceptance.yml
  .github/workflows/charts.yml
  .github/workflows/conformity-workflow.yml
  .github/workflows/dapp.yml
  .github/workflows/dev-tool-workflow.yml
  .github/workflows/flow-pr-title-check.yml
  .github/workflows/foundry.yml
  .github/workflows/image-build.yml
  .github/workflows/manual-testing.yml
  .github/workflows/postman.yml
  .github/workflows/release-acceptance.yml
  .github/workflows/release-automation.yml
  .github/workflows/release-integration.yml
  .github/workflows/release-production.yml
  .github/workflows/subgraph.yml
  .github/workflows/test.yml
  tools/subgraph-example/package.json
Labels: enhancement, github_actions

#2919 fix: removed nonce precheck buffer
  docs/configuration.md
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/precheck.ts
  packages/relay/tests/lib/precheck.spec.ts
  packages/ws-server/src/controllers/index.ts
  packages/ws-server/tests/acceptance/sendRawTransaction.spec.ts
Labels: bug

#2936 fix: removed nonce precheck buffer (#2919)
  docs/configuration.md
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/precheck.ts
  packages/relay/tests/lib/precheck.spec.ts
  packages/ws-server/src/controllers/index.ts
  packages/ws-server/tests/acceptance/sendRawTransaction.spec.ts
Labels: bug

#2912 feat: create third batch of conformity tests
  .github/workflows/conformity-workflow.yml
  packages/server/tests/acceptance/conformityTests.spec.ts
Labels: enhancement

#2923 ci: Updating the workflows/actions to use the step-security version.
  .github/workflows/foundry.yml
Labels: github_actions

#2914 ci: Updating actions to use step-security version
  .github/workflows/acceptance-public.yml
  .github/workflows/acceptance-workflow.yml
  .github/workflows/acceptance.yml
  .github/workflows/manual-testing.yml
  .github/workflows/release-acceptance.yml
  .github/workflows/test.yml
Labels: github_actions

#2942 ci: Revert breaking change to publish-unit-test-result-action
  .github/workflows/acceptance-public.yml
  .github/workflows/acceptance-workflow.yml
  .github/workflows/acceptance.yml
  .github/workflows/manual-testing.yml
  .github/workflows/release-acceptance.yml
  .github/workflows/test.yml
Labels: bug, github_actions

#2931 feat: Add `keys()` method to `CacheService`
  packages/relay/src/lib/clients/cache/ICacheClient.ts
  packages/relay/src/lib/clients/cache/localLRUCache.ts
  packages/relay/src/lib/clients/cache/redisCache.ts
  packages/relay/src/lib/errors/RedisCacheError.ts
  packages/relay/src/lib/services/cacheService/cacheService.ts
  packages/relay/tests/lib/clients/localLRUCache.spec.ts
  packages/relay/tests/lib/clients/redisCache.spec.ts
  packages/relay/tests/lib/services/cacheService/cacheService.spec.ts
Labels: enhancement

#2828 feat: Add workaround for support of isAssociated
  charts/hedera-json-rpc-relay/value-test.yaml
  charts/hedera-json-rpc-relay/values.yaml
  docs/configuration.md
  package-lock.json
  package.json
  packages/relay/src/formatters.ts
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth/eth_call.spec.ts
  packages/relay/tests/lib/formatters.spec.ts
  packages/server/package.json
  packages/ws-server/package.json
  packages/ws-server/tests/acceptance/subscribe.spec.ts
  tools/hardhat-viem-example/package-lock.json
  tools/hardhat-viem-example/package.json
Labels: enhancement

#2938 feat: block gas limit should be 30_000_000
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/precheck.ts
  packages/relay/tests/assertions.ts
  packages/relay/tests/lib/eth/eth_call.spec.ts
  packages/relay/tests/lib/precheck.spec.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
  packages/server/tests/helpers/assertions.ts
Labels: bug

#2949 docs: added Preemptive Rate Limitting for HFS Transactions to hbar-limiter desgin doc
  docs/design/hbar-limiter.md
Labels: enhancement

#2918 fix: [Snyk] Upgrade @mui/material from 5.16.6 to 5.16.7
  dapp-example/package-lock.json
  dapp-example/package.json
Labels: dependencies

#2930 build(deps): [Snyk] Upgrade keyv-file from 0.3.1 to 0.3.2
  package-lock.json
  package.json
Labels: dependencies

#2932 feat: Add new metrics for spending plans
  packages/relay/src/lib/db/repositories/hbarLimiter/hbarSpendingPlanRepository.ts
  packages/relay/src/lib/services/hbarLimitService/index.ts
  packages/relay/tests/lib/repositories/hbarLimiter/hbarSpendingPlanRepository.spec.ts
  packages/relay/tests/lib/services/hbarLimitService/hbarLimitService.spec.ts
Labels: enhancement

#2964 build: (deps) [Snyk] Upgrade @emotion/react from 11.13.0 to 11.13.3
  dapp-example/package-lock.json
  dapp-example/package.json
Labels: dependencies

#2965 build: deps [Snyk] Upgrade @graphprotocol/graph-cli from 0.80.0 to 0.80.1
  tools/subgraph-example/subgraph/package.json
Labels: dependencies

#2950 feat: implement preemptive rate limitting logic to HbarLimitService class
  packages/relay/src/lib/services/hbarLimitService/IHbarLimitService.ts
  packages/relay/src/lib/services/hbarLimitService/index.ts
  packages/relay/tests/lib/services/hbarLimitService/hbarLimitService.spec.ts
Labels: enhancement

#2917 feat: Updated design doc to describe flexible alerting for spending l…
  docs/design/hbar-limiter.md
Labels: design

#2986 build(deps): [Snyk] Security upgrade koa-router from 12.0.1 to 13.0.1
  package-lock.json
  packages/ws-server/package.json
Labels: dependencies

#2985 build: (deps)[Snyk] Security upgrade koa-router from 12.0.1 to 13.0.1
  package-lock.json
  packages/server/package.json
Labels: dependencies

#2969 docs: Add high-level flow diagram of the redesigned hbar limiter
  docs/design/hbar-limiter.md
Labels: documentation, design

#2967 build: (deps). [Snyk] Upgrade: , , keyv-file
  package-lock.json
  package.json
Labels: dependencies

#2952 fix: improve `RedisCache` and simplify usage of `RedisInMemoryServer` in tests
  packages/relay/src/lib/clients/cache/redisCache.ts
  packages/relay/src/lib/services/cacheService/cacheService.ts
  packages/relay/tests/helpers.ts
  packages/relay/tests/lib/clients/redisCache.spec.ts
  packages/relay/tests/lib/ethGetBlockBy.spec.ts
  packages/relay/tests/lib/repositories/hbarLimiter/ethAddressHbarSpendingPlanRepository.spec.ts
  packages/relay/tests/lib/repositories/hbarLimiter/hbarSpendingPlanRepository.spec.ts
  packages/relay/tests/lib/services/cacheService/cacheService.spec.ts
  packages/relay/tests/redisInMemoryServer.ts
Labels: enhancement, Technical Debt

#2972 fix: Bumped up exchanged value
  packages/server/tests/acceptance/rpc_batch2.spec.ts
Labels: bug

#2983 feat: improved eth call force to consensus by selector logic
  charts/hedera-json-rpc-relay/value-test.yaml
  charts/hedera-json-rpc-relay/values.yaml
  docs/configuration.md
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth/eth_call.spec.ts
  packages/server/tests/acceptance/rpc_batch3.spec.ts
  packages/server/tests/contracts/HRC719Contract.json
  packages/server/tests/contracts/HRC719Contract.sol
  packages/server/tests/contracts/IHRC719.sol
Labels: enhancement

#2913 feat: add ipAddressHbarSpendingPlan
  packages/relay/src/lib/db/entities/hbarLimiter/ipAddressHbarSpendingPlan.ts
  packages/relay/src/lib/db/repositories/hbarLimiter/ipAddressHbarSpendingPlanRepository.ts
  packages/relay/src/lib/db/types/hbarLimiter/errors.ts
  packages/relay/src/lib/db/types/hbarLimiter/ipAddressHbarSpendingPlan.ts
  packages/relay/src/lib/services/hbarLimitService/index.ts
  packages/relay/tests/lib/repositories/hbarLimiter/ipAddressHbarSpendingPlanRepository.spec.ts
  packages/relay/tests/lib/services/hbarLimitService/hbarLimitService.spec.ts
Labels: enhancement

#2966 feat: Implement `resetLimit`
  packages/relay/src/lib/db/repositories/hbarLimiter/hbarSpendingPlanRepository.ts
  packages/relay/src/lib/services/hbarLimitService/index.ts
  packages/relay/tests/lib/repositories/hbarLimiter/hbarSpendingPlanRepository.spec.ts
  packages/relay/tests/lib/services/hbarLimitService/hbarLimitService.spec.ts
Labels: enhancement

#2981 feat: enabled retrieval of network `gasPrice` in `sendRawTransaction` using MAPI instead of HAPI.
  packages/relay/src/formatters.ts
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/precheck.ts
  packages/relay/tests/lib/formatters.spec.ts
  packages/relay/tests/lib/sdkClient.spec.ts
Labels: enhancement

#2998 test: example web3py usage
  tools/web3py-example/.env.example
  tools/web3py-example/.gitignore
  tools/web3py-example/README.md
  tools/web3py-example/contract/Greeter.sol
  tools/web3py-example/scripts/test.py
Labels: enhancement, ArianeLabs

#2922 feat: improved preemtive rate limit for file transactions
  packages/relay/src/index.ts
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/hbarlimiter/index.ts
  packages/relay/tests/helpers.ts
  packages/relay/tests/lib/eth/eth_sendRawTransaction.spec.ts
  packages/relay/tests/lib/hbarLimiter.spec.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
  packages/relay/tests/lib/openrpc.spec.ts
  packages/relay/tests/lib/sdkClient.spec.ts
  packages/server/tests/acceptance/hbarLimiter.spec.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
Labels: enhancement

#2999 feat: results of rust ethereum clients research
  tools/alloy-core-rs-example/.env.example
  tools/alloy-core-rs-example/.gitignore
  tools/alloy-core-rs-example/Cargo.lock
  tools/alloy-core-rs-example/Cargo.toml
  tools/alloy-core-rs-example/README.md
  tools/alloy-core-rs-example/contract/Greeter.sol
  tools/alloy-core-rs-example/contract/out/Greeter.sol/Greeter.json
  tools/alloy-core-rs-example/contract/out/build-info/7f3c822f6fba8c1e4e5e2894bb7355b5.json
  tools/alloy-core-rs-example/src/main.rs
  tools/ethers-rs-example/.env.example
  tools/ethers-rs-example/.gitignore
  tools/ethers-rs-example/Cargo.lock
  tools/ethers-rs-example/Cargo.toml
  tools/ethers-rs-example/README.md
  tools/ethers-rs-example/contract/Greeter.sol
  tools/ethers-rs-example/contract/out/Greeter.sol/Greeter.json
  tools/ethers-rs-example/contract/out/build-info/7f3c822f6fba8c1e4e5e2894bb7355b5.json
  tools/ethers-rs-example/src/main.rs
  tools/web3rs-example/.env.example
  tools/web3rs-example/.gitignore
  tools/web3rs-example/Cargo.lock
  tools/web3rs-example/Cargo.toml
  tools/web3rs-example/README.md
  tools/web3rs-example/src/SimpleStorage.abi
  tools/web3rs-example/src/SimpleStorage.bin
  tools/web3rs-example/src/main.rs
Labels: enhancement, ArianeLabs

#2996 build: (deps) [Snyk] Upgrade web3 from 4.11.1 to 4.12.1
  tools/web3js-example/package-lock.json
  tools/web3js-example/package.json
Labels: dependencies

#2971 feat: Defined a barebones mainnet-light test suite.
  package.json
  packages/server/tests/acceptance/rpc_batch1.spec.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
Labels: enhancement

#2993 fix: included `call.from` to the `cacheKey` in callConsensusNode()
  packages/relay/src/lib/eth.ts
Labels: enhancement

#3006 chore: Bump versions for v0.57.0-SNAPSHOT
  charts/hedera-json-rpc-relay-websocket/Chart.yaml
  charts/hedera-json-rpc-relay/Chart.yaml
  charts/hedera-json-rpc/Chart.yaml
  docs/openrpc.json
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: process

#2924 ci: Updating the workflows/actions to use the step-security version.
  .github/workflows/acceptance-workflow.yml
  .github/workflows/dev-tool-workflow.yml
  .github/workflows/postman.yml
  .github/workflows/release-acceptance.yml
Labels: enhancement, github_actions

#3010 fix: hardcoded chainId in acceptance tests
  packages/relay/tests/lib/eth/eth_sendRawTransaction.spec.ts
  packages/server/tests/acceptance/conformityTests.spec.ts
  packages/server/tests/acceptance/rpc_batch3.spec.ts
  packages/server/tests/previewnetAcceptance.env
  packages/server/tests/testnetAcceptance.env
Labels: bug

#2997 chore: Disable spending history of HbarSpendingPlans
  packages/relay/src/lib/db/repositories/hbarLimiter/hbarSpendingPlanRepository.ts
  packages/relay/src/lib/services/hbarLimitService/index.ts
  packages/relay/tests/lib/repositories/hbarLimiter/hbarSpendingPlanRepository.spec.ts
  packages/relay/tests/lib/services/hbarLimitService/hbarLimitService.spec.ts
Labels: enhancement

#3012 ci: Fix issue with github_env echo statements
  .github/workflows/acceptance-public.yml
  .github/workflows/acceptance-workflow.yml
  .github/workflows/conformity-workflow.yml
Labels: github_actions

#3019 ci: Updating permissions within manual-testing to resolve workflow issue.
  .github/workflows/manual-testing.yml
Labels: github_actions

#3015 build(deps): [Snyk] Upgrade @graphprotocol/graph-cli from 0.80.1 to 0.81.0
  tools/subgraph-example/subgraph/package.json
Labels: enhancement

#3027 fix: failing websocket tests in manual-testing.yml
  .github/workflows/manual-testing.yml
Labels: bug

#3034 feat: bump hedera local node version to 2.31.0 and fix `eth_estimateGas` with hollow account creation test
  package-lock.json
  package.json
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth/eth_estimateGas.spec.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
  packages/ws-server/tests/acceptance/sendRawTransaction.spec.ts
Labels: enhancement

#3036 chore: Move unneeded dependencies to `devDependencies`
  package-lock.json
  package.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: enhancement, Technical Debt

#3013 feat: Added configuration option for allocating HBar for a test run.
  docs/configuration.md
  packages/server/tests/acceptance/index.spec.ts
  packages/server/tests/clients/servicesClient.ts
  packages/server/tests/helpers/utils.ts
Labels: enhancement

#3046 build: Bump versions for v0.58.0-SNAPSHOT
  charts/hedera-json-rpc-relay-websocket/Chart.yaml
  charts/hedera-json-rpc-relay/Chart.yaml
  charts/hedera-json-rpc/Chart.yaml
  docs/openrpc.json
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: process
