Repository hiero-ledger/hiero-json-rpc-relay, pull requests merged in 2024-01, with the labels that each got.

#2004 Bump versions for v0.40.0-SNAPSHOT
  charts/hedera-json-rpc-relay-websocket/Chart.yaml
  charts/hedera-json-rpc-relay/Chart.yaml
  docs/openrpc.json
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: dependencies

#2001 chore: [Snyk] Upgrade web3 from 4.2.2 to 4.3.0
  tools/web3js-example/package-lock.json
  tools/web3js-example/package.json
Labels: dependencies

#2000 chore: [Snyk] Upgrade pnpm from 8.11.0 to 8.12.0
  package-lock.json
  packages/ws-server/package.json
Labels: dependencies

#2014 [Snyk] Upgrade pnpm from 8.12.1 to 8.13.0
  package-lock.json
  packages/ws-server/package.json
Labels: dependencies

#2016 [Snyk] Upgrade @graphprotocol/graph-cli from 0.62.0 to 0.64.0
  tools/subgraph-example/subgraph/package.json
Labels: dependencies

#2017 [Snyk] Upgrade @graphprotocol/graph-ts from 0.31.0 to 0.32.0
  tools/subgraph-example/subgraph/package.json
Labels: dependencies

#2018 [Snyk] Upgrade @hashgraph/hedera-local from 2.16.0 to 2.17.2
  package-lock.json
  package.json
Labels: dependencies

#2027 [Snyk] Upgrade @hashgraph/hedera-local from 2.16.0 to 2.17.2
  tools/hardhat-example/package-lock.json
  tools/hardhat-example/package.json
Labels: dependencies

#2020 2019 update included tools to include foundry
  tools/README.md
  tools/foundry-example/README.md
Labels: documentation

#2030 [Snyk] Upgrade @mui/material from 5.15.0 to 5.15.1
  dapp-example/package-lock.json
  dapp-example/package.json
Labels: dependencies

#2032 [Snyk] Upgrade redis from 4.6.11 to 4.6.12
  package-lock.json
  package.json
Labels: dependencies

#2031 test: 2013 add polling to the relay stabilize
  packages/server/tests/acceptance/htsPrecompile/tokenCreate.spec.ts
  packages/server/tests/acceptance/htsPrecompile/tokenManagement.spec.ts
  packages/server/tests/acceptance/rpc_batch3.spec.ts
  packages/server/tests/helpers/utils.ts
Labels: bug

#2034 test: Added the deploy retry.
  packages/server/tests/acceptance/htsPrecompile_v1.spec.ts
Labels: bug

#2035 [Snyk] Upgrade @graphprotocol/graph-cli from 0.64.0 to 0.64.1
  tools/subgraph-example/subgraph/package.json
Labels: dependencies

#2036 [Snyk] Upgrade @emotion/react from 11.11.1 to 11.11.3
  dapp-example/package-lock.json
  dapp-example/package.json
Labels: dependencies

#2038 [Snyk] Upgrade @mui/material from 5.15.1 to 5.15.2
  dapp-example/package-lock.json
  dapp-example/package.json
Labels: dependencies

#2042 fix: nonce too low precheck relaxed to allow a buffer
  docs/configuration.md
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/precheck.ts
  packages/relay/tests/lib/precheck.spec.ts
Labels: bug

#2044 fix: Cherry pick 2042 into 0.39
  docs/configuration.md
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/precheck.ts
  packages/relay/tests/lib/precheck.spec.ts
Labels: bug

#2041 [Snyk] Upgrade pnpm from 8.13.0 to 8.13.1
  package-lock.json
  packages/ws-server/package.json
Labels: dependencies

#2046 fix: Removed prechecks for existing accounts.
  packages/relay/src/formatters.ts
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth/eth_call.spec.ts
  packages/relay/tests/lib/formatters.spec.ts
Labels: bug

#2048 fix: Removed prechecks for existing accounts. (#2046)
  packages/relay/src/formatters.ts
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth/eth_call.spec.ts
  packages/relay/tests/lib/formatters.spec.ts
Labels: bug

#2049 chore: add test reports to acceptance tests workflow
  .github/workflows/acceptance-public.yml
  .github/workflows/acceptance-workflow.yml
  .github/workflows/acceptance.yml
  .github/workflows/dev-tool-workflow.yml
  .github/workflows/test.yml
  .mocharc.js
  package-lock.json
  package.json
Labels: enhancement, limechain

#2033 fix: Added 20% deviation in gasPricing.
  docs/configuration.md
  packages/server/tests/acceptance/rpc_batch1.spec.ts
  packages/server/tests/helpers/assertions.ts
  packages/server/tests/localAcceptance.env
  packages/server/tests/previewnetAcceptance.env
  packages/server/tests/testnetAcceptance.env
Labels: bug

#2051 fix: remove unneeded applying of gas on
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth/eth_call.spec.ts
Labels: bug, limechain

#2053 chore: Bump versions for v0.41.0-SNAPSHOT
  charts/hedera-json-rpc-relay-websocket/Chart.yaml
  charts/hedera-json-rpc-relay/Chart.yaml
  docs/openrpc.json
  package-lock.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: process

#2059 [Snyk] Upgrade @mui/material from 5.15.2 to 5.15.3
  dapp-example/package-lock.json
  dapp-example/package.json
Labels: dependencies

#2060 [Snyk] Upgrade pnpm from 8.13.1 to 8.14.0
  package-lock.json
  packages/ws-server/package.json
Labels: dependencies

#2056 docs: add verification instructions in Hardhat example
  tools/hardhat-example/.env.example
  tools/hardhat-example/hardhat.config.js
  tools/hardhat-example/package-lock.json
  tools/hardhat-example/package.json
  tools/hardhat-example/scripts/deployContract.js
  tools/hardhat-example/scripts/showBalance.js
  tools/hardhat-example/scripts/transferHbars.js
  tools/hardhat-example/test/rpc.js
  tools/hardhat-example/test/simple-vault.js
Labels: enhancement, dev tools

#1903 fix: formatting on standalone networks
  charts/hedera-json-rpc-relay-websocket/templates/configmap.yaml
  charts/hedera-json-rpc-relay/templates/configmap.yaml
Labels: P2, process

#2061 docs: Add note about `stateRoot` in `getBlockBy*` RPCs
  docs/rpc-api.md
Labels: documentation

#2067 build: Upgraded koa-router dependency to 12.0.1 to improve performance
  package-lock.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: dependencies

#2069 [Snyk] Upgrade @mui/material from 5.15.3 to 5.15.4
  dapp-example/package-lock.json
  dapp-example/package.json
Labels: dependencies
