Repository hiero-ledger/hiero-json-rpc-relay, pull requests merged in 2024-11, with the labels that each got.

#3164 docs: Add `testing-guide.md` to document testing best practices
  README.md
  docs/testing-guide.md
Labels: documentation, enhancement

#3189 fix: stabilized HBAR Rate Limit acceptance tests
  docs/configuration.md
  packages/config-service/src/services/globalConfig.ts
  packages/server/tests/acceptance/hbarLimiter.spec.ts
  packages/server/tests/localAcceptance.env
Labels: P1, Internal

#3161 fix: Adds retry to send raw transaction
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/errors/SDKClientError.ts
  packages/relay/src/lib/services/hapiService/hapiService.ts
  packages/relay/tests/lib/eth/eth_sendRawTransaction.spec.ts
  packages/relay/tests/lib/sdkClient.spec.ts
  packages/relay/tests/lib/services/metricService/metricService.spec.ts
Labels: enhancement

#3206 build(deps): [Snyk] Upgrade @graphprotocol/graph-cli from 0.85.0 to 0.86.0
  tools/subgraph-example/subgraph/package.json
Labels: dependencies

#3205 build(deps): [Snyk] Upgrade ethers from 6.13.3 to 6.13.4
  k6/package-lock.json
  k6/package.json
Labels: dependencies

#3208 fix: Adds retry to send raw transaction (#3161)
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/errors/SDKClientError.ts
  packages/relay/src/lib/services/hapiService/hapiService.ts
  packages/relay/tests/lib/eth/eth_sendRawTransaction.spec.ts
  packages/relay/tests/lib/sdkClient.spec.ts
  packages/relay/tests/lib/services/metricService/metricService.spec.ts
Labels: enhancement

#3210 fix: added null check for nullable values in formatContractResult()
  packages/relay/src/formatters.ts
  packages/relay/tests/lib/eth/eth_getTransactionByBlockHashAndIndex.spec.ts
  packages/relay/tests/lib/eth/eth_getTransactionByBlockNumberAndIndex.spec.ts
  packages/relay/tests/lib/formatters.spec.ts
Labels: bug

#3211 chore: cherry picked #3120 to release/0.59
  packages/relay/src/formatters.ts
  packages/relay/tests/lib/eth/eth_getTransactionByBlockHashAndIndex.spec.ts
  packages/relay/tests/lib/eth/eth_getTransactionByBlockNumberAndIndex.spec.ts
  packages/relay/tests/lib/formatters.spec.ts
Labels: process

#3194 ci: Update per Q3 audit findings
  .github/CODEOWNERS
  .github/workflows/dapp.yml
Labels: github_actions

#3217 feat: cherry-pick #3177 remove transactions with status `INVALID_ACCOUNT_ID` from block…
  docs/configuration.md
  packages/config-service/src/services/globalConfig.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/utils.ts
  packages/relay/tests/lib/eth/eth_getBlockByNumber.spec.ts
  packages/relay/tests/lib/utils.spec.ts
Labels: enhancement

#3216 chore: reverted "fix: added null check for nullable values in formatContractResult() (#3210)"
  packages/relay/src/formatters.ts
  packages/relay/tests/lib/eth/eth_getTransactionByBlockHashAndIndex.spec.ts
  packages/relay/tests/lib/eth/eth_getTransactionByBlockNumberAndIndex.spec.ts
  packages/relay/tests/lib/formatters.spec.ts
Labels: Internal

#3213 build(deps): [Snyk] Upgrade ethers from 6.13.3 to 6.13.4
  dapp-example/package-lock.json
  dapp-example/package.json
Labels: dependencies

#3221 fix: Added the root package.json file to the
  scripts/.bump-version.js
Labels: bug

#3222 ci: Fix check for forked repository on PR
  .github/workflows/flow-pr-title-check.yml
Labels: github_actions

#3190 test: added e2e tests for multiple users across various tiers
  packages/server/tests/acceptance/hbarLimiter.spec.ts
Labels: Internal

#3230 build(deps): [Snyk] Upgrade @hashgraph/sdk from 2.51.0 to 2.52.0
  dapp-example/package-lock.json
  dapp-example/package.json
Labels: dependencies

#3233 feat: fix wrong cache key on `eth_getBlockByHash` (#3232)
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
Labels: bug

#3226 fix WS_NEW_HEADS_ENABLED default
  packages/config-service/src/services/globalConfig.ts
Labels: good first issue, Internal

#3238 fix: Added the TEST_INITIAL_ACCOUNT_STARTING_BALANCE to the GlobalCon…
  packages/config-service/src/services/globalConfig.ts
Labels: bug

#3241 fix: Strip leading zeros in signature v and s values coming from the mirror node, in tests.
  packages/ws-server/tests/acceptance/getTransactionByHash.spec.ts
Labels: bug

#3229 fix: modified sendRawTransaction to also poll MN for transaction's validity for Timeout and ConnectionDropped error
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/services/hapiService/hapiService.ts
  packages/relay/tests/lib/eth/eth_sendRawTransaction.spec.ts
  packages/relay/tests/lib/sdkClient.spec.ts
  packages/relay/tests/lib/services/metricService/metricService.spec.ts
Labels: enhancement

#3245 chore: Upgrade node version to 20.
  .github/workflows/conformity-workflow.yml
  .github/workflows/dapp.yml
  .github/workflows/test.yml
Labels: Internal

#3248 build(dep): [Snyk] Upgrade web3 from 4.13.0 to 4.14.0
  tools/web3js-example/package-lock.json
  tools/web3js-example/package.json
Labels: dependencies

#3154 refactor: add log level guards to prevent unnecessary string generation
  packages/relay/src/lib/clients/cache/localLRUCache.ts
  packages/relay/src/lib/clients/cache/redisCache.ts
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/config/hbarSpendingPlanConfigService.ts
  packages/relay/src/lib/db/repositories/hbarLimiter/ethAddressHbarSpendingPlanRepository.ts
  packages/relay/src/lib/db/repositories/hbarLimiter/hbarSpendingPlanRepository.ts
  packages/relay/src/lib/db/repositories/hbarLimiter/ipAddressHbarSpendingPlanRepository.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/poller.ts
  packages/relay/src/lib/precheck.ts
  packages/relay/src/lib/services/debugService/index.ts
  packages/relay/src/lib/services/ethService/ethCommonService/index.ts
  packages/relay/src/lib/services/ethService/ethFilterService/index.ts
  packages/relay/src/lib/services/hbarLimitService/index.ts
  packages/relay/src/lib/services/metricService/metricService.ts
  packages/relay/src/lib/subscriptionController.ts
  packages/relay/tests/lib/poller.spec.ts
  packages/relay/tests/lib/subscriptionController.spec.ts
  packages/relay/tests/redisInMemoryServer.ts
  packages/server/src/server.ts
  packages/server/tests/acceptance/hbarLimiter.spec.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
  packages/server/tests/clients/metricsClient.ts
  packages/server/tests/clients/mirrorClient.ts
  packages/server/tests/clients/relayClient.ts
  packages/server/tests/clients/servicesClient.ts
  packages/server/tests/helpers/assertions.ts
  packages/server/tests/helpers/utils.ts
  packages/ws-server/src/controllers/index.ts
  packages/ws-server/src/metrics/connectionLimiter.ts
  packages/ws-server/src/webSocketServer.ts
Labels: enhancement, P3, perf, good first issue candidate, hacktoberfest

#3175 fix: updated .github/release.yaml to include `internal` and `github_action` labeled PRs
  .github/release.yaml
Labels: good first issue, good first issue candidate, hacktoberfest, Internal

#3107 feat: added redis in docker-compose
  docker-compose.yml
Labels: good first issue, good first issue candidate, hacktoberfest, Internal

#3150 chore: add active users counter per rate limiter duration
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth/eth_call.spec.ts
  packages/relay/tests/lib/eth/eth_sendRawTransaction.spec.ts
Labels: enhancement

#3254 fix: `eth_getBlockByHash` is using invalid cache record
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
Labels: bug

#3255 chore: cherry picked #3254 to release/0.56
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
Labels: process

#3256 chore: Reduce initial account funding
  packages/server/tests/mainnetAcceptance.env
  packages/server/tests/previewnetAcceptance.env
  packages/server/tests/testnetAcceptance.env
Labels: enhancement

#3260 build(deps): [Snyk] Upgrade @graphprotocol/graph-cli from 0.86.0 to 0.87.0
  tools/subgraph-example/subgraph/package.json
Labels: dependencies

#3244 build(dep): bump hedera-local-node to the latest version
  package-lock.json
  package.json
Labels: dependencies

#3261 feat: add eslint to be run pre commit
  .eslintrc.js
  .husky/pre-commit
  package-lock.json
  package.json
  packages/relay/tests/lib/sdkClient.spec.ts
Labels: Internal

#3252 fix: Allow the HBar Rate Limiter to be disabled.
  .github/workflows/acceptance.yml
  package.json
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/services/hbarLimitService/IHbarLimitService.ts
  packages/relay/src/lib/services/hbarLimitService/index.ts
  packages/relay/tests/lib/services/hbarLimitService/hbarLimitService.spec.ts
  packages/server/tests/acceptance/hbarLimiter.spec.ts
Labels: bug

#3264 fix: Added gas deviation to the release-light tests.
  packages/server/tests/acceptance/rpc_batch1.spec.ts
Labels: bug

#3269 chore: cherry pick #3252 to release/0.60
  .github/workflows/acceptance.yml
  package.json
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/services/hbarLimitService/IHbarLimitService.ts
  packages/relay/src/lib/services/hbarLimitService/index.ts
  packages/relay/tests/lib/services/hbarLimitService/hbarLimitService.spec.ts
  packages/server/tests/acceptance/hbarLimiter.spec.ts
Labels: process

#3277 chore: cherry pick #3268 to release/0.60
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth/eth_sendRawTransaction.spec.ts
Labels: process

#3276 build(deps): bump `hedera-local` version from 2.32.2 to 2.32.5
  package-lock.json
  package.json
Labels: dependencies

#3284 chore: update workflow permissions for github token
  .github/workflows/acceptance-workflow.yml
Labels: github_action

#3282 docs: added design docs for eth_sendRawTransaction fast transaction hash return
  docs/design/sendRawTransaction-fast-return.md
Labels: documentation, enhancement

#3292 feat: expose node account id in relay logging of failed transactions
  package-lock.json
  packages/relay/package.json
  packages/relay/src/lib/clients/sdkClient.ts
  packages/server/package.json
  packages/ws-server/package.json
Labels: enhancement

#3291 ci: replace release notes generator action with one maintained by stepsecurity
  .github/workflows/release-automation.yml
Labels: github_action

#3273 feat: enabled fast return on eth_sendRawTransaction
  docs/configuration.md
  package-lock.json
  package.json
  packages/config-service/src/services/globalConfig.ts
  packages/relay/package.json
  packages/relay/src/lib/eth.ts
  packages/relay/src/utils.ts
  packages/relay/tests/lib/eth/eth_sendRawTransaction.spec.ts
  packages/relay/tests/lib/utils.spec.ts
  packages/relay/tests/test.env
  packages/server/tests/acceptance/conformityTests.spec.ts
  packages/server/tests/acceptance/hbarLimiter.spec.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
  packages/server/tests/acceptance/rpc_batch3.spec.ts
  packages/server/tests/clients/relayClient.ts
  packages/server/tests/localAcceptance.env
  packages/ws-server/tests/acceptance/getStorageAt.spec.ts
Labels: enhancement

#3301 build: Bump versions for v0.62.0-SNAPSHOT
  charts/hedera-json-rpc-relay-websocket/Chart.yaml
  charts/hedera-json-rpc-relay/Chart.yaml
  charts/hedera-json-rpc/Chart.yaml
  docs/openrpc.json
  package-lock.json
  package.json
  packages/config-service/package.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: process

#3297 feat: move current node account id logging logic into sdk client
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/errors/SDKClientError.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/errors/SDKClientError.spec.ts
Labels: enhancement

#3285 chore: extend the format checking via openrpcjson
  docs/openrpc.json
  packages/server/tests/acceptance/conformityTests.spec.ts
  packages/server/tests/acceptance/data/conformity-tests-batch-2.json
Labels: internal
