Repository hiero-ledger/hiero-json-rpc-relay, pull requests merged in 2024-10, with the labels that each got.

#2953 feat: add `eth_call`, `eth_getLogs` and `eth_estimateGas` coverage to conformity tests
  packages/server/tests/acceptance/conformityTests.spec.ts
  packages/server/tests/acceptance/data/conformity-tests-batch-2.json
  packages/server/tests/acceptance/data/conformity-tests-batch-3.json
  packages/server/tests/acceptance/data/conformity-tests-batch-4.json
Labels: enhancement

#3073 feat: enabled configurable server host for the Relay server
  docs/configuration.md
  packages/relay/src/lib/constants.ts
  packages/server/src/index.ts
  packages/server/tests/acceptance/index.spec.ts
  packages/server/tests/acceptance/serverConfig.spec.ts
  packages/server/tests/integration/server.spec.ts
  packages/ws-server/src/index.ts
Labels: enhancement

#3014 refactor: configurations of `HbarLimitService`
  docs/configuration.md
  docs/design/hbar-limiter.md
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/db/entities/hbarLimiter/hbarSpendingPlan.ts
  packages/relay/src/lib/db/repositories/hbarLimiter/ethAddressHbarSpendingPlanRepository.ts
  packages/relay/src/lib/db/repositories/hbarLimiter/hbarSpendingPlanRepository.ts
  packages/relay/src/lib/db/repositories/hbarLimiter/ipAddressHbarSpendingPlanRepository.ts
  packages/relay/src/lib/db/types/hbarLimiter/hbarSpendingPlan.ts
  packages/relay/src/lib/relay.ts
  packages/relay/src/lib/services/hbarLimitService/index.ts
  packages/relay/tests/lib/clients/redisCache.spec.ts
  packages/relay/tests/lib/eth/eth-helpers.ts
  packages/relay/tests/lib/ethGetBlockBy.spec.ts
  packages/relay/tests/lib/openrpc.spec.ts
  packages/relay/tests/lib/poller.spec.ts
  packages/relay/tests/lib/repositories/hbarLimiter/ethAddressHbarSpendingPlanRepository.spec.ts
  packages/relay/tests/lib/repositories/hbarLimiter/hbarSpendingPlanRepository.spec.ts
  packages/relay/tests/lib/repositories/hbarLimiter/ipAddressHbarSpendingPlanRepository.spec.ts
  packages/relay/tests/lib/sdkClient.spec.ts
  packages/relay/tests/lib/services/hbarLimitService/hbarLimitService.spec.ts
  packages/relay/tests/lib/services/metricService/metricService.spec.ts
Labels: documentation, enhancement, design

#3074 feat: enabled configurable server host for the Relay server (#3073)
  docs/configuration.md
  packages/relay/src/lib/constants.ts
  packages/server/src/index.ts
  packages/server/tests/acceptance/index.spec.ts
  packages/server/tests/acceptance/serverConfig.spec.ts
  packages/server/tests/integration/server.spec.ts
  packages/ws-server/src/index.ts
Labels: bug

#3061 fix: SDKClient timeouts are not getting logged with requestIds.
  packages/relay/src/lib/clients/sdkClient.ts
Labels: bug

#3077 fix: pr check ignore issues check external projects
  .github/scripts/check-pr.js
Labels: bug

#3069 build(deps): [Snyk] Upgrade @hashgraph/sdk from 2.50.0 to 2.51.0
  dapp-example/package-lock.json
  dapp-example/package.json
Labels: dependencies

#3080 feat: change units of the value in eth gettransactionbyhash result
  packages/relay/src/formatters.ts
  packages/relay/src/lib/constants.ts
  packages/relay/tests/lib/eth/eth-config.ts
  packages/relay/tests/lib/formatters.spec.ts
  packages/server/tests/helpers/assertions.ts
  scripts/signTransaction.js
Labels: enhancement

#3081 feat: change units of the value in eth gettransactionbyhash result (#…
  packages/relay/src/formatters.ts
  packages/relay/src/lib/constants.ts
  packages/relay/tests/lib/eth/eth-config.ts
  packages/relay/tests/lib/formatters.spec.ts
  packages/server/tests/helpers/assertions.ts
  scripts/signTransaction.js
Labels: enhancement

#3076 build(dep): [Snyk] Upgrade @graphprotocol/graph-cli from 0.81.0 to 0.82.0
  tools/subgraph-example/subgraph/package.json
Labels: dependencies

#3070 feat: Brownie example and description
  tools/brownie-example/.gitignore
  tools/brownie-example/LICENSE
  tools/brownie-example/README.md
  tools/brownie-example/contracts/Greeter.sol
  tools/brownie-example/requirements.txt
  tools/brownie-example/scripts/deploy.py
  tools/brownie-example/tests/conftest.py
  tools/brownie-example/tests/test_rpc.py
Labels: ArianeLabs

#3060 feat: Add release testing workflow for public networks
  .github/workflows/acceptance-public.yml
  .github/workflows/acceptance-workflow.yml
  packages/server/tests/mainnetAcceptance.env
  packages/server/tests/previewnetAcceptance.env
  packages/server/tests/testnetAcceptance.env
Labels: enhancement, github_actions

#3087 fix: delete unnecessary script signTransaction
  scripts/signTransaction.js
Labels: bug

#3085 build: (deps) [Snyk] Upgrade web3 from 4.12.1 to 4.13.0
  tools/web3js-example/package-lock.json
  tools/web3js-example/package.json
Labels: dependencies

#3000 feat: Wagmi example usage with Hedera
  tools/wagmi-example/.gitignore
  tools/wagmi-example/.npmrc
  tools/wagmi-example/README.md
  tools/wagmi-example/biome.json
  tools/wagmi-example/contract/Greeter.sol
  tools/wagmi-example/contract/contract_Greeter_sol_Greeter.bin
  tools/wagmi-example/contract/contract_Greeter_sol_Greeter.json
  tools/wagmi-example/index.html
  tools/wagmi-example/package.json
  tools/wagmi-example/src/App.tsx
  tools/wagmi-example/src/components/Contract.tsx
  tools/wagmi-example/src/components/Profile.tsx
  tools/wagmi-example/src/hooks/use-balance.ts
  tools/wagmi-example/src/hooks/use-deploy.ts
  tools/wagmi-example/src/index.css
  tools/wagmi-example/src/main.tsx
  tools/wagmi-example/src/vite-env.d.ts
  tools/wagmi-example/src/wagmi.ts
  tools/wagmi-example/tsconfig.json
  tools/wagmi-example/vite.config.ts
Labels: enhancement, ArianeLabs

#3022 test: add helper method for overriding env variables
  packages/relay/src/lib/services/ethService/ethFilterService/index.ts
  packages/relay/tests/helpers.ts
  packages/relay/tests/lib/clients/localLRUCache.spec.ts
  packages/relay/tests/lib/clients/redisCache.spec.ts
  packages/relay/tests/lib/eth/eth_call.spec.ts
  packages/relay/tests/lib/eth/eth_estimateGas.spec.ts
  packages/relay/tests/lib/eth/eth_feeHistory.spec.ts
  packages/relay/tests/lib/eth/eth_gasPrice.spec.ts
  packages/relay/tests/lib/eth/eth_getBalance.spec.ts
  packages/relay/tests/lib/eth/eth_getBlockByHash.spec.ts
  packages/relay/tests/lib/eth/eth_getBlockByNumber.spec.ts
  packages/relay/tests/lib/eth/eth_getBlockTransactionCountByHash.spec.ts
  packages/relay/tests/lib/eth/eth_getCode.spec.ts
  packages/relay/tests/lib/eth/eth_getLogs.spec.ts
  packages/relay/tests/lib/eth/eth_getStorageAt.spec.ts
  packages/relay/tests/lib/eth/eth_getTransactionByBlockNumberAndIndex.spec.ts
  packages/relay/tests/lib/eth/eth_getTransactionCount.spec.ts
  packages/relay/tests/lib/eth/eth_getTransactionReceipt.spec.ts
  packages/relay/tests/lib/eth/eth_sendRawTransaction.spec.ts
  packages/relay/tests/lib/ethGetBlockBy.spec.ts
  packages/relay/tests/lib/formatters.spec.ts
  packages/relay/tests/lib/hapiService.spec.ts
  packages/relay/tests/lib/hbarLimiter.spec.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
  packages/relay/tests/lib/net.spec.ts
  packages/relay/tests/lib/openrpc.spec.ts
  packages/relay/tests/lib/precheck.spec.ts
  packages/relay/tests/lib/relay.spec.ts
  packages/relay/tests/lib/repositories/hbarLimiter/ethAddressHbarSpendingPlanRepository.spec.ts
  packages/relay/tests/lib/repositories/hbarLimiter/hbarSpendingPlanRepository.spec.ts
  packages/relay/tests/lib/repositories/hbarLimiter/ipAddressHbarSpendingPlanRepository.spec.ts
  packages/relay/tests/lib/sdkClient.spec.ts
  packages/relay/tests/lib/services/cacheService/cacheService.spec.ts
  packages/relay/tests/lib/services/debugService/debug.spec.ts
  packages/relay/tests/lib/services/eth/filter.spec.ts
  packages/relay/tests/lib/services/metricService/metricService.spec.ts
  packages/relay/tests/lib/subscriptionController.spec.ts
  packages/relay/tests/lib/utils.spec.ts
  packages/relay/tests/lib/web3.spec.ts
  packages/server/tests/acceptance/cacheService.spec.ts
  packages/server/tests/acceptance/hbarLimiter.spec.ts
  packages/server/tests/acceptance/rpc_batch3.spec.ts
  packages/server/tests/integration/koaJsonRpc/utils.spec.ts
  packages/server/tests/integration/rateLimiter.spec.ts
  packages/server/tests/integration/server.spec.ts
  packages/ws-server/tests/acceptance/batchRequest.spec.ts
  packages/ws-server/tests/acceptance/subscribe.spec.ts
  packages/ws-server/tests/acceptance/subscribeNewHeads.spec.ts
  packages/ws-server/tests/acceptance/validations.spec.ts
  packages/ws-server/tests/helper/index.ts
  packages/ws-server/tests/unit/utils.spec.ts
  packages/ws-server/tests/unit/validations.spec.ts
Labels: enhancement, Technical Debt

#3058 feat: implement configuration to pre-populate the cache with spending plans
  docs/configuration.md
  docs/design/hbar-limiter.md
  packages/relay/src/lib/clients/cache/localLRUCache.ts
  packages/relay/src/lib/clients/cache/redisCache.ts
  packages/relay/src/lib/config/hbarSpendingPlanConfigService.ts
  packages/relay/src/lib/db/entities/hbarLimiter/hbarSpendingPlan.ts
  packages/relay/src/lib/db/repositories/hbarLimiter/ethAddressHbarSpendingPlanRepository.ts
  packages/relay/src/lib/db/repositories/hbarLimiter/hbarSpendingPlanRepository.ts
  packages/relay/src/lib/db/repositories/hbarLimiter/ipAddressHbarSpendingPlanRepository.ts
  packages/relay/src/lib/db/types/hbarLimiter/hbarSpendingPlan.ts
  packages/relay/src/lib/db/types/hbarLimiter/subscriptionTier.ts
  packages/relay/src/lib/relay.ts
  packages/relay/src/lib/services/hbarLimitService/index.ts
  packages/relay/src/lib/types/spendingPlanConfig.ts
  packages/relay/src/utils.ts
  packages/relay/tests/lib/clients/localLRUCache.spec.ts
  packages/relay/tests/lib/clients/redisCache.spec.ts
  packages/relay/tests/lib/config/hbarSpendingPlanConfigService.spec.ts
  packages/relay/tests/lib/relay.spec.ts
  packages/relay/tests/lib/repositories/hbarLimiter/ethAddressHbarSpendingPlanRepository.spec.ts
  packages/relay/tests/lib/repositories/hbarLimiter/hbarSpendingPlanRepository.spec.ts
  packages/relay/tests/lib/repositories/hbarLimiter/ipAddressHbarSpendingPlanRepository.spec.ts
  packages/relay/tests/lib/services/cacheService/cacheService.spec.ts
  packages/relay/tests/lib/services/hbarLimitService/hbarLimitService.spec.ts
  packages/server/tests/integration/server.spec.ts
  spendingPlansConfig.example.json
  tools/wagmi-example/vite.config.ts
Labels: enhancement, P1

#3088 feat: eth_call revert error message is too long, and should not be a REVERT but a BAD Request Response
  packages/server/src/validator/constants.ts
  packages/server/src/validator/objectTypes.ts
  packages/server/src/validator/types.ts
  packages/server/tests/integration/server.spec.ts
  packages/server/tests/integration/validator.spec.ts
Labels: bug

#3089 feat: add maxAttempts parameter to the acceptance test workflow
  .github/workflows/acceptance-public.yml
  .github/workflows/acceptance-workflow.yml
Labels: enhancement

#3100 chore: Set proper limits for the redesigned HBAR limiter
  charts/hedera-json-rpc-relay/value-test.yaml
  charts/hedera-json-rpc-relay/values.yaml
  dapp-example/localDappCI.env
  docs/configuration.md
  packages/relay/src/lib/constants.ts
  packages/server/tests/acceptance/htsPrecompile/tokenCreate.spec.ts
  packages/server/tests/acceptance/htsPrecompile/tokenManagement.spec.ts
  packages/server/tests/localAcceptance.env
  packages/server/tests/mainnetAcceptance.env
  packages/server/tests/previewnetAcceptance.env
  packages/server/tests/testnetAcceptance.env
Labels: enhancement, P1

#3117 fix: added newFilter to paramRearrangementMap for WS server
  packages/ws-server/src/controllers/index.ts
  packages/ws-server/src/utils/utils.ts
  packages/ws-server/tests/unit/utils.spec.ts
Labels: bug

#3119 fix: added newFilter to paramRearrangementMap for WS server (#3117)
  packages/ws-server/src/controllers/index.ts
  packages/ws-server/src/utils/utils.ts
  packages/ws-server/tests/unit/utils.spec.ts
Labels: bug

#3123 build: (deps)[Snyk] Upgrade @graphprotocol/graph-cli from 0.82.0 to 0.84.0
  tools/subgraph-example/subgraph/package.json
Labels: dependencies

#3128 chore: update codeowners
  .github/CODEOWNERS
Labels: enhancement, P2

#3131 fix: Spelling fix in the logged messages.
  packages/relay/src/lib/eth.ts
Labels: bug

#3110 feat: replaced HbarLimit module with the new HbarLimitService class
  package.json
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/db/repositories/hbarLimiter/ethAddressHbarSpendingPlanRepository.ts
  packages/relay/src/lib/db/repositories/hbarLimiter/ipAddressHbarSpendingPlanRepository.ts
  packages/relay/src/lib/hbarlimiter/index.ts
  packages/relay/src/lib/relay.ts
  packages/relay/src/lib/services/hapiService/hapiService.ts
  packages/relay/src/lib/services/hbarLimitService/IHbarLimitService.ts
  packages/relay/src/lib/services/hbarLimitService/index.ts
  packages/relay/src/lib/services/metricService/metricService.ts
  packages/relay/src/lib/types/events.ts
  packages/relay/src/utils.ts
  packages/relay/tests/helpers.ts
  packages/relay/tests/lib/eth/eth-helpers.ts
  packages/relay/tests/lib/ethGetBlockBy.spec.ts
  packages/relay/tests/lib/hapiService.spec.ts
  packages/relay/tests/lib/hbarLimiter.spec.ts
  packages/relay/tests/lib/openrpc.spec.ts
  packages/relay/tests/lib/sdkClient.spec.ts
  packages/relay/tests/lib/services/hbarLimitService/hbarLimitService.spec.ts
  packages/relay/tests/lib/services/metricService/metricService.spec.ts
  packages/relay/tests/lib/utils.spec.ts
  packages/server/tests/acceptance/hbarLimiter.spec.ts
  packages/server/tests/localAcceptance.env
  packages/server/tests/mainnetAcceptance.env
  packages/server/tests/previewnetAcceptance.env
  packages/server/tests/testnetAcceptance.env
  packages/server/tests/types/AliasAccount.ts
Labels: enhancement

#3135 feat: replaced HbarLimit module with the new HbarLimitService
  package.json
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/db/repositories/hbarLimiter/ethAddressHbarSpendingPlanRepository.ts
  packages/relay/src/lib/db/repositories/hbarLimiter/ipAddressHbarSpendingPlanRepository.ts
  packages/relay/src/lib/hbarlimiter/index.ts
  packages/relay/src/lib/relay.ts
  packages/relay/src/lib/services/hapiService/hapiService.ts
  packages/relay/src/lib/services/hbarLimitService/IHbarLimitService.ts
  packages/relay/src/lib/services/hbarLimitService/index.ts
  packages/relay/src/lib/services/metricService/metricService.ts
  packages/relay/src/lib/types/events.ts
  packages/relay/src/utils.ts
  packages/relay/tests/helpers.ts
  packages/relay/tests/lib/eth/eth-helpers.ts
  packages/relay/tests/lib/ethGetBlockBy.spec.ts
  packages/relay/tests/lib/hapiService.spec.ts
  packages/relay/tests/lib/hbarLimiter.spec.ts
  packages/relay/tests/lib/openrpc.spec.ts
  packages/relay/tests/lib/sdkClient.spec.ts
  packages/relay/tests/lib/services/hbarLimitService/hbarLimitService.spec.ts
  packages/relay/tests/lib/services/metricService/metricService.spec.ts
  packages/relay/tests/lib/utils.spec.ts
  packages/server/tests/acceptance/hbarLimiter.spec.ts
  packages/server/tests/localAcceptance.env
  packages/server/tests/mainnetAcceptance.env
  packages/server/tests/previewnetAcceptance.env
  packages/server/tests/testnetAcceptance.env
  packages/server/tests/types/AliasAccount.ts
Labels: enhancement

#3133 feat: State the default log level in the documentation.
  docs/configuration.md
Labels: enhancement

#3101 chore: add another batch of conformity tests
  packages/server/tests/acceptance/conformityTests.spec.ts
  packages/server/tests/acceptance/data/conformity-tests-batch-5.json
Labels: enhancement

#3141 fix: do not link IP addresses of general users
  packages/relay/src/lib/db/repositories/hbarLimiter/ethAddressHbarSpendingPlanRepository.ts
  packages/relay/src/lib/db/repositories/hbarLimiter/ipAddressHbarSpendingPlanRepository.ts
  packages/relay/src/lib/services/hbarLimitService/index.ts
  packages/relay/tests/lib/services/hbarLimitService/hbarLimitService.spec.ts
  packages/server/tests/acceptance/hbarLimiter.spec.ts
Labels: bug, enhancement, P1

#3108 ci: Updating workflows/actions to be compatible to and updating to the step-security maintained version.
  .github/workflows/acceptance-public.yml
  .github/workflows/acceptance-workflow.yml
  .github/workflows/acceptance.yml
  .github/workflows/manual-testing.yml
  .github/workflows/release-acceptance.yml
  .github/workflows/test.yml
Labels: github_actions

#3149 build: (deps) [Snyk] Upgrade ethers from 6.13.2 to 6.13.3
  k6/package-lock.json
  k6/package.json
Labels: dependencies

#3146 feat: Updated dashboards due to on going HBar Rate Limiter work.
  charts/hedera-json-rpc/dashboards/hedera-json-rpc-relay-http-server.json
  charts/hedera-json-rpc/dashboards/webSocketServer.json
Labels: enhancement

#3148 feat: add env masking for values starting with known secrets prefixes
  packages/config-service/src/services/loggerService.ts
  packages/config-service/tests/src/services/loggerService.spec.ts
Labels: enhancement

#3139 feat: add additional tests for unexpected fail appends failures during contract creation via `eth_sendRawTransaction`
  packages/relay/tests/lib/eth/eth_sendRawTransaction.spec.ts
  packages/relay/tests/lib/sdkClient.spec.ts
Labels: enhancement

#3147 test: added e2e test for EXTENDED and PRIVILEGED tier users
  package.json
  packages/relay/src/lib/services/hbarLimitService/index.ts
  packages/server/tests/acceptance/hbarLimiter.spec.ts
  packages/server/tests/localAcceptance.env
  packages/server/tests/previewnetAcceptance.env
  packages/server/tests/testSpendingPlansConfig.json
  packages/server/tests/testnetAcceptance.env
Labels: enhancement

#3140 fix: Protect preconfigured spending plans from being deleted automatically in `LRUCache`
  package-lock.json
  packages/config-service/src/services/globalConfig.ts
  packages/relay/src/lib/clients/cache/localLRUCache.ts
  packages/relay/src/lib/config/hbarSpendingPlanConfigService.ts
  packages/relay/src/lib/db/repositories/hbarLimiter/ethAddressHbarSpendingPlanRepository.ts
  packages/relay/src/lib/db/repositories/hbarLimiter/hbarSpendingPlanRepository.ts
  packages/relay/src/lib/db/repositories/hbarLimiter/ipAddressHbarSpendingPlanRepository.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/relay.ts
  packages/relay/src/lib/services/cacheService/cacheService.ts
  packages/relay/tests/helpers.ts
  packages/relay/tests/lib/clients/localLRUCache.spec.ts
  packages/relay/tests/lib/config/hbarSpendingPlanConfigService.spec.ts
  packages/relay/tests/lib/repositories/hbarLimiter/ethAddressHbarSpendingPlanRepository.spec.ts
  packages/relay/tests/lib/repositories/hbarLimiter/hbarSpendingPlanRepository.spec.ts
  packages/relay/tests/lib/repositories/hbarLimiter/ipAddressHbarSpendingPlanRepository.spec.ts
Labels: bug, enhancement, P1

#3157 build(dep): [Snyk] Upgrade @graphprotocol/graph-cli from 0.84.0 to 0.85.0
  tools/subgraph-example/subgraph/package.json
Labels: dependencies

#3124 ci: Updaiting workflow permissions and adding hardend runner per step-security.
  .github/workflows/acceptance-workflow.yml
  .github/workflows/charts.yml
  .github/workflows/conformity-workflow.yml
  .github/workflows/dapp.yml
  .github/workflows/dev-tool-workflow.yml
  .github/workflows/flow-pr-title-check.yml
  .github/workflows/image-build.yml
  .github/workflows/postman.yml
  .github/workflows/pr-label-milestone-check.yml
  .github/workflows/release-acceptance.yml
  .github/workflows/release-integration.yml
  .github/workflows/release-production.yml
  .github/workflows/subgraph.yml
Labels: github_actions

#3166 ci: Fixing workflow permissions for uploading docker images.
  .github/workflows/release-integration.yml
Labels: github_actions

#3158 fix: Inconsistent handling of failed EVM transactions
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth/eth_getBlockByHash.spec.ts
  packages/relay/tests/lib/eth/eth_getBlockByNumber.spec.ts
Labels: bug, P1

#3170 chore: Bump threshold of memory leak alerts
  packages/server/tests/helpers/utils.ts
Labels: bug

#3179 build: Bump versions for v0.60.0-SNAPSHOT
  charts/hedera-json-rpc-relay-websocket/Chart.yaml
  charts/hedera-json-rpc-relay/Chart.yaml
  charts/hedera-json-rpc/Chart.yaml
  docs/openrpc.json
  package-lock.json
  packages/config-service/package.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: enhancement, dependencies

#3183 ci(bug): Update permissions in JSON rpc relay for GITHUB_TOKEN
  .github/workflows/release-production.yml
Labels: bug, github_actions

#3181 chore: divided hbar limtier tests into different batches
  .github/workflows/acceptance.yml
  package.json
  packages/server/tests/acceptance/hbarLimiter.spec.ts
Labels: Internal

#3173 chore: Adds eslint rules in eslintrc
  .eslintrc.js
  .eslintrc.yml
  package-lock.json
  package.json
  packages/config-service/package.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: Internal

#3186 ci(bug): Update permissions in JSON rpc relay for GITHUB_TOKEN (#3183)
  .github/workflows/acceptance.yml
  .github/workflows/release-production.yml
  package.json
  packages/server/tests/acceptance/hbarLimiter.spec.ts
Labels: bug

#3196 fix: skipped title check CI job for forked PRs
  .github/workflows/flow-pr-title-check.yml
Labels: Internal

#3193 fix: Wrong metrics in the report of the WS performance tests
  k6/src/scenarios/test-ws/common.js
  k6/src/scenarios/test-ws/eth_chainId.js
  k6/src/scenarios/test-ws/eth_subscribe_logs.js
  k6/src/scenarios/test-ws/eth_subscribe_newHeads.js
  k6/src/scenarios/test-ws/eth_subscribe_newPendingTransactions.js
  k6/src/scenarios/ws-apis.js
Labels: bug, process

#3198 fix: Capture the npm_package_version
  package-lock.json
  package.json
  packages/config-service/src/services/globalConfig.ts
  packages/config-service/tests/src/services/validationService.spec.ts
  packages/server/tests/acceptance/index.spec.ts
Labels: bug

#3153 feat: Added ability to load spending plans from environment variable.
  docs/configuration.md
  docs/design/hbar-limiter.md
  packages/config-service/src/services/globalConfig.ts
  packages/config-service/tests/src/services/loggerService.spec.ts
  packages/relay/src/lib/clients/cache/localLRUCache.ts
  packages/relay/src/lib/config/hbarSpendingPlanConfigService.ts
  packages/relay/tests/lib/config/hbarSpendingPlanConfigService.spec.ts
  packages/relay/tests/lib/relay.spec.ts
  packages/server/tests/acceptance/hbarLimiter.spec.ts
  packages/server/tests/localAcceptance.env
Labels: enhancement

#3200 fix: 3198 cherry pick npm package version
  package-lock.json
  package.json
  packages/config-service/src/services/globalConfig.ts
  packages/config-service/tests/src/services/validationService.spec.ts
  packages/server/tests/acceptance/index.spec.ts
Labels: bug

#3201 feat: Added ability to load spending plans from environment variable.…
  docs/configuration.md
  docs/design/hbar-limiter.md
  packages/config-service/src/services/globalConfig.ts
  packages/config-service/tests/src/services/loggerService.spec.ts
  packages/relay/src/lib/clients/cache/localLRUCache.ts
  packages/relay/src/lib/config/hbarSpendingPlanConfigService.ts
  packages/relay/tests/lib/config/hbarSpendingPlanConfigService.spec.ts
  packages/relay/tests/lib/relay.spec.ts
  packages/server/tests/acceptance/hbarLimiter.spec.ts
  packages/server/tests/localAcceptance.env
Labels: enhancement
