Repository hiero-ledger/hiero-json-rpc-relay, pull requests merged in 2024-12, with the labels that each got.

#3299 ci: Pass CODECOV_TOKEN to acceptance workflow
  .github/workflows/acceptance-public.yml
  .github/workflows/acceptance-workflow.yml
  .github/workflows/acceptance.yml
  .github/workflows/manual-testing.yml
Labels: github_action

#3307 fix: Add websocket-batch-n to needs clause in manual-testing
  .github/workflows/manual-testing.yml
Labels: github_action

#3303 build(dep): [Snyk] Upgrade web3 from 4.14.0 to 4.15.0
  tools/web3js-example/package-lock.json
  tools/web3js-example/package.json
Labels: dependencies

#3302 build(dep): [Snyk] Upgrade @graphprotocol/graph-cli from 0.87.0 to 0.88.0
  tools/subgraph-example/subgraph/package.json
Labels: dependencies

#3308 fix: added cache refreshing after subsequent getFilterLogs calls for the same filter
  packages/relay/src/lib/services/ethService/ethFilterService/index.ts
Labels: bug

#3304 fix: let 0 value transactions pass
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/precheck.ts
  packages/relay/tests/lib/eth/eth_estimateGas.spec.ts
  packages/relay/tests/lib/precheck.spec.ts
Labels: enhancement

#3305 feat: return hts token address for new fungible token
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/eth.ts
  packages/server/tests/acceptance/htsPrecompile/precompileCalls.spec.ts
Labels: enhancement

#3315 build(deps): [Snyk] Upgrade @graphprotocol/graph-cli from 0.88.0 to 0.89.0
  tools/subgraph-example/subgraph/package.json
Labels: dependencies

#3203 chore: Adds check for license header
  .eslintrc.js
  package-lock.json
  package.json
Labels: internal

#3323 fix: improves getContractAddressFromReceipt
  packages/relay/src/lib/eth.ts
Labels: internal

#3327 build: Bump versions for v0.63.0-SNAPSHOT
  charts/hedera-json-rpc-relay-websocket/Chart.yaml
  charts/hedera-json-rpc-relay/Chart.yaml
  charts/hedera-json-rpc/Chart.yaml
  docs/openrpc.json
  package-lock.json
  package.json
  packages/config-service/package.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: process

#3330 build(dep): [Snyk] Upgrade @emotion/styled from 11.13.0 to 11.13.5
  dapp-example/package-lock.json
  dapp-example/package.json
Labels: dependencies

#3334 build(dep): [Snyk] Upgrade @emotion/react from 11.13.3 to 11.13.5
  dapp-example/package-lock.json
  dapp-example/package.json
Labels: dependencies

#3335 chore: add maintainers as codeowners to all files
  .github/CODEOWNERS
Labels: Audit

#3310 chore: add precheck for receivers account in sendRawTransactionCheck
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/relay/src/lib/precheck.ts
  packages/relay/tests/lib/eth/eth_sendRawTransaction.spec.ts
  packages/relay/tests/lib/openrpc.spec.ts
  packages/relay/tests/lib/precheck.spec.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
Labels: enhancement

#3338 docs: update `hbar-limiter.md` with information about `OPERATOR` plans
  docs/design/hbar-limiter.md
Labels: documentation

#3316 feat: Add `OPERATOR` tier
  docs/configuration.md
  packages/config-service/src/services/globalConfig.ts
  packages/relay/src/lib/db/types/hbarLimiter/subscriptionTier.ts
  packages/relay/src/lib/relay.ts
  packages/relay/src/lib/services/hapiService/hapiService.ts
  packages/relay/src/lib/services/hbarLimitService/index.ts
  packages/relay/tests/lib/eth/eth-helpers.ts
  packages/relay/tests/lib/ethGetBlockBy.spec.ts
  packages/relay/tests/lib/hapiService.spec.ts
  packages/relay/tests/lib/openrpc.spec.ts
  packages/relay/tests/lib/sdkClient.spec.ts
  packages/relay/tests/lib/services/hbarLimitService/hbarLimitService.spec.ts
  packages/relay/tests/lib/services/metricService/metricService.spec.ts
  packages/server/tests/acceptance/hbarLimiter.spec.ts
Labels: enhancement, Technical Debt
