Repository hiero-ledger/hiero-json-rpc-relay, pull requests merged in 2025-05, with the labels that each got.

#3731 fix: fixes check to remove duplicates from transactionArray
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/ethGetBlockBy.spec.ts
Labels: bug

#3733 feat: HTSConnector fuzz testing
  tools/layer-zero-example/test/fuzzy-testing/.gitignore
  tools/layer-zero-example/test/fuzzy-testing/README.md
  tools/layer-zero-example/test/fuzzy-testing/foundry.toml
  tools/layer-zero-example/test/fuzzy-testing/lib/.gitkeep
  tools/layer-zero-example/test/fuzzy-testing/package-lock.json
  tools/layer-zero-example/test/fuzzy-testing/package.json
  tools/layer-zero-example/test/fuzzy-testing/script/.gitkeep
  tools/layer-zero-example/test/fuzzy-testing/src/ExampleHTSConnectorMock.sol
  tools/layer-zero-example/test/fuzzy-testing/src/HTSConnectorMock.sol
  tools/layer-zero-example/test/fuzzy-testing/src/hts/HederaTokenServiceMock.sol
  tools/layer-zero-example/test/fuzzy-testing/src/hts/KeyHelper.sol
  tools/layer-zero-example/test/fuzzy-testing/test/HTSConnectorFuzzTest.t.sol
Labels: enhancement

#3720 refactor: Create all service classes, moving buisness logic from eth to services
  packages/relay/src/formatters.ts
  packages/relay/src/index.ts
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/debug.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/factories/blockFactory.ts
  packages/relay/src/lib/factories/transactionFactory.ts
  packages/relay/src/lib/factories/transactionReceiptFactory.ts
  packages/relay/src/lib/modelConverter.ts
  packages/relay/src/lib/relay.ts
  packages/relay/src/lib/services/ethService/accountService/AccountService.ts
  packages/relay/src/lib/services/ethService/accountService/IAccountService.ts
  packages/relay/src/lib/services/ethService/blockService/BlockService.ts
  packages/relay/src/lib/services/ethService/blockService/IBlockService.ts
  packages/relay/src/lib/services/ethService/contractService/ContractService.ts
  packages/relay/src/lib/services/ethService/contractService/IContractService.ts
  packages/relay/src/lib/services/ethService/ethCommonService/CommonService.ts
  packages/relay/src/lib/services/ethService/ethCommonService/ICommonService.ts
  packages/relay/src/lib/services/ethService/ethFilterService/FilterService.ts
  packages/relay/src/lib/services/ethService/feeService/FeeService.ts
  packages/relay/src/lib/services/ethService/feeService/IFeeService.ts
  packages/relay/src/lib/services/ethService/index.ts
  packages/relay/src/lib/services/ethService/transactionService/ITransactionService.ts
  packages/relay/src/lib/services/ethService/transactionService/TransactionService.ts
  packages/relay/src/lib/services/index.ts
  packages/relay/src/lib/services/metricService/metricService.ts
  packages/relay/src/lib/types/events.ts
  packages/relay/src/lib/types/mirrorNode.ts
  packages/relay/src/logsBloomUtils.ts
  packages/relay/src/receiptsRootUtils.ts
  packages/relay/tests/assertions.ts
  packages/relay/tests/helpers.ts
  packages/relay/tests/lib/debug.spec.ts
  packages/relay/tests/lib/eth/eth-helpers.ts
  packages/relay/tests/lib/eth/eth_call.spec.ts
  packages/relay/tests/lib/eth/eth_estimateGas.spec.ts
  packages/relay/tests/lib/eth/eth_gasPrice.spec.ts
  packages/relay/tests/lib/eth/eth_getBalance.spec.ts
  packages/relay/tests/lib/eth/eth_getBlockByHash.spec.ts
  packages/relay/tests/lib/eth/eth_getBlockByNumber.spec.ts
  packages/relay/tests/lib/eth/eth_getBlockReceipts.spec.ts
  packages/relay/tests/lib/eth/eth_getCode.spec.ts
  packages/relay/tests/lib/eth/eth_getStorageAt.spec.ts
  packages/relay/tests/lib/eth/eth_getTransactionByBlockHashAndIndex.spec.ts
  packages/relay/tests/lib/eth/eth_getTransactionByBlockNumberAndIndex.spec.ts
  packages/relay/tests/lib/eth/eth_getTransactionCount.spec.ts
  packages/relay/tests/lib/eth/eth_getTransactionReceipt.spec.ts
  packages/relay/tests/lib/eth/eth_sendRawTransaction.spec.ts
  packages/relay/tests/lib/ethGetBlockBy.spec.ts
  packages/relay/tests/lib/formatters.spec.ts
  packages/relay/tests/lib/logsBloomUtils.spec.ts
  packages/relay/tests/lib/openrpc.spec.ts
  packages/relay/tests/lib/services/eth/filter.spec.ts
  packages/relay/tests/lib/services/metricService/metricService.spec.ts
  packages/server/tests/acceptance/erc20.spec.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
  packages/server/tests/acceptance/rpc_batch3.spec.ts
  packages/server/tests/helpers/assertions.ts
Labels: enhancement

#3722 feat: implement Jumbo Transaction support and enhance pre-requisite validation for eth_sendRawTransaction
  .github/workflows/acceptance.yml
  docs/configuration.md
  package.json
  packages/config-service/src/services/globalConfig.ts
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/relay/src/lib/precheck.ts
  packages/relay/src/lib/services/ethService/transactionService/TransactionService.ts
  packages/relay/tests/lib/precheck.spec.ts
  packages/relay/tests/lib/sdkClient.spec.ts
  packages/relay/tests/test.env
  packages/server/tests/acceptance/equivalence.spec.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
  packages/server/tests/acceptance/sendRawTransactionExtension.spec.ts
  packages/server/tests/localAcceptance.env
  packages/server/tests/mainnetAcceptance.env
  packages/server/tests/previewnetAcceptance.env
  packages/server/tests/testnetAcceptance.env
Labels: enhancement

#3735 chore: bump package versions
  dapp-example/package-lock.json
  dapp-example/package.json
  package-lock.json
  package.json
  packages/relay/package.json
  packages/relay/tsconfig.json
  packages/server/package.json
  packages/server/tests/acceptance/erc20.spec.ts
  packages/server/tests/acceptance/htsPrecompile/precompileCalls.spec.ts
  packages/server/tests/acceptance/htsPrecompile/tokenCreate.spec.ts
  packages/server/tests/acceptance/htsPrecompile/tokenManagement.spec.ts
  packages/server/tests/acceptance/htsPrecompile_v1.spec.ts
  packages/server/tsconfig.json
  packages/ws-server/package.json
  packages/ws-server/tests/acceptance/subscribe.spec.ts
  packages/ws-server/tests/acceptance/subscribeNewHeads.spec.ts
  packages/ws-server/tsconfig.json
  tools/waffle-example/package-lock.json
  tools/whbar-hardhat-example/package-lock.json
Labels: dependencies

#3741 docs: edited the badge and its link
  README.md
Labels: internal

#3744 feat: added support for debug_traceBlockByNumber
  .github/workflows/acceptance.yml
  docs/configuration.md
  docs/design/batch-request.md
  docs/openrpc.json
  package.json
  packages/config-service/src/services/globalConfig.ts
  packages/relay/src/index.ts
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/debug.ts
  packages/relay/src/lib/types/debug.ts
  packages/relay/src/lib/types/index.ts
  packages/relay/src/lib/types/mirrorNode.ts
  packages/relay/src/lib/validators/constants.ts
  packages/relay/tests/lib/debug.spec.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
  packages/server/src/koaJsonRpc/lib/methodConfiguration.ts
  packages/server/tests/acceptance/data/conformity-tests-batch-3.json
  packages/server/tests/acceptance/debug.spec.ts
  packages/server/tests/helpers/constants.ts
  packages/server/tests/integration/server.spec.ts
Labels: enhancement

#3768 fix: allowed callTracer to return empty array if no call actions found
  packages/relay/src/lib/debug.ts
  packages/relay/src/lib/types/debug.ts
  packages/relay/tests/lib/debug.spec.ts
Labels: bug

#3759 feat: Adds getProof as unsupported method
  docs/openrpc.json
  packages/relay/src/index.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth/eth_common.spec.ts
  packages/relay/tests/lib/openrpc.spec.ts
  packages/server/src/koaJsonRpc/lib/methodConfiguration.ts
  packages/server/tests/acceptance/conformityTests.spec.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
  packages/server/tests/integration/server.spec.ts
Labels: enhancement

#3750 feat: improve cache layer
  package-lock.json
  packages/relay/package.json
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/decorators/cache.decorator.ts
  packages/relay/src/lib/decorators/index.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/relay.ts
  packages/relay/src/lib/services/cacheService/cacheService.ts
  packages/relay/src/lib/services/ethService/accountService/AccountService.ts
  packages/relay/src/lib/services/ethService/blockService/BlockService.ts
  packages/relay/src/lib/services/ethService/contractService/ContractService.ts
  packages/relay/src/lib/services/ethService/ethCommonService/CommonService.ts
  packages/relay/src/lib/services/ethService/feeService/FeeService.ts
  packages/relay/src/lib/services/ethService/transactionService/TransactionService.ts
  packages/relay/tests/lib/admin.spec.ts
  packages/relay/tests/lib/config/hbarSpendingPlanConfigService.spec.ts
  packages/relay/tests/lib/decorators/cache.spec.ts
  packages/relay/tests/lib/eth/eth-helpers.ts
  packages/relay/tests/lib/eth/eth_feeHistory.spec.ts
  packages/relay/tests/lib/eth/eth_getBlockReceipts.spec.ts
  packages/relay/tests/lib/eth/eth_getTransactionReceipt.spec.ts
  packages/relay/tests/lib/ethGetBlockBy.spec.ts
  packages/relay/tests/lib/hapiService.spec.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
  packages/relay/tests/lib/openrpc.spec.ts
  packages/relay/tests/lib/precheck.spec.ts
  packages/relay/tests/lib/relay.spec.ts
  packages/relay/tests/lib/repositories/hbarLimiter/evmAddressHbarSpendingPlanRepository.spec.ts
  packages/relay/tests/lib/repositories/hbarLimiter/hbarSpendingPlanRepository.spec.ts
  packages/relay/tests/lib/repositories/hbarLimiter/ipAddressHbarSpendingPlanRepository.spec.ts
  packages/relay/tests/lib/sdkClient.spec.ts
  packages/relay/tests/lib/services/cacheService/cacheService.spec.ts
  packages/relay/tests/lib/services/eth/filter.spec.ts
  packages/relay/tests/lib/services/hbarLimitService/hbarLimitService.spec.ts
  packages/relay/tests/lib/services/metricService/metricService.spec.ts
  packages/server/tests/acceptance/cacheService.spec.ts
  packages/server/tests/acceptance/hbarLimiter.spec.ts
Labels: enhancement

#3758 chore: Improves performance and adds synthetic transaction support to getBlockReceipts
  packages/relay/package.json
  packages/relay/src/index.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/services/ethService/blockService/BlockService.ts
  packages/relay/src/lib/services/ethService/blockService/IBlockService.ts
  packages/relay/tests/assertions.ts
  packages/relay/tests/lib/eth/eth_getBlockReceipts.spec.ts
  packages/relay/tests/lib/ethGetBlockBy.spec.ts
Labels: enhancement, internal

#3777 fix: fixed flaky/failing acceptance tests
  packages/server/tests/acceptance/rpc_batch2.spec.ts
  packages/server/tests/localAcceptance.env
  packages/ws-server/tests/acceptance/batchRequest.spec.ts
Labels: internal

#3791 chore: add proof handling for empty hex responses in web3.js and ethers.js without exceptions
  tools/hardhat-example/test/rpc.js
  tools/web3js-example/test/rpc.js
Labels: internal

#3795 feat: add check for positive amount in dapp example
  dapp-example/src/components/AccountActivationForm.js
Labels: enhancement
