Repository hiero-ledger/hiero-json-rpc-relay, pull requests merged in 2025-01, with the labels that each got.

#3357 chore: updated release-automation script to add more information to SNAPSHOT PR
  .github/workflows/release-automation.yml
Labels: internal

#3355 chore(release): Bump versions for v0.64.0-SNAPSHOT
  charts/hedera-json-rpc-relay-websocket/Chart.yaml
  charts/hedera-json-rpc-relay/Chart.yaml
  charts/hedera-json-rpc/Chart.yaml
  docs/openrpc.json
  package-lock.json
  package.json
  packages/config-service/package.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: process

#3341 build: [Snyk] Security upgrade @graphprotocol/graph-cli from 0.89.0 to 0.92.0
  tools/subgraph-example/subgraph/package.json
Labels: dependencies

#3348 build: [Snyk] Upgrade @mui/material from 5.16.7 to 5.16.8
  dapp-example/package-lock.json
  dapp-example/package.json
Labels: dependencies

#3326 feat: add layer zero examples
  tools/layer-zero-example/.env.example
  tools/layer-zero-example/.gitignore
  tools/layer-zero-example/README.md
  tools/layer-zero-example/contracts/CreateHTS.sol
  tools/layer-zero-example/contracts/ERC20Mock.sol
  tools/layer-zero-example/contracts/ERC721Mock.sol
  tools/layer-zero-example/contracts/ExampleHTSConnector.sol
  tools/layer-zero-example/contracts/ExampleOApp.sol
  tools/layer-zero-example/contracts/ExampleOFT.sol
  tools/layer-zero-example/contracts/ExampleOFTAdapter.sol
  tools/layer-zero-example/contracts/ExampleONFT.sol
  tools/layer-zero-example/contracts/ExampleONFTAdapter.sol
  tools/layer-zero-example/contracts/HTSConnector.sol
  tools/layer-zero-example/contracts/WHBAR.sol
  tools/layer-zero-example/contracts/hts/HederaTokenService.sol
  tools/layer-zero-example/contracts/hts/IHederaTokenService.sol
  tools/layer-zero-example/contracts/hts/KeyHelper.sol
  tools/layer-zero-example/hardhat.config.js
  tools/layer-zero-example/package-lock.json
  tools/layer-zero-example/package.json
  tools/layer-zero-example/test/htsAdapterTests.js
  tools/layer-zero-example/test/htsConnectorTests.js
  tools/layer-zero-example/test/oappTests.js
  tools/layer-zero-example/test/oftAdapterTests.js
  tools/layer-zero-example/test/oftTests.js
  tools/layer-zero-example/test/onftAdapterTests.js
  tools/layer-zero-example/test/onftTests.js
  tools/layer-zero-example/test/whbarTests.js
Labels: dev tools, internal

#3358 build: [Snyk] Upgrade dotenv from 16.4.5 to 16.4.7
  tools/truffle-example/package-lock.json
  tools/truffle-example/package.json
Labels: dependencies

#3349 fix: enhanced reliability of eth RPC methods with null checks and retry mechanisms
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/services/debugService/index.ts
  packages/relay/src/lib/services/ethService/ethCommonService/index.ts
  packages/relay/src/receiptsRootUtils.ts
  packages/relay/tests/lib/eth/eth_getBlockByHash.spec.ts
  packages/relay/tests/lib/eth/eth_getBlockByNumber.spec.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
Labels: bug

#3363 chore: cherry pick #3349 - fix: enhanced reliability of eth RPC methods with null checks and retry mechanisms to release/0.63
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/services/debugService/index.ts
  packages/relay/src/lib/services/ethService/ethCommonService/index.ts
  packages/relay/src/receiptsRootUtils.ts
  packages/relay/tests/lib/eth/eth_getBlockByHash.spec.ts
  packages/relay/tests/lib/eth/eth_getBlockByNumber.spec.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
Labels: process

#3368 fix: added polling logic to ensure the retrieval of fully mature records from MN
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/services/ethService/ethCommonService/index.ts
  packages/relay/tests/lib/eth/eth_getLogs.spec.ts
  packages/relay/tests/lib/eth/eth_getTransactionByHash.spec.ts
  packages/relay/tests/lib/eth/eth_getTransactionReceipt.spec.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
Labels: enhancement

#3370 chore: cherry pick #3368 fix: added polling logic to ensure the retrieval of fully mature records from MN
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/services/ethService/ethCommonService/index.ts
  packages/relay/tests/lib/eth/eth_getLogs.spec.ts
  packages/relay/tests/lib/eth/eth_getTransactionByHash.spec.ts
  packages/relay/tests/lib/eth/eth_getTransactionReceipt.spec.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
Labels: process

#3365 build: [Snyk] Upgrade @graphprotocol/graph-ts from 0.35.1 to 0.37.0
  tools/subgraph-example/subgraph/package.json
Labels: dependencies

#3391 chore: rename devops-ci to platform-ci
  .github/CODEOWNERS
Labels: github_action

#3383 build: [Snyk] Upgrade @hashgraph/sdk from 2.53.0 to 2.56.0
  dapp-example/package-lock.json
  dapp-example/package.json
Labels: dependencies

#3396 chore(release): Bump versions for v0.65.0-SNAPSHOT
  charts/hedera-json-rpc-relay-websocket/Chart.yaml
  charts/hedera-json-rpc-relay/Chart.yaml
  charts/hedera-json-rpc/Chart.yaml
  docs/openrpc.json
  package-lock.json
  package.json
  packages/config-service/package.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: process

#3397 feat: remove duplicated OFT Adapter section in LZ readme
  tools/layer-zero-example/README.md
  tools/layer-zero-example/hardhat.config.js
Labels: enhancement

#3386 chore: blockscout example project
  tools/blockscout-example/README.md
Labels: enhancement

#3400 build: [Snyk] Upgrade @graphprotocol/graph-cli from 0.92.0 to 0.93.3
  tools/subgraph-example/subgraph/package.json
Labels: dependencies

#3384 chore: fix CODEOWNERS file
  .github/CODEOWNERS
Labels: github_action

#3394 feat: added DEPENDENT_SERVICE_IMMATURE_RECORDS predefined error for immature records scenarios
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/services/ethService/ethCommonService/index.ts
  packages/relay/tests/lib/eth/eth_getBlockByHash.spec.ts
  packages/relay/tests/lib/eth/eth_getBlockByNumber.spec.ts
  packages/relay/tests/lib/eth/eth_getLogs.spec.ts
  packages/relay/tests/lib/eth/eth_getTransactionByHash.spec.ts
  packages/relay/tests/lib/eth/eth_getTransactionReceipt.spec.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
  packages/server/src/koaJsonRpc/lib/HttpStatusCodeAndMessage.ts
Labels: internal

#3415 chore: cherry pick feat: added DEPENDENT_SERVICE_IMMATURE_RECORDS predefined error for immature records scenarios (#3394)
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/services/ethService/ethCommonService/index.ts
  packages/relay/tests/lib/eth/eth_getBlockByHash.spec.ts
  packages/relay/tests/lib/eth/eth_getBlockByNumber.spec.ts
  packages/relay/tests/lib/eth/eth_getLogs.spec.ts
  packages/relay/tests/lib/eth/eth_getTransactionByHash.spec.ts
  packages/relay/tests/lib/eth/eth_getTransactionReceipt.spec.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
  packages/server/src/koaJsonRpc/lib/HttpStatusCodeAndMessage.ts
Labels: process

#3331 refactor: clean up configurations
  .github/workflows/acceptance-workflow.yml
  .github/workflows/test.yml
  charts/hedera-json-rpc-relay/environments/minikube.yaml
  charts/hedera-json-rpc-relay/templates/secret.yaml
  packages/config-service/src/services/index.ts
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/relay.ts
  packages/relay/src/lib/services/hapiService/hapiService.ts
  packages/relay/src/lib/services/hbarLimitService/index.ts
  packages/relay/src/utils.ts
  packages/relay/tests/lib/clients/localLRUCache.spec.ts
  packages/relay/tests/lib/clients/redisCache.spec.ts
  packages/relay/tests/lib/config/hbarSpendingPlanConfigService.spec.ts
  packages/relay/tests/lib/eth/eth-helpers.ts
  packages/relay/tests/lib/eth/eth_common.spec.ts
  packages/relay/tests/lib/eth/eth_estimateGas.spec.ts
  packages/relay/tests/lib/eth/eth_sendRawTransaction.spec.ts
  packages/relay/tests/lib/ethGetBlockBy.spec.ts
  packages/relay/tests/lib/hapiService.spec.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
  packages/relay/tests/lib/net.spec.ts
  packages/relay/tests/lib/openrpc.spec.ts
  packages/relay/tests/lib/precheck.spec.ts
  packages/relay/tests/lib/relay.spec.ts
  packages/relay/tests/lib/repositories/hbarLimiter/evmAddressHbarSpendingPlanRepository.spec.ts
  packages/relay/tests/lib/repositories/hbarLimiter/hbarSpendingPlanRepository.spec.ts
  packages/relay/tests/lib/repositories/hbarLimiter/ipAddressHbarSpendingPlanRepository.spec.ts
  packages/relay/tests/lib/sdkClient.spec.ts
  packages/relay/tests/lib/services/cacheService/cacheService.spec.ts
  packages/relay/tests/lib/services/debugService/debug.spec.ts
  packages/relay/tests/lib/services/eth/filter.spec.ts
  packages/relay/tests/lib/services/hbarLimitService/hbarLimitService.spec.ts
  packages/relay/tests/lib/services/metricService/metricService.spec.ts
  packages/relay/tests/lib/utils.spec.ts
  packages/relay/tests/lib/web3.spec.ts
  packages/server/tests/acceptance/equivalence.spec.ts
  packages/server/tests/acceptance/hbarLimiter.spec.ts
  packages/server/tests/acceptance/index.spec.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
  packages/server/tests/integration/rateLimiter.spec.ts
  packages/ws-server/tests/acceptance/index.spec.ts
  packages/ws-server/tests/unit/validations.spec.ts
Labels: Technical Debt, internal

#3403 build: [Snyk] Upgrade @mui/material from 5.16.8 to 5.16.13
  dapp-example/package-lock.json
  dapp-example/package.json
Labels: dependencies

#3382 build: [Snyk] Upgrade pnpm from 9.15.0 to 9.15.1
  package-lock.json
  package.json
  packages/relay/src/lib/clients/sdkClient.ts
Labels: dependencies

#3422 chore(logging): enhanced logging upon receiving responses from the Mirror Node server
  packages/relay/src/lib/clients/mirrorNodeClient.ts
Labels: enhancement

#3426 chore: cherry pick PR#3422 feat(logging): enhanced logging upon receiving responses from the Mirror Node server (#3422) to release/0.64
  packages/relay/src/lib/clients/mirrorNodeClient.ts
Labels: process

#3431 feat: enhanced eth_getLogs with timestamp range validation and new error handling
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/services/ethService/ethCommonService/index.ts
  packages/relay/src/lib/services/ethService/ethFilterService/index.ts
  packages/relay/tests/lib/eth/eth_getLogs.spec.ts
  packages/relay/tests/lib/services/eth/filter.spec.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
Labels: bug

#3434 chore: cherry pick feat: enhanced eth_getLogs with timestamp range validation and new error handling (#3431) to release/0.64
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/services/ethService/ethCommonService/index.ts
  packages/relay/src/lib/services/ethService/ethFilterService/index.ts
  packages/relay/tests/lib/eth/eth_getLogs.spec.ts
  packages/relay/tests/lib/services/eth/filter.spec.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
Labels: bug

#3387 feat: transaction with `CONTRACT_NEGATIVE_VALUE` breaks some routes
  package-lock.json
  packages/relay/package.json
  packages/relay/src/formatters.ts
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/tests/lib/formatters.spec.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
  packages/server/tests/clients/servicesClient.ts
Labels: bug

#3423 build: [Snyk] Upgrade pnpm from 9.15.1 to 9.15.2
  package-lock.json
  package.json
Labels: dependencies

#3436 chore: cherry pick feat: transaction with CONTRACT_NEGATIVE_VALUE breaks some routes (#3387) to release/0.64
  .github/workflows/acceptance-workflow.yml
  .github/workflows/test.yml
  package-lock.json
  packages/relay/package.json
  packages/relay/src/formatters.ts
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/tests/lib/formatters.spec.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
  packages/server/tests/clients/servicesClient.ts
Labels: process
