Repository hiero-ledger/hiero-json-rpc-relay, pull requests merged in 2025-04, with the labels that each got.

#3612 refactor: add account service class
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/services/accountService/IAccountService.ts
  packages/relay/src/lib/services/accountService/index.ts
  packages/relay/src/lib/services/blockService/IBlockService.ts
  packages/relay/src/lib/services/ethService/ethCommonService/ITimestamp.ts
  packages/relay/src/lib/services/ethService/ethCommonService/index.ts
  packages/relay/tests/lib/eth/eth_getBalance.spec.ts
Labels: enhancement

#3600 refactor: Create BlockService with block related classes
  packages/relay/src/formatters.ts
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/debug.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/services/accountService/index.ts
  packages/relay/src/lib/services/blockService/BlockService.ts
  packages/relay/src/lib/services/blockService/IBlockService.ts
  packages/relay/src/lib/services/blockService/index.ts
  packages/relay/src/lib/services/ethService/ethCommonService/CommonService.ts
  packages/relay/src/lib/services/ethService/ethCommonService/ICommonService.ts
  packages/relay/src/lib/services/ethService/ethFilterService/index.ts
  packages/relay/src/lib/services/ethService/index.ts
  packages/relay/src/lib/services/factories/blockFactory.ts
  packages/relay/src/lib/services/factories/transactionFactory.ts
  packages/relay/src/lib/services/feeService/index.ts
  packages/relay/src/lib/services/index.ts
  packages/relay/src/lib/services/transactionService/ITransactionService.ts
  packages/relay/tests/lib/debug.spec.ts
  packages/relay/tests/lib/eth/eth_getBlockReceipts.spec.ts
  packages/relay/tests/lib/eth/eth_getTransactionReceipt.spec.ts
  packages/relay/tests/lib/ethGetBlockBy.spec.ts
  packages/relay/tests/lib/formatters.spec.ts
  packages/relay/tests/lib/openrpc.spec.ts
  packages/relay/tests/lib/services/eth/filter.spec.ts
Labels: enhancement

#3620 ci: update ghcr references in docker compose
  README.md
  docker-compose.yml
  docs/configuration.md
  docs/openrpc.json
  docs/rpc-api.md
  k6/package.json
  package.json
  packages/relay/src/lib/eth.ts
  packages/server/tests/acceptance/htsPrecompile/precompileCalls.spec.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
  scripts/.bump-version.js
  tools/foundry-example/README.md
  tools/golang-example/README.md
  tools/golang-json-rpc-tests/README.md
  tools/hardhat-viem-example/README.md
  tools/layer-zero-example/README.md
  tools/waffle-example/README.md
Labels: bug, dependencies

#3589 feat: add redis as helm charts dependency
  charts/hedera-json-rpc-relay-websocket/templates/_helpers.tpl
  charts/hedera-json-rpc-relay-websocket/templates/configmap.yaml
  charts/hedera-json-rpc-relay-websocket/values.yaml
  charts/hedera-json-rpc-relay/templates/_helpers.tpl
  charts/hedera-json-rpc-relay/templates/configmap.yaml
  charts/hedera-json-rpc-relay/values.yaml
  charts/hedera-json-rpc/Chart.yaml
  charts/hedera-json-rpc/values.yaml
Labels: enhancement

#3626 feat: added IS_MODULARIZED axios header for MirrorNodeClient
  docs/configuration.md
  packages/config-service/src/services/globalConfig.ts
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
Labels: enhancement

#3625 chore: fix Docker `libc-bin` issue
  .github/workflows/image-build.yml
  .github/workflows/release-integration.yml
  .github/workflows/release-production.yml
  Dockerfile
Labels: github_action

#3628 chore: Update setup-buildx action and Qemu
  .github/workflows/charts.yml
  .github/workflows/image-build.yml
  .github/workflows/release-production.yml
Labels: github_action

#3615 chore(release): Bump versions for v0.68.0-SNAPSHOT
  charts/hedera-json-rpc-relay-websocket/Chart.yaml
  charts/hedera-json-rpc-relay/Chart.yaml
  charts/hedera-json-rpc/Chart.yaml
  docs/openrpc.json
  package-lock.json
  package.json
  packages/config-service/package.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: process

#3562 build(deps): [Snyk] Upgrade @graphprotocol/graph-cli from 0.95.0 to 0.96.0
  tools/subgraph-example/subgraph/package.json
Labels: dependencies

#3631 chore: cherry pick to fix Docker build image workflows
  .github/workflows/charts.yml
  .github/workflows/image-build.yml
  .github/workflows/release-integration.yml
  .github/workflows/release-production.yml
  Dockerfile
Labels: process, github_action

#3525 build(dep): [Snyk] Security upgrade @hashgraph/sdk from 2.59.0 to 2.60.1
  dapp-example/package-lock.json
Labels: dependencies

#3621 refactor: creates ContractService class
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/services/blockService/BlockService.ts
  packages/relay/src/lib/services/contractService/ContractService.ts
  packages/relay/src/lib/services/contractService/IContractService.ts
  packages/relay/src/lib/services/ethService/ethCommonService/CommonService.ts
  packages/relay/src/lib/services/ethService/ethCommonService/ICommonService.ts
  packages/relay/src/lib/services/factories/blockFactory.ts
  packages/relay/src/lib/services/index.ts
  packages/relay/src/lib/types/IMirrorNodeBlock.ts
  packages/relay/src/lib/types/index.ts
  packages/relay/src/lib/types/mirrorNode.ts
  packages/relay/src/receiptsRootUtils.ts
  packages/relay/tests/assertions.ts
  packages/relay/tests/helpers.ts
  packages/relay/tests/lib/eth/eth-helpers.ts
  packages/relay/tests/lib/eth/eth_call.spec.ts
  packages/relay/tests/lib/eth/eth_estimateGas.spec.ts
  packages/relay/tests/lib/eth/eth_getBlockReceipts.spec.ts
  packages/relay/tests/lib/eth/eth_getCode.spec.ts
  packages/relay/tests/lib/eth/eth_getStorageAt.spec.ts
  packages/relay/tests/lib/eth/eth_getTransactionCount.spec.ts
  packages/server/tests/acceptance/erc20.spec.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
Labels: enhancement

#3641 chore: Update docker images to use specific commit shas as versions
  dapp-example/docker-compose.yml
  docker-compose.yml
  tools/subgraph-example/docker-compose.yml
Labels: Audit

#3639 fix: skipped Is-Modularized header for Mirror Node Client when USE_MIRROR_NODE_MODULARIZED_SERVICES flag is unset
  docs/configuration.md
  packages/config-service/src/services/globalConfig.ts
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
Labels: enhancement

#3565 chore: moves poller and subscriptions controller to ws-server
  packages/relay/src/index.ts
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/relay/src/lib/relay.ts
  packages/relay/tests/lib/relay.spec.ts
  packages/relay/tests/test.env
  packages/server/tests/localAcceptance.env
  packages/ws-server/src/controllers/jsonRpcController.ts
  packages/ws-server/src/controllers/subscribeController.ts
  packages/ws-server/src/controllers/unsubscribeController.ts
  packages/ws-server/src/service/pollerService.ts
  packages/ws-server/src/service/subscriptionService.ts
  packages/ws-server/src/utils/utils.ts
  packages/ws-server/src/webSocketServer.ts
  packages/ws-server/tests/acceptance/subscribe.spec.ts
  packages/ws-server/tests/unit/pollerService.spec.ts
  packages/ws-server/tests/unit/subscriptionService.spec.ts
  packages/ws-server/tests/unit/utils.spec.ts
Labels: enhancement

#3651 chore: fix k6 issues found when running release `0.67` tests
  k6/README.md
  k6/src/prepare/prep.js
  k6/src/scenarios/test/index.js
Labels: internal

#3657 fix: fixed GHA deprecated cache and resolved LegacyKeyValueFormat for Docker build
  .github/workflows/charts.yml
  .github/workflows/image-build.yml
  .github/workflows/release-integration.yml
  .github/workflows/release-production.yml
  Dockerfile
Labels: internal

#3670 fix: Update flow-pr-title-check.yml
  .github/workflows/flow-pr-title-check.yml
Labels: internal

#3662 refactor: moves estimateGas and getStorageAt to ContractService
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/services/contractService/ContractService.ts
  packages/relay/src/lib/services/contractService/IContractService.ts
  packages/relay/tests/lib/eth/eth_estimateGas.spec.ts
Labels: enhancement

#3660 fix: enhanced JsonRpcError handling and message formatting
  packages/relay/src/lib/dispatcher/rpcMethodDispatcher.ts
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/relay/tests/lib/errors/JsonRpcError.spec.ts
Labels: Technical Debt, internal

#3671 build(deps): bump golang.org/x/crypto from 0.22.0 to 0.31.0 in /tools/golang-json-rpc-tests
  tools/golang-json-rpc-tests/go.mod
  tools/golang-json-rpc-tests/go.sum
Labels: dependencies

#3687 build(deps): bump elliptic to v6.6.1 for example tools
  package-lock.json
  package.json
  tools/hardhat-example/package-lock.json
  tools/hardhat-example/package.json
  tools/hardhat-viem-example/package-lock.json
  tools/hardhat-viem-example/package.json
  tools/layer-zero-example/package-lock.json
  tools/layer-zero-example/package.json
  tools/solidity-coverage-example/package-lock.json
  tools/solidity-coverage-example/package.json
  tools/subgraph-example/package-lock.json
  tools/subgraph-example/package.json
  tools/waffle-example/package-lock.json
  tools/waffle-example/package.json
Labels: dependencies

#3688 build(deps): bump golang.org/x/crypto from 0.31.0 to 0.35.0 in /tools/golang-example
  tools/golang-example/go.mod
  tools/golang-example/go.sum
Labels: dependencies

#3689 build(deps): bump axios to 1.8.4 in tools/whbar-hardhat-example
  tools/hardhat-viem-example/package-lock.json
  tools/layer-zero-example/package-lock.json
  tools/layer-zero-example/package.json
  tools/subgraph-example/package-lock.json
  tools/subgraph-example/package.json
  tools/whbar-hardhat-example/package-lock.json
Labels: dependencies

#3694 build(deps): bump dependencies in example tools in tools/ folder
  tools/alloy-core-rs-example/Cargo.lock
  tools/alloy-core-rs-example/Cargo.toml
  tools/ethers-rs-example/Cargo.lock
  tools/ethers-rs-example/Cargo.toml
  tools/golang-json-rpc-tests/go.mod
  tools/golang-json-rpc-tests/go.sum
  tools/hardhat-example/package-lock.json
  tools/hardhat-example/package.json
  tools/hardhat-viem-example/package-lock.json
  tools/hardhat-viem-example/package.json
  tools/layer-zero-example/package-lock.json
  tools/layer-zero-example/package.json
  tools/solidity-coverage-example/package-lock.json
  tools/solidity-coverage-example/package.json
  tools/subgraph-example/package-lock.json
  tools/subgraph-example/package.json
  tools/waffle-example/package-lock.json
  tools/waffle-example/package.json
  tools/web3js-example/package-lock.json
  tools/web3js-example/package.json
  tools/web3rs-example/Cargo.lock
  tools/web3rs-example/Cargo.toml
  tools/whbar-hardhat-example/package-lock.json
  tools/whbar-hardhat-example/package.json
Labels: dependencies

#3646 refactor: create TransactionService class
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/relay.ts
  packages/relay/src/lib/services/blockService/BlockService.ts
  packages/relay/src/lib/services/ethService/ethCommonService/CommonService.ts
  packages/relay/src/lib/services/factories/blockFactory.ts
  packages/relay/src/lib/services/factories/transactionFactory.ts
  packages/relay/src/lib/services/factories/transactionReceiptFactory.ts
  packages/relay/src/lib/services/index.ts
  packages/relay/src/lib/services/metricService/metricService.ts
  packages/relay/src/lib/services/transactionService/ITransactionService.ts
  packages/relay/src/lib/services/transactionService/TransactionService.ts
  packages/relay/src/lib/types/events.ts
  packages/relay/src/logsBloomUtils.ts
  packages/relay/tests/assertions.ts
  packages/relay/tests/lib/eth/eth-helpers.ts
  packages/relay/tests/lib/eth/eth_call.spec.ts
  packages/relay/tests/lib/eth/eth_estimateGas.spec.ts
  packages/relay/tests/lib/eth/eth_getBlockByHash.spec.ts
  packages/relay/tests/lib/eth/eth_getBlockByNumber.spec.ts
  packages/relay/tests/lib/eth/eth_getTransactionByBlockNumberAndIndex.spec.ts
  packages/relay/tests/lib/eth/eth_getTransactionReceipt.spec.ts
  packages/relay/tests/lib/eth/eth_sendRawTransaction.spec.ts
  packages/relay/tests/lib/ethGetBlockBy.spec.ts
  packages/relay/tests/lib/logsBloomUtils.spec.ts
  packages/relay/tests/lib/openrpc.spec.ts
  packages/relay/tests/lib/services/eth/filter.spec.ts
  packages/relay/tests/lib/services/metricService/metricService.spec.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
  packages/server/tests/helpers/assertions.ts
Labels: enhancement

#3715 fix: removed Consensus Node fallback mechanism for read-only RPC methods
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/relay.ts
  packages/relay/src/lib/services/hapiService/hapiService.ts
  packages/relay/tests/lib/eth/eth_call.spec.ts
  packages/relay/tests/lib/eth/eth_feeHistory.spec.ts
  packages/relay/tests/lib/eth/eth_gasPrice.spec.ts
  packages/relay/tests/lib/eth/eth_getCode.spec.ts
  packages/relay/tests/lib/eth/eth_getTransactionReceipt.spec.ts
  packages/relay/tests/lib/openrpc.spec.ts
  packages/relay/tests/lib/sdkClient.spec.ts
Labels: enhancement

#3718 feat: support non-zero shard/realm
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth/eth_getCode.spec.ts
  packages/server/tests/acceptance/erc20.spec.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
  packages/server/tests/helpers/utils.ts
Labels: enhancement

#3726 feat: added eth_blobBaseFee endpoint
  charts/hedera-json-rpc-relay/postman.json
  docs/openrpc.json
  docs/rate-limiting.md
  docs/rpc-api.md
  packages/relay/src/index.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth/eth_common.spec.ts
  packages/relay/tests/lib/openrpc.spec.ts
  packages/server/src/koaJsonRpc/lib/methodConfiguration.ts
  packages/server/tests/acceptance/data/conformity-tests-batch-2.json
  packages/server/tests/acceptance/rpc_batch2.spec.ts
  packages/server/tests/helpers/constants.ts
  packages/server/tests/integration/server.spec.ts
Labels: enhancement
