Repository hiero-ledger/hiero-json-rpc-relay, pull requests merged in 2025-06, with the labels that each got.

#3828 build(deps): restored sdk version and fixed package vuls in whbar-hardhat-exampl
  tools/whbar-hardhat-example/package-lock.json
  tools/whbar-hardhat-example/package.json
Labels: dependencies

#3822 feat: updates the RPC API section of the docs
  docs/rpc-api.md
Labels: enhancement

#3809 feat: [hedera-crosschain-bridge] Case B – Custom HTS Token Bridging Implementation and Testing
  tools/hedera-crosschain-bridge/README.md
  tools/hedera-crosschain-bridge/contracts/ExampleHTSConnector.sol
  tools/hedera-crosschain-bridge/contracts/ExampleOFT.sol
  tools/hedera-crosschain-bridge/contracts/HTSConnector.sol
  tools/hedera-crosschain-bridge/contracts/hts/HederaTokenService.sol
  tools/hedera-crosschain-bridge/contracts/hts/IHederaTokenService.sol
  tools/hedera-crosschain-bridge/contracts/hts/KeyHelper.sol
  tools/hedera-crosschain-bridge/package-lock.json
  tools/hedera-crosschain-bridge/package.json
  tools/hedera-crosschain-bridge/scripts/deployments/README.md
  tools/hedera-crosschain-bridge/scripts/deployments/deploy-hts-connector.ts
  tools/hedera-crosschain-bridge/scripts/deployments/deploy-oft.ts
  tools/hedera-crosschain-bridge/scripts/utils/constants.ts
  tools/hedera-crosschain-bridge/scripts/utils/update-account-associations.ts
  tools/hedera-crosschain-bridge/test/bridging-e2e/erc20-hts/README.md
  tools/hedera-crosschain-bridge/test/bridging-e2e/erc20-hts/erc20-hts-e2e-hedera-sepolia.spec.ts
  tools/hedera-crosschain-bridge/test/bridging-e2e/whbar/whbar-e2e-hedera-sepolia.spec.ts
  tools/hedera-crosschain-bridge/test/deployments/deploy-hts-connector.spec.ts
  tools/hedera-crosschain-bridge/test/deployments/deploy-oft.spec.ts
  tools/hedera-crosschain-bridge/test/utils/helpers.ts
Labels: enhancement

#3796 feat: adds shared rate limiting to the relay using Redis
  README.md
  docs/configuration.md
  docs/rate-limiting.md
  packages/config-service/src/services/globalConfig.ts
  packages/relay/src/lib/config/methodConfiguration.ts
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/hbarlimiter/index.ts
  packages/relay/src/lib/services/index.ts
  packages/relay/src/lib/services/rateLimiterService/LruRateLimitStore.ts
  packages/relay/src/lib/services/rateLimiterService/RedisRateLimitStore.ts
  packages/relay/src/lib/services/rateLimiterService/rateLimiterService.ts
  packages/relay/src/lib/types/index.ts
  packages/relay/src/lib/types/rateLimiter.ts
  packages/relay/tests/lib/services/rateLimiterService/rateLimiterService.spec.ts
  packages/server/src/koaJsonRpc/index.ts
  packages/server/src/rateLimit/index.ts
  packages/server/tests/acceptance/rateLimiter.spec.ts
  packages/server/tests/integration/rateLimiter.spec.ts
  packages/ws-server/src/controllers/jsonRpcController.ts
  packages/ws-server/src/metrics/connectionLimiter.ts
  packages/ws-server/tests/acceptance/rateLimiter.spec.ts
Labels: enhancement

#3836 fix: remove custom cache logic from `getBlockReceipts`
  packages/relay/src/lib/services/ethService/blockService/BlockService.ts
Labels: Technical Debt

#3771 chore: Update MAINTAINERS.md - Update names and affiliations
  MAINTAINERS.md
Labels: internal

#3843 chore(release): Bump versions for v0.70.0-SNAPSHOT
  README.md
  charts/hedera-json-rpc-relay-websocket/Chart.yaml
  charts/hedera-json-rpc-relay/Chart.yaml
  charts/hedera-json-rpc/Chart.yaml
  docs/openrpc.json
  package-lock.json
  package.json
  packages/config-service/package.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: process

#3852 chore: include `eth_createAccessList` as an unsupported method
  docs/openrpc.json
  docs/rpc-api.md
  packages/relay/src/lib/config/methodConfiguration.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth/eth_common.spec.ts
  packages/relay/tests/lib/openrpc.spec.ts
  packages/server/tests/acceptance/conformityTests.spec.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
  packages/server/tests/helpers/constants.ts
  packages/server/tests/integration/server.spec.ts
Labels: internal

#3866 feat: enables proxy support
  packages/server/src/server.ts
  packages/server/tests/integration/proxyHeaders.spec.ts
  packages/server/tests/integration/server.spec.ts
Labels: enhancement

#3789 fix: Aligns debug_traceTransaction validation with industry standards
  docs/openrpc.json
  packages/relay/src/index.ts
  packages/relay/src/lib/debug.ts
  packages/relay/src/lib/types/debug.ts
  packages/relay/src/lib/validators/objectTypes.ts
  packages/relay/src/utils.ts
  packages/relay/tests/lib/debug.spec.ts
  packages/relay/tests/lib/utils.spec.ts
  packages/server/tests/integration/server.spec.ts
Labels: enhancement

#3871 feat: adds Forwarded header to downstream MN requests + custom parsing for Forwarded headers
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
  packages/server/src/server.ts
  packages/server/tests/integration/proxyHeaders.spec.ts
Labels: enhancement

#3876 feat: edit `rpc_relay_consensusnode_*` metrics
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/services/metricService/metricService.ts
  packages/relay/src/lib/types/events.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
  packages/relay/tests/lib/sdkClient.spec.ts
  packages/relay/tests/lib/services/metricService/metricService.spec.ts
Labels: enhancement
