Repository hiero-ledger/hiero-json-rpc-relay, pull requests merged in 2025-07, with the labels that each got.

#3825 feat: fix contract creation tx receipt compatibility with Ethereum spec
  packages/relay/src/lib/factories/transactionReceiptFactory.ts
  packages/relay/src/lib/services/ethService/blockService/BlockService.ts
  packages/relay/src/lib/services/ethService/transactionService/ITransactionService.ts
  packages/relay/src/lib/services/ethService/transactionService/TransactionService.ts
  packages/relay/src/lib/types/ITransactionReceipt.ts
  packages/relay/tests/lib/eth/eth_getBlockReceipts.spec.ts
  packages/relay/tests/lib/eth/eth_getTransactionReceipt.spec.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
Labels: ArianeLabs

#3879 feat: make blockNumberOrTagOrHash a required parameter for eth_getStorageAt (#3839)
  packages/relay/src/lib/decorators/cache.decorator.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/services/ethService/contractService/ContractService.ts
  packages/relay/src/lib/services/ethService/contractService/IContractService.ts
  packages/relay/tests/lib/eth/eth_getStorageAt.spec.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
  packages/server/tests/integration/server.spec.ts
Labels: ArianeLabs

#3824 feat: stop skipping the confromity tests
  packages/server/tests/acceptance/conformityTests.spec.ts
  packages/server/tests/acceptance/data/conformity/genesis.json
  packages/server/tests/acceptance/data/conformity/overwrites/README.md
  packages/server/tests/acceptance/data/conformity/overwrites/eth_call/call-callenv-options-eip1559.io
  packages/server/tests/acceptance/data/conformity/overwrites/eth_call/call-callenv.io
  packages/server/tests/acceptance/data/conformity/overwrites/eth_call/call-contract.io
  packages/server/tests/acceptance/data/conformity/overwrites/eth_call/call-revert-abi-error.io
  packages/server/tests/acceptance/data/conformity/overwrites/eth_call/call-revert-abi-panic.io
  packages/server/tests/acceptance/data/conformity/overwrites/eth_createAccessList/create-al-contract-eip1559.io
  packages/server/tests/acceptance/data/conformity/overwrites/eth_createAccessList/create-al-contract.io
  packages/server/tests/acceptance/data/conformity/overwrites/eth_createAccessList/create-al-value-transfer.io
  packages/server/tests/acceptance/data/conformity/overwrites/eth_estimateGas/estimate-failed-call.io
  packages/server/tests/acceptance/data/conformity/overwrites/eth_estimateGas/estimate-successful-call.io
  packages/server/tests/acceptance/data/conformity/overwrites/eth_getLogs/contract-addr.io
  packages/server/tests/acceptance/data/conformity/overwrites/eth_getLogs/no-topics.io
  packages/server/tests/acceptance/data/conformity/overwrites/eth_getLogs/topic-exact-match.io
  packages/server/tests/acceptance/data/conformity/overwrites/eth_getLogs/topic-wildcard.io
  packages/server/tests/acceptance/data/conformity/overwrites/eth_getProof/get-account-proof-blockhash.io
  packages/server/tests/acceptance/data/conformity/overwrites/eth_getProof/get-account-proof-latest.io
  packages/server/tests/acceptance/data/conformity/overwrites/eth_getProof/get-account-proof-with-storage.io
  packages/server/tests/acceptance/data/conformity/overwrites/eth_getTransactionByHash/get-blob-tx.io
  packages/server/tests/acceptance/data/conformity/overwrites/eth_getTransactionReceipt/get-blob-tx.io
  packages/server/tests/acceptance/data/conformity/overwrites/eth_sendRawTransaction/send-blob-tx.io
Labels: ArianeLabs

#3861 feat: update getTransactionCount to always require a blockNumOrTag parameter (#3840)
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/services/ethService/accountService/AccountService.ts
  packages/relay/src/lib/services/ethService/accountService/IAccountService.ts
  packages/relay/tests/lib/eth/eth_getTransactionCount.spec.ts
Labels: enhancement

#3884 feat: remove contract code size limit precheck
  docs/configuration.md
  packages/config-service/src/services/globalConfig.ts
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/relay/src/lib/precheck.ts
  packages/relay/tests/lib/precheck.spec.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
  packages/server/tests/acceptance/sendRawTransactionExtension.spec.ts
Labels: enhancement

#3892 feat: ensure rpc params array length according to rpc definitions
  packages/relay/src/lib/validators/index.ts
  packages/relay/tests/lib/dispatcher/rpcMethodDispatcher.spec.ts
  packages/relay/tests/lib/validators/validators.spec.ts
  packages/server/tests/acceptance/rpc_batch3.spec.ts
Labels: enhancement

#3893 feat: adds IPFS_PROFILE env variable when running CI for subgraph
  .github/workflows/subgraph.yml
  tools/subgraph-example/docker-compose.yml
Labels: enhancement

#3891 chore: refactor validator service in relay package for clarity and optimization
  packages/relay/src/lib/debug.ts
  packages/relay/src/lib/decorators/index.ts
  packages/relay/src/lib/decorators/rpcParamValidationRules.decorator.ts
  packages/relay/src/lib/dispatcher/rpcMethodDispatcher.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/services/registryService/rpcMethodRegistryService.ts
  packages/relay/src/lib/types/index.ts
  packages/relay/src/lib/types/validation.ts
  packages/relay/src/lib/validators/constants.ts
  packages/relay/src/lib/validators/index.ts
  packages/relay/src/lib/validators/objectTypes.ts
  packages/relay/src/lib/validators/types.ts
  packages/relay/src/lib/validators/utils.ts
  packages/relay/src/lib/web3.ts
  packages/relay/src/utils.ts
  packages/relay/tests/lib/decorators/rpcParamSchema.spec.ts
  packages/relay/tests/lib/dispatcher/rpcMethodDispatcher.spec.ts
  packages/relay/tests/lib/validators/validators.spec.ts
  packages/server/tests/acceptance/debug.spec.ts
  packages/server/tests/helpers/constants.ts
  packages/server/tests/integration/server.spec.ts
  packages/ws-server/src/utils/validators.ts
Labels: enhancement, internal

#3792 chore: add `eth_getBlockReceipts` method to OpenRPC definitions
  docs/openrpc.json
Labels: documentation

#3922 chore: TAC requirement - Update README.md
  README.md
Labels: documentation

#3925 feat: deprecate `ETH_CALL_DEFAULT_TO_CONSENSUS_NODE`, `OPERATOR_ID_ETH_SENDRAWTRANSACTION` and `OPERATOR_KEY_ETH_SENDRAWTRANSACTION`
  .env.http.example
  .env.ws.example
  charts/hedera-json-rpc-relay-websocket/values.yaml
  charts/hedera-json-rpc-relay/environments/minikube.yaml
  charts/hedera-json-rpc-relay/templates/secret.yaml
  charts/hedera-json-rpc-relay/values.yaml
  docs/configuration.md
  docs/rpc-api.md
  packages/config-service/src/services/globalConfig.ts
  packages/config-service/src/services/loggerService.ts
  packages/relay/src/formatters.ts
  packages/relay/src/lib/services/ethService/contractService/ContractService.ts
  packages/relay/src/lib/services/hapiService/hapiService.ts
  packages/relay/src/utils.ts
  packages/relay/tests/lib/eth/eth_call.spec.ts
  packages/relay/tests/lib/formatters.spec.ts
  packages/relay/tests/lib/utils.spec.ts
  packages/relay/tests/test.env
  packages/server/tests/acceptance/rpc_batch3.spec.ts
  packages/server/tests/localAcceptance.env
  packages/server/tests/previewnetAcceptance.env
  packages/server/tests/testnetAcceptance.env
Labels: enhancement

#3881 feat: updated values for hbar rate limiter based on new spending rate
  .env.http.example
  charts/hedera-json-rpc/dashboards/hedera-json-rpc-relay-http-server.json
  charts/hedera-json-rpc/dashboards/webSocketServer.json
  docs/configuration.md
  packages/config-service/src/services/globalConfig.ts
Labels: enhancement

#3932 fix: charts install workflow after introducing Read-Only mode
  charts/hedera-json-rpc-relay-websocket/ci/default-values.yaml
  charts/hedera-json-rpc-relay/ci/default-values.yaml
  charts/hedera-json-rpc/ci/default-values.yaml
Labels: bug

#3934 feat: remove cache from `eth_blockNumber`
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth/eth_getBlockByNumber.spec.ts
Labels: enhancement

#3936 feat: unify treatment of HEDERA_NETWORK value in Relay and WS charts
  charts/hedera-json-rpc-relay-websocket/templates/configmap.yaml
Labels: enhancement

#3865 feat: add MAX_GAS_ALLOWANCE_HBAR configuration
  charts/hedera-json-rpc-relay/values.yaml
  docs/configuration.md
  packages/config-service/src/services/globalConfig.ts
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/precheck.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
Labels: enhancement

#3945 chore: improve pull request template for clarity and review effectiveness
  .github/pull_request_template.md
Labels: internal

#3950 fix: displayed error message for `InternalError`
  packages/server/src/koaJsonRpc/index.ts
  packages/server/src/koaJsonRpc/lib/RpcError.ts
  packages/server/tests/integration/koaJsonRpc/rpcError.spec.ts
  packages/ws-server/src/controllers/jsonRpcController.ts
Labels: bug

#3952 feat: display request payload in log level `INFO`
  packages/relay/src/lib/dispatcher/rpcMethodDispatcher.ts
Labels: enhancement

#3946 chore: improve test coverage for sdkClient
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/tests/lib/eth/eth_call.spec.ts
  packages/relay/tests/lib/fixtures/transactionBufferFixture.ts
  packages/relay/tests/lib/sdkClient.spec.ts
Labels: enhancement

#3904 chore: Add testing documentation regarding conformity tests
  CONFORMITY_TESTING.md
  README.md
  packages/server/tests/acceptance/data/conformity/overwrites/README.md
Labels: documentation, ArianeLabs

#3941 feat: paymaster functionality
  docs/configuration.md
  packages/config-service/src/services/globalConfig.ts
  packages/config-service/tests/configServiceTestHelper.ts
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/precheck.ts
  packages/relay/src/lib/services/ethService/ethCommonService/CommonService.ts
  packages/relay/tests/lib/precheck.spec.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
  packages/server/tests/acceptance/sendRawTransactionExtension.spec.ts
Labels: enhancement

#3859 feat: update `getBalance` method to require `blockNumberOrTagOrHash` parameter instead of allowing null (#3838)
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/services/ethService/accountService/AccountService.ts
  packages/relay/src/lib/services/ethService/accountService/IAccountService.ts
  packages/relay/tests/lib/eth/eth_getBalance.spec.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
Labels: enhancement

#3977 feat: increased k6 coverage for all RPC endpoints
  k6/src/prepare/prep.js
  k6/src/scenarios/test/debug_traceBlockByNumber.js
  k6/src/scenarios/test/debug_traceTransaction.js
  k6/src/scenarios/test/eth_blobBaseFee.js
  k6/src/scenarios/test/eth_createAccessList.js
  k6/src/scenarios/test/eth_getFilterChanges.js
  k6/src/scenarios/test/eth_getFilterLogs.js
  k6/src/scenarios/test/eth_getProof.js
  k6/src/scenarios/test/eth_maxPriorityFeePerGas.js
  k6/src/scenarios/test/eth_newBlockFilter.js
  k6/src/scenarios/test/eth_newFilter.js
  k6/src/scenarios/test/eth_newPendingTransactionFilter.js
  k6/src/scenarios/test/eth_uninstallFilter.js
  k6/src/scenarios/test/index.js
  k6/src/scenarios/test/net_peerCount.js
  k6/src/scenarios/test/web3_sha3.js
Labels: internal

#3984 chore: use Node's native `fetch` in PR check workflow
  .github/scripts/check-pr.js
  .github/workflows/pr-label-milestone-check.yml
Labels: github_action, internal

#3978 fix: replaces nyc with c8
  .c8rc.json
  codecov.yml
  package-lock.json
  package.json
  packages/config-service/package.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
  packages/ws-server/tsconfig.json
Labels: enhancement, internal
