Repository hiero-ledger/hiero-json-rpc-relay, pull requests merged in 2025-03, with the labels that each got.

#3507 build: [Snyk] Upgrade lerna from 8.1.8 to 8.1.9
  package-lock.json
  package.json
Labels: dependencies

#3478 build: [Snyk] Upgrade @graphprotocol/graph-cli from 0.94.0 to 0.95.0
  tools/subgraph-example/subgraph/package.json
Labels: dependencies

#3524 chore: set debug level for improved visibility and easier troubleshooting in eth_sendRawTransaction
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/db/repositories/hbarLimiter/evmAddressHbarSpendingPlanRepository.ts
  packages/relay/src/lib/db/repositories/hbarLimiter/hbarSpendingPlanRepository.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/services/hbarLimitService/index.ts
  packages/relay/src/lib/services/metricService/metricService.ts
Labels: Technical Debt, internal

#3510 feat: adds logic for `engine_*` rpc methods which indicates they're not supported
  docs/rate-limiting.md
  packages/relay/src/lib/relay.ts
  packages/server/src/koaJsonRpc/index.ts
  packages/server/src/routes/otherRoutes.ts
  packages/server/src/server.ts
  packages/server/tests/acceptance/data/conformity-tests-batch-3.json
  packages/server/tests/acceptance/rpc_batch2.spec.ts
  packages/server/tests/helpers/constants.ts
  packages/server/tests/integration/server.spec.ts
  packages/server/tests/postman.json
Labels: enhancement

#3469 feat: adds proper structure to automatic bumping PRs
  .github/scripts/check-pr.js
  .github/snyk_pull_request_template.yaml
Labels: internal

#3523 feat: execute `WHBAR` tests against already existing contract
  tools/whbar-hardhat-example/.env.example
  tools/whbar-hardhat-example/README.md
  tools/whbar-hardhat-example/test/WHBAR.js
Labels: enhancement

#3522 feat: add a deterministic WHBAR deployment script
  tools/whbar-hardhat-example/.env.example
  tools/whbar-hardhat-example/README.md
  tools/whbar-hardhat-example/contracts/WHBAR.sol
  tools/whbar-hardhat-example/hardhat.config.js
  tools/whbar-hardhat-example/test/WHBAR.js
  tools/whbar-hardhat-example/verification_file.json
Labels: enhancement

#3539 chore: add additional `transfer` check
  tools/whbar-hardhat-example/contracts/WHBAR.sol
  tools/whbar-hardhat-example/test/WHBAR.js
  tools/whbar-hardhat-example/verification_file.json
Labels: enhancement

#3513 feat: adds logic for handling trace_* rpc methods
  docs/rate-limiting.md
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/server/src/routes/otherRoutes.ts
  packages/server/tests/acceptance/data/conformity-tests-batch-3.json
  packages/server/tests/helpers/constants.ts
  packages/server/tests/integration/server.spec.ts
  packages/server/tests/postman.json
Labels: enhancement

#3543 chore: add total HBAR rate limit gauge metric for monitoring
  packages/relay/src/lib/services/hbarLimitService/index.ts
Labels: internal

#3531 feat: adds support for arrays in ConfigService
  packages/config-service/src/services/globalConfig.ts
  packages/config-service/src/services/validationService.ts
  packages/config-service/tests/src/services/validationService.spec.ts
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/services/hapiService/hapiService.ts
  packages/relay/src/utils.ts
  packages/relay/tests/lib/eth/eth_call.spec.ts
  packages/relay/tests/lib/hapiService.spec.ts
  packages/relay/tests/lib/utils.spec.ts
  packages/server/src/koaJsonRpc/index.ts
  packages/server/tests/acceptance/rpc_batch3.spec.ts
  packages/ws-server/src/webSocketServer.ts
  packages/ws-server/tests/acceptance/batchRequest.spec.ts
Labels: enhancement

#3546 feat: add `WHBAR` contract deployment example under tools folder
  tools/whbar-hardhat-example/.env.example
  tools/whbar-hardhat-example/.gitignore
  tools/whbar-hardhat-example/Dockerfile
  tools/whbar-hardhat-example/README.md
  tools/whbar-hardhat-example/contracts/WHBAR.sol
  tools/whbar-hardhat-example/fund.js
  tools/whbar-hardhat-example/hardhat.config.js
  tools/whbar-hardhat-example/package-lock.json
  tools/whbar-hardhat-example/package.json
  tools/whbar-hardhat-example/test/WHBAR.js
  tools/whbar-hardhat-example/verification_file.json
Labels: enhancement

#3545 fix(metrics): handled BigNumber values in operator balance metric
  packages/relay/src/lib/relay.ts
Labels: internal

#3495 fix: fixes flaky CI tests in RPC Batch 2
  packages/server/tests/acceptance/rpc_batch2.spec.ts
Labels: bug

#3535 build: [Snyk] Security upgrade @hashgraph/sdk from 2.59.0 to 2.60.1
  dapp-example/package-lock.json
  dapp-example/package.json
Labels: dependencies

#3561 chore: update runners and codeowners to use hiero runners and teams
  .github/CODEOWNERS
  .github/workflows/acceptance-public.yml
  .github/workflows/acceptance-workflow.yml
  .github/workflows/acceptance.yml
  .github/workflows/charts.yml
  .github/workflows/conformity-workflow.yml
  .github/workflows/dapp.yml
  .github/workflows/dev-tool-workflow.yml
  .github/workflows/flow-pr-title-check.yml
  .github/workflows/foundry.yml
  .github/workflows/image-build.yml
  .github/workflows/manual-testing.yml
  .github/workflows/postman.yml
  .github/workflows/pr-label-milestone-check.yml
  .github/workflows/release-acceptance.yml
  .github/workflows/release-automation.yml
  .github/workflows/release-integration.yml
  .github/workflows/release-production.yml
  .github/workflows/subgraph.yml
  .github/workflows/test.yml
Labels: github_action

#3578 ci: Add gh-pages-sync workflow to json-rpc-relay
  .github/workflows/gh-pages-sync.yaml
Labels: github_action

#3555 refactor: normalize routes and reorganize service implementations
  packages/relay/src/index.ts
  packages/relay/src/lib/debug.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/net.ts
  packages/relay/src/lib/poller.ts
  packages/relay/src/lib/relay.ts
  packages/relay/src/lib/services/debugService/IDebugService.ts
  packages/relay/src/lib/services/ethService/ethFilterService/IFilterService.ts
  packages/relay/src/lib/services/ethService/ethFilterService/index.ts
  packages/relay/src/lib/types/index.ts
  packages/relay/src/lib/types/requestParams.ts
  packages/relay/src/lib/web3.ts
  packages/relay/tests/lib/debug.spec.ts
  packages/relay/tests/lib/eth/eth_common.spec.ts
  packages/relay/tests/lib/eth/eth_getLogs.spec.ts
  packages/relay/tests/lib/eth/eth_getStorageAt.spec.ts
  packages/relay/tests/lib/net.spec.ts
  packages/relay/tests/lib/openrpc.spec.ts
  packages/relay/tests/lib/relay.spec.ts
  packages/relay/tests/lib/services/eth/filter.spec.ts
  packages/relay/tests/lib/web3.spec.ts
  packages/server/src/routes/debugRoutes.ts
  packages/server/src/routes/ethRoutes.ts
  packages/server/src/server.ts
  packages/server/src/validator/constants.ts
  packages/server/src/validator/types.ts
  packages/server/tests/integration/server.spec.ts
  packages/server/tests/integration/validator.spec.ts
  packages/ws-server/src/controllers/index.ts
  packages/ws-server/src/utils/utils.ts
  packages/ws-server/src/webSocketServer.ts
  packages/ws-server/tests/unit/utils.spec.ts
Labels: enhancement

#3580 feat: update `WHBAR` readme
  tools/whbar-hardhat-example/README.md
Labels: enhancement

#3583 fix: change urls to repo in charts directory
  charts/hedera-json-rpc-relay-websocket/Chart.yaml
  charts/hedera-json-rpc-relay-websocket/values.yaml
  charts/hedera-json-rpc-relay/Chart.yaml
  charts/hedera-json-rpc-relay/templates/cronjob.yaml
  charts/hedera-json-rpc-relay/value-test.yaml
  charts/hedera-json-rpc-relay/values.yaml
  charts/hedera-json-rpc/Chart.yaml
Labels: bug

#3559 feat: add GET `/config` route
  README.md
  docs/configuration.md
  packages/config-service/src/services/globalConfig.ts
  packages/config-service/src/services/index.ts
  packages/config-service/tests/src/services/configService.spec.ts
  packages/relay/src/index.ts
  packages/relay/src/lib/admin.ts
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/relay.ts
  packages/relay/src/utils.ts
  packages/relay/tests/lib/admin.spec.ts
  packages/relay/tests/lib/utils.spec.ts
  packages/server/src/koaJsonRpc/lib/methodConfiguration.ts
  packages/server/src/server.ts
  packages/server/tests/integration/formatters.spec.ts
Labels: enhancement

#3591 fix: fixed net_listening to return boolean `true`
  charts/hedera-json-rpc-relay/postman.json
  packages/relay/src/lib/net.ts
  packages/relay/tests/lib/net.spec.ts
  packages/server/src/routes/netRoutes.ts
  packages/server/tests/acceptance/data/conformity-tests-batch-3.json
  packages/server/tests/acceptance/rpc_batch2.spec.ts
  packages/server/tests/integration/server.spec.ts
  packages/server/tests/postman.json
Labels: bug

#3521 feat: Include support for getblockreceipts
  k6/src/scenarios/test/eth_getBlockReceipts.js
  k6/src/scenarios/test/index.js
  packages/relay/src/index.ts
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/services/ethService/ethCommonService/index.ts
  packages/relay/tests/helpers.ts
  packages/relay/tests/lib/eth/eth-config.ts
  packages/relay/tests/lib/eth/eth_getBlockReceipts.spec.ts
  packages/server/src/koaJsonRpc/lib/methodConfiguration.ts
  packages/server/src/routes/ethRoutes.ts
  packages/server/src/validator/methods.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
  packages/server/tests/helpers/constants.ts
  packages/ws-server/src/utils/utils.ts
Labels: enhancement

#3595 feat: create `FeeService` class
  packages/relay/src/lib/debug.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/relay.ts
  packages/relay/src/lib/services/blockService/index.ts
  packages/relay/src/lib/services/ethService/ethCommonService/ICommonService.ts
  packages/relay/src/lib/services/ethService/ethCommonService/index.ts
  packages/relay/src/lib/services/factories/transactionFactory.ts
  packages/relay/src/lib/services/feeService/IFeeService.ts
  packages/relay/src/lib/services/feeService/index.ts
  packages/relay/tests/lib/eth/eth_getTransactionReceipt.spec.ts
Labels: enhancement

#3598 feat: add an addition check on the `HTSConnector` contract under the `layer-zero` example
  tools/layer-zero-example/contracts/HTSConnector.sol
Labels: enhancement

#3604 ci: Add GPG sign-off to commit options
  .github/workflows/release-automation.yml
Labels: github_action

#3581 feat: implemented decorator-based RPC method dispatcher and parameter handling system
  charts/hedera-json-rpc-relay/postman.json
  packages/relay/src/lib/debug.ts
  packages/relay/src/lib/decorators/index.ts
  packages/relay/src/lib/decorators/rpcMethod.decorator.ts
  packages/relay/src/lib/decorators/rpcParamLayoutConfig.decorator.ts
  packages/relay/src/lib/decorators/rpcParamValidationRules.decorator.ts
  packages/relay/src/lib/dispatcher/index.ts
  packages/relay/src/lib/dispatcher/rpcMethodDispatcher.ts
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/net.ts
  packages/relay/src/lib/relay.ts
  packages/relay/src/lib/services/registryService/rpcMethodRegistryService.ts
  packages/relay/src/lib/types/index.ts
  packages/relay/src/lib/types/registry.ts
  packages/relay/src/lib/types/validation.ts
  packages/relay/src/lib/validators/constants.ts
  packages/relay/src/lib/validators/index.ts
  packages/relay/src/lib/validators/objectTypes.ts
  packages/relay/src/lib/validators/types.ts
  packages/relay/src/lib/validators/utils.ts
  packages/relay/src/lib/web3.ts
  packages/relay/src/utils.ts
  packages/relay/tests/lib/decorators/rpcMethod.spec.ts
  packages/relay/tests/lib/decorators/rpcParamLayoutConfig.spec.ts
  packages/relay/tests/lib/decorators/rpcParamSchema.spec.ts
  packages/relay/tests/lib/dispatcher/rpcMethodDispatcher.spec.ts
  packages/relay/tests/lib/services/registry/rpcMethodRegistry.spec.ts
  packages/relay/tests/lib/utils.spec.ts
  packages/relay/tests/lib/validators/validators.spec.ts
  packages/relay/tsconfig.json
  packages/server/src/koaJsonRpc/index.ts
  packages/server/src/routes/debugRoutes.ts
  packages/server/src/routes/ethRoutes.ts
  packages/server/src/routes/netRoutes.ts
  packages/server/src/routes/otherRoutes.ts
  packages/server/src/routes/web3Routes.ts
  packages/server/src/server.ts
  packages/server/src/types/validator/index.ts
  packages/server/src/types/validator/methods.ts
  packages/server/src/types/validator/objectTypes.ts
  packages/server/src/types/validator/types.ts
  packages/server/src/utils.ts
  packages/server/src/validator/methods.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
  packages/server/tests/acceptance/rpc_batch3.spec.ts
  packages/server/tests/integration/server.spec.ts
  packages/server/tests/postman.json
  packages/ws-server/src/controllers/index.ts
  packages/ws-server/src/utils/utils.ts
  packages/ws-server/src/utils/validators.ts
  packages/ws-server/src/webSocketServer.ts
  packages/ws-server/tests/acceptance/validations.spec.ts
  packages/ws-server/tests/unit/utils.spec.ts
Labels: enhancement

#3609 test: Add test coverage for traceTransaction parameter parsing logic
  packages/relay/tests/lib/utils.spec.ts
Labels: Technical Debt, internal

#3605 fix: added safe guard for rewardPercentiles size limit
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth/eth_feeHistory.spec.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
  packages/server/tests/helpers/constants.ts
Labels: enhancement

#3547 feat: change acceptance.yml to use matrix and tweak configurations for a more optimal CI flow
  .github/workflows/acceptance.yml
  packages/server/tests/localAcceptance.env
Labels: enhancement
