Repository hiero-ledger/hiero-json-rpc-relay, pull requests merged in 2025-08, with the labels that each got.

#4148 chore: removes deprecated husky lines
  .husky/commit-msg
  .husky/pre-commit
  package.json
Labels: internal

#4164 chore: remove unused packages
  package-lock.json
  package.json
  packages/relay/package.json
  packages/relay/src/utils.ts
  packages/relay/tests/lib/utils.spec.ts
  packages/server/package.json
  packages/ws-server/package.json
Labels: dependencies

#4081 refactor: improve execution event handling
  package-lock.json
  packages/relay/package.json
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/relay.ts
  packages/relay/src/lib/services/ethService/transactionService/TransactionService.ts
  packages/relay/src/lib/services/hapiService/hapiService.ts
  packages/relay/src/lib/services/metricService/metricService.ts
  packages/relay/src/lib/types/events.ts
  packages/relay/tests/lib/debug.spec.ts
  packages/relay/tests/lib/eth/eth-helpers.ts
  packages/relay/tests/lib/eth/eth_estimateGas.spec.ts
  packages/relay/tests/lib/eth/eth_getBlockByHash.spec.ts
  packages/relay/tests/lib/eth/eth_getBlockByNumber.spec.ts
  packages/relay/tests/lib/ethGetBlockBy.spec.ts
  packages/relay/tests/lib/hapiService.spec.ts
  packages/relay/tests/lib/openrpc.spec.ts
  packages/relay/tests/lib/sdkClient.spec.ts
  packages/relay/tests/lib/services/metricService/metricService.spec.ts
Labels: enhancement

#4176 feat: removes custom CPU and Memory usage Gauge
  charts/hedera-json-rpc/dashboards/webSocketServer.json
  packages/ws-server/src/metrics/wsMetricRegistry.ts
  packages/ws-server/src/utils/constants.ts
  packages/ws-server/tests/unit/wsMetricRegistry.spec.ts
Labels: enhancement

#4192 docs: indicate proper error codes for unsupported methods
  docs/openrpc.json
  packages/relay/src/index.ts
  packages/relay/src/lib/eth.ts
  packages/relay/src/lib/services/ethService/ethFilterService/FilterService.ts
  packages/relay/src/lib/services/ethService/ethFilterService/IFilterService.ts
  packages/relay/tests/lib/openrpc.spec.ts
Labels: documentation

#4198 fix: add `value` in transaction object for synthetic transactions
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/factories/transactionFactory.ts
  packages/relay/src/lib/services/ethService/blockService/BlockService.ts
  packages/relay/tests/lib/eth/eth_getTransactionByHash.spec.ts
Labels: bug

#4207 fix: sets node version to 22.17
  .github/workflows/acceptance-workflow.yml
  .github/workflows/conformity-workflow.yml
  .github/workflows/dapp.yml
  .github/workflows/dev-tool-workflow.yml
  .github/workflows/openrpc-updater.yml
  .github/workflows/postman.yml
  .github/workflows/pr-label-milestone-check.yml
  .github/workflows/release-acceptance.yml
  .github/workflows/release-automation.yml
  .github/workflows/release-production.yml
  .github/workflows/subgraph.yml
  .github/workflows/test.yml
Labels: bug, internal

#4220 chore: refine npm weekly group updates
  .github/dependabot.yml
Labels: dependencies

#4302 build(deps): bump lru-cache from 7.14.0 to 11.1.0
  package-lock.json
  packages/relay/package.json
  packages/relay/src/lib/clients/cache/localLRUCache.ts
  packages/ws-server/package.json
  packages/ws-server/src/service/subscriptionService.ts
Labels: enhancement

#4219 chore: updates prom-client to new major version
  package-lock.json
  package.json
  packages/ws-server/tests/unit/utils.spec.ts
Labels: internal

#4310 chore(release): Bump versions for v0.72.0-SNAPSHOT
  charts/hedera-json-rpc-relay-websocket/Chart.yaml
  charts/hedera-json-rpc-relay/Chart.yaml
  charts/hedera-json-rpc/Chart.yaml
  docs/openrpc.json
  package-lock.json
  package.json
  packages/config-service/package.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: process
