Repository hiero-ledger/hiero-json-rpc-relay, pull requests merged in 2025-02, with the labels that each got.

#3439 chore(release): Bump versions for v0.66.0-SNAPSHOT
  charts/hedera-json-rpc-relay-websocket/Chart.yaml
  charts/hedera-json-rpc-relay/Chart.yaml
  charts/hedera-json-rpc/Chart.yaml
  docs/openrpc.json
  package-lock.json
  package.json
  packages/config-service/package.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: process

#3435 feat: refactor mirrorNodeClient axios `transformResponse` and fix all unit tests
  packages/relay/src/lib/clients/mirrorNodeClient.ts
  packages/relay/tests/lib/eth/eth_call.spec.ts
  packages/relay/tests/lib/eth/eth_estimateGas.spec.ts
  packages/relay/tests/lib/eth/eth_feeHistory.spec.ts
  packages/relay/tests/lib/eth/eth_gasPrice.spec.ts
  packages/relay/tests/lib/eth/eth_getBalance.spec.ts
  packages/relay/tests/lib/eth/eth_getBlockByHash.spec.ts
  packages/relay/tests/lib/eth/eth_getBlockByNumber.spec.ts
  packages/relay/tests/lib/eth/eth_getBlockTransactionCountByHash.spec.ts
  packages/relay/tests/lib/eth/eth_getBlockTransactionCountByNumber.spec.ts
  packages/relay/tests/lib/eth/eth_getCode.spec.ts
  packages/relay/tests/lib/eth/eth_getLogs.spec.ts
  packages/relay/tests/lib/eth/eth_getStorageAt.spec.ts
  packages/relay/tests/lib/eth/eth_getTransactionByBlockHashAndIndex.spec.ts
  packages/relay/tests/lib/eth/eth_getTransactionByBlockNumberAndIndex.spec.ts
  packages/relay/tests/lib/eth/eth_getTransactionByHash.spec.ts
  packages/relay/tests/lib/eth/eth_getTransactionCount.spec.ts
  packages/relay/tests/lib/eth/eth_getTransactionReceipt.spec.ts
  packages/relay/tests/lib/eth/eth_sendRawTransaction.spec.ts
  packages/relay/tests/lib/mirrorNodeClient.spec.ts
  packages/relay/tests/lib/openrpc.spec.ts
  packages/relay/tests/lib/precheck.spec.ts
  packages/relay/tests/lib/sdkClient.spec.ts
  packages/relay/tests/lib/services/debugService/debug.spec.ts
  packages/relay/tests/lib/services/eth/filter.spec.ts
  packages/relay/tests/lib/services/metricService/metricService.spec.ts
Labels: enhancement

#3438 build: [Snyk] Upgrade @mui/material from 5.16.13 to 5.16.14
  dapp-example/package-lock.json
  dapp-example/package.json
Labels: dependencies

#3437 build: [Snyk] Upgrade ethers from 6.13.4 to 6.13.5
  k6/package-lock.json
  k6/package.json
Labels: dependencies

#3452 fix(test): equipped a more appropriate block range for eth_getLogs WS release test
  packages/ws-server/tests/acceptance/getLogs.spec.ts
Labels: internal

#3463 fix: Resolve BigInt type mismatch in eth_sendRawTransaction precheck
  packages/relay/src/lib/precheck.ts
  packages/relay/tests/lib/precheck.spec.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
Labels: bug

#3464 chore: cherry pick fix: Resolve BigInt type mismatch in eth_sendRawTransaction precheck (#3463) to release/0.65
  packages/relay/src/lib/precheck.ts
  packages/relay/tests/lib/precheck.spec.ts
  packages/server/tests/acceptance/rpc_batch1.spec.ts
Labels: process

#3459 chore: updated grafana dashboard for better visibility on Ethereum RPC Execution Methods
  charts/hedera-json-rpc/dashboards/hedera-json-rpc-relay-http-server.json
Labels: internal

#3454 build: [Snyk] Upgrade @graphprotocol/graph-cli from 0.93.3 to 0.94.0
  tools/subgraph-example/subgraph/package.json
Labels: dependencies

#3453 build: [Snyk] Upgrade pnpm from 9.15.2 to 9.15.4
  package-lock.json
  package.json
Labels: dependencies

#3473 chore(release): Bump versions for v0.67.0-SNAPSHOT
  charts/hedera-json-rpc-relay-websocket/Chart.yaml
  charts/hedera-json-rpc-relay/Chart.yaml
  charts/hedera-json-rpc/Chart.yaml
  docs/openrpc.json
  package-lock.json
  package.json
  packages/config-service/package.json
  packages/relay/package.json
  packages/server/package.json
  packages/ws-server/package.json
Labels: process

#3433 fix: fixed eth_getCode to now use blockNumber when address is an HTS token
  packages/relay/src/lib/eth.ts
  packages/relay/tests/lib/eth/eth_getCode.spec.ts
  packages/server/tests/acceptance/rpc_batch2.spec.ts
Labels: bug

#3472 fix: fixed CI release automation to create release notes automatically
  .github/release-notes.yml
  .github/workflows/release-automation.yml
Labels: internal

#3498 feat: fix eslint
  .eslintrc.js
Labels: enhancement

#3497 feat: filter out some methods from batch requests
  docs/configuration.md
  docs/design/batch-request.md
  packages/config-service/src/services/globalConfig.ts
  packages/relay/src/lib/errors/JsonRpcError.ts
  packages/server/src/koaJsonRpc/index.ts
  packages/server/tests/acceptance/rpc_batch3.spec.ts
  packages/ws-server/src/webSocketServer.ts
  packages/ws-server/tests/acceptance/batchRequest.spec.ts
Labels: enhancement

#3482 fix: reduced TTL for feeHistory, getTinyBarGasFee, and getPrice
  packages/relay/src/lib/clients/sdkClient.ts
  packages/relay/src/lib/constants.ts
  packages/relay/src/lib/eth.ts
Labels: bug

#3500 chore: turned USE_ASYNC_TX_PROCESSING to true by default
  charts/hedera-json-rpc-relay-websocket/values.yaml
  charts/hedera-json-rpc-relay/values.yaml
  docs/configuration.md
  packages/config-service/src/services/globalConfig.ts
Labels: internal

#3501 feat: add `web3_sha3` support
  docs/openrpc.json
  docs/rate-limiting.md
  packages/relay/src/index.ts
  packages/relay/src/lib/web3.ts
  packages/relay/tests/lib/openrpc.spec.ts
  packages/relay/tests/lib/web3.spec.ts
  packages/server/src/koaJsonRpc/lib/methodConfiguration.ts
  packages/server/src/server.ts
  packages/server/src/validator/methods.ts
  packages/server/tests/acceptance/data/conformity-tests-batch-3.json
  packages/server/tests/helpers/constants.ts
  packages/server/tests/integration/server.spec.ts
  packages/server/tests/postman.json
  packages/ws-server/src/utils/constants.ts
Labels: enhancement

#3504 feat: update `totalSupply` logic on WHBAR contract
  tools/whbar-hardhat-example/contracts/WHBAR.sol
  tools/whbar-hardhat-example/package-lock.json
  tools/whbar-hardhat-example/package.json
  tools/whbar-hardhat-example/test/WHBAR.js
  tools/whbar-hardhat-example/verification_file.json
Labels: enhancement

#3475 build: [Snyk] Upgrade ethers from 6.13.4 to 6.13.5
  dapp-example/package-lock.json
  dapp-example/package.json
Labels: dependencies

#3496 build: [Snyk] Security upgrade @hashgraph/sdk from 2.56.0 to 2.59.0
  dapp-example/package-lock.json
  dapp-example/package.json
Labels: dependencies

#3509 feat: torn down`server.ts` into separate routes
  packages/server/src/routes/debugRoutes.ts
  packages/server/src/routes/ethRoutes.ts
  packages/server/src/routes/netRoutes.ts
  packages/server/src/routes/web3Routes.ts
  packages/server/src/server.ts
  packages/server/src/utils.ts
Labels: enhancement
